### ISSUE TITLE
i386 support?

### ISSUE THREAD

**Issue by piotr1212** [grobian/carbon-c-relay#100]
While building rpm's for epel rhel5 I noticed that carbon-c-relay fails to build on i386. As this is very old, I was wondering if you are willing to make i386 work or not. If not, please comment here, then I will exclude the i386 arch from builds. Don't think many people still use i386.

Also do you expect (or know) if ti works on Big Endian architectures?  Fedora builds for some Big Endian archs automatically, but I don't have access to any Big Endian machines at this moment to test...

<pre><code>
+ make -j4 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables' relay
/bin/sh: git: command not found
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o relay.o relay.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o md5.o md5.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o consistent-hash.o consistent-hash.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o receptor.o receptor.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o dispatcher.o dispatcher.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o router.o router.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o queue.o queue.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o server.o server.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o collector.o collector.c
cc -fopenmp -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -DGIT_VERSION=\"2015-08-31\" -pthread   -c -o aggregator.o aggregator.c
cc -fopenmp -o relay  relay.o md5.o consistent-hash.o receptor.o dispatcher.o router.o queue.o server.o collector.o aggregator.o  -pthread
dispatcher.o: In function `dispatch_addconnection':
/builddir/build/BUILD/carbon-c-relay-38fac767bf35aa6ecc4f9ea0c8861607325789bf/dispatcher.c:169: undefined reference to `__sync_bool_compare_and_swap_1'
dispatcher.o: In function `dispatch_addlistener':
/builddir/build/BUILD/carbon-c-relay-38fac767bf35aa6ecc4f9ea0c8861607325789bf/dispatcher.c:117: undefined reference to `__sync_bool_compare_and_swap_4'
dispatcher.o: In function `dispatch_runner':
/builddir/build/BUILD/carbon-c-relay-38fac767bf35aa6ecc4f9ea0c8861607325789bf/dispatcher.c:519: undefined reference to `__sync_bool_compare_and_swap_1'
collect2: ld returned 1 exit status
make: *** [relay] Error 1
</code></pre>

**Comment by Civil** [comment]
I think it's related to old GCC, which do not have __sync primitives.

**Comment by piotr1212** [comment]
Build succeeded on el5 x86_64 which should have the same gcc version. From what I could find is that those primitives got introduced in i486..

http://koji.fedoraproject.org/koji/taskinfo?taskID=10892303

**Comment by grobian** [comment]
Oh joy, I guess that would be nasty, as some of them are pretty much necessary to avoid conflicts.

**Comment by grobian** [comment]
re bigendian: my sparc isn't up at the moment, but I don't anticipate any problems since I don't do byte tricks as far as I recall

**Comment by piotr1212** [comment]
OK Thanks, I will disable builds on i386 and keep other archs enabled.

**Comment by grobian** [comment]
Just for the record: I think with pthread locks we could work around this, but there seems no real usecase for it at the moment.

**Comment by piotr1212** [comment]
32 Bit PPC also fails with the same errors.

I don't think there are many RHEL-5 i386 users left, if there are they could probably build with -march=i486

**Comment by grobian** [comment]
PPC doesn't have them either? that's a bugger!

**Comment by grobian** [comment]
Weird, GCC says they should be there.  What version of GCC is being used on these platforms?

**Comment by piotr1212** [comment]
Only 32 bit PPC on rhel5 fails.  64 bit PPC rhel6 builds fine. 

TBH: I didn't really look into this.... just disabled the build.

gcc version: 
gcc.ppc 0:4.1.2-55.el5 


Fedora build task:
http://koji.fedoraproject.org/koji/taskinfo?taskID=10898956

**Comment by grobian** [comment]
Oh, that's like what, a couple? of decades back ago.  Right, if we're all happy with this, then let's not care about it.

**Comment by oyermolenko** [comment]
Hi
having approximately 100 old centos5 i386 built with success using gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) and without -march=i486 ... just info

**Comment by piotr1212** [comment]
Thanks for sharing. rhel 5 is going eol this month so I won't be bothering this.
