### ISSUE TITLE
relay statistics not showing up in carbon

### ISSUE THREAD

**Issue by ronvisser** [grobian/carbon-c-relay#101]
When I start relay with the "-s" flag the internal statistics are not propagated to carbon.
I had a quick look at the code and think the test in collector.c (in function collector_start) should be reversed.
i.e. 
if (mode != SUBMISSION) {
should be
 if (mode == SUBMISSION) {

**Comment by grobian** [comment]
submission mode was designed to be exactly like this, I've improved the description, which should make it more clear what "submission" mode means.
