### ISSUE TITLE
Does carbon-c-relay perform a toLowerCase on the incoming metric names?

### ISSUE THREAD

**Issue by costimuraru** [grobian/carbon-c-relay#102]
We have a system sending metrics that contain upper case characters (metrics are retrieved from a third party library, so we can't really change them). We use multiple clusters and multiple relays (some of which are the standard graphite-relay, others carbon-c-relay). We noticed an inconsistency with metrics being sent with the original uppercase letters by standard graphite-relay and with full lowercase by carbon-c-relay.

Because of the inconsistency we can't query across graphite clusters. 

Is this lower case transition intended? Can it be disabled?

Thanks!

**Comment by grobian** [comment]
It depends on your config.  carbon-c-relay doesn't do anything to the casing of your metrics by default.  It does replace characters it doesn't like, see irregular char replacement in the README: https://github.com/grobian/carbon-c-relay/blob/master/README.md

If you use a replacement rule with lowercase output, carbon-c-relay will indeed do the translation.  See the rewrite rules section in the same README.
