### ISSUE TITLE
expire after time is from start of bucket, not end

### ISSUE THREAD

**Issue by tjamesturner** [grobian/carbon-c-relay#103]
when checking for bucket expiration, we compare "now" to the "bucket start" plus "expire after". this is inconsistent with the documentation on the main github page which implies it is relative to the bucket end. also, we might consider validating that the expiry >= interval, since expiring a bucket before it is over is probably never what the user wants.

specifically, this is **the wording i think needs to be changed**
from: 
"In the example, 35 was used, which means after **35 + 10** seconds the first four aggregate metrics are produced. It also means that metrics can arrive **35** seconds late, and still be taken into account."
to:
"In the example, 35 was used, which means after **35** seconds the first four aggregate metrics are produced. It also means that metrics can arrive **25** seconds late, and still be taken into account."
on this page: https://github.com/grobian/carbon-c-relay

here is my **proposed validation code change** to aggregator.c:

    //if (interval == 0 || expire == 0) {
    if (interval == 0 || expire < interval) {

here is the relevant (presumably correct) expiration code from aggregator.c:

    while (inv->buckets[0].start +
        (keep_running ? inv->expire : s->expire) < now)

**Comment by grobian** [comment]
It appears you really torture my self-respect regarding correctness of this piece of code and its derivatives :)

Looking at this, it seem a documentation update such as you suggested fixes this issue, right?

**Comment by tjamesturner** [comment]
sorry if i offended you. i am just doing a lot of work in this area to try to improve performance of our cassandra cluster.  

yes, a simple documentation update would be sufficient. however, i think the validation change i proposed would be helpful too since this is an easy mistake to make and some simple validation could save people time when they are new to the application.

**Comment by grobian** [comment]
Don't feel bad!  It's good we can improve this code, it is extremely complex ever since it does dynamic invocations.

**Comment by grobian** [comment]
The implementation does a sneaky trick in the back, it adds random seconds to the expiration of in total expiration (e.g. double).  Thus, metrics are soonest expired after expire, but likely later.

**Comment by grobian** [comment]
The implementation does a sneaky trick in the back, it adds random seconds to the expiration of in total expiration (e.g. double).  Thus, metrics are soonest expired after expire, but likely later.  I've changed this in the README.
(Sorry for getting back with such a delay, my employer doesn't allow me to work on this at the moment.)
