### ISSUE TITLE
time buckets should start on even edges

### ISSUE THREAD

**Issue by tjamesturner** [grobian/carbon-c-relay#104]
currently time buckets or "invocations" start at arbitrary points in time based on when the first metric is received. ideally, buckets should always start on the zeros since this is how graphite and cyanite group timestamps.  this mismatch can cause data to be aggregated into the wrong time intervals.

here is a specific scenario highlighting such a potential issue:
our bucket interval is 10 seconds, both in carbon-c-relay and cyanite (or carbon-cache)
a metric is received with timestamp 12:00:05 causing the relay to create buckets starting at 12:00:05, 12:00:15, etc.
a metric is received with timestamp 12:00:11
carbon-c-relay adds the 12:00:11 metric to a bucket spanning 12:00:05-12:00:15
carbon-c-relay eventually expires the bucket and sends it to cyanite labelled 12:00:05
cyanite sees a metric at 12:00:05 and puts it in the 12:00:00-12:00:10 bucket
you now have data timestamped as 12:00:11 in a bucket representing 12:00:00-12:00:10

the problem gets even worse if you chain your relays since each relay in the chain can move the metric by up to 1 interval.

the fix should be easy, simply add this line to aggregator.c:

			now = (now / s->interval) * s->interval;

here is the code in context:

			time(&now);
			now -= s->expire;
			//round to nearest bucket boundary
			now = (now / s->interval) * s->interval;
			invocation->expire = s->expire + (rand() % s->interval);

**Comment by grobian** [comment]
Ok, this might affect the thundering hurd pervention, so I'll have to dive into this to see what it would do.  I see it is important for some applications that the windows are "predictable", so it is good to have that.

**Comment by grobian** [comment]
this shouldn't affect the thundering herd prevention, since it only (consistently) shifts the start time, e.g. doesn't make it different, only sooner.
