### ISSUE TITLE
incorrect bucket counts

### ISSUE THREAD

**Issue by tjamesturner** [grobian/carbon-c-relay#105]
the relay currently creates too few buckets when the expiry time is slightly below 2 times the interval time.  also, it creates too many buckets when the expiry time is over 2 times the interval time.  ideally, we need buckets to cover from "expiry time" plus "splay" in the past up through the present. we also need 1 additional "future" bucket in case the relay does not expire a bucket immediately when it is eligible or system clocks are a bit off and we get data with "future" timestamps. this works out to at least 2 buckets, plus 1 for every interval or partial interval in the expiry period.

**example 1** (too few buckets, potential dropped metrics):

    every 10 seconds
    expire after 19 seconds

we need to cover 39 seconds worth of timestamps (19 for expiry + 10 for splay + 10 for the future bucket). 39 seconds can not fit into 3 buckets, but will fit in 4.
buckets currently created: 3 (1-2 past, 1 current, 0-1 future)
buckets ideally created: 4 (1-2 past, 1 current, 1-2 future)

**example 2** (too many buckets, cpu/memory waste):

    every 10 seconds
    expire after 60 seconds

we need to cover 80 seconds worth of timestamps (60 for expiry + 10 for splay + 10 for the future bucket). 80 seconds can not fit into 7 buckets, but will fit in 8.
buckets currently created: 13 (6-7 past, 1 current, 5-6 future)
buckets ideally created: 8 (6-7 past, 1 current, 0-1 future) note: when there are 0 future buckets, then the current bucket just started.

here is the **proposed fix** to aggregator.c:

	// ret->bucketcnt = (expire / interval) * 2 + 1 ;
	ret->bucketcnt = 3 + (expire-1) / interval;

in practice this does not usually cause erroneous metric dropping, since the "expire after" value is not normally immediately below 2 times the interval. even if the expiry was just 1 second below 2 times the interval, the relay would have to be 1 second late expiring the bucket and the splay would have to fall at the max of 1*interval to see an issue.  as for the other scenario, when the "expire after" value is particularly large relative to the interval, it only causes performance problems and not functional errors (assuming you do not become cpu or ram bound)

**Comment by grobian** [comment]
this may indeed be a bit tight where it shouldn't and overzealous where it doesn't have to

**Comment by grobian** [comment]
What do you think about:
``
ret->bucketcnt = (expire + (interval - 1) / interval) + 1 + 1;
``

ceil(expire/interval) so we cover the entire past, one for the current, and one for the future.

**Comment by grobian** [comment]
IIRC your expire - 1 works like floor() hence your 3.  So I guess mine is equal to yours.

**Comment by grobian** [comment]
I think I fixed it, if you disagree, please reopen, thanks!

**Comment by tjamesturner** [comment]
i might have my operator precedence confused, but i think you meant to write:

    ret->bucketcnt = (expire + interval - 1) / interval + 1 + 1;

which, yes, reduces to what i wrote, just more verbose.  
the way you typed it would reduce to this, which is clearly problematic:

    ret->bucketcnt = expire + 2;

**Comment by grobian** [comment]
bah, indeed, bleh
