### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by ravibhooshan** [grobian/carbon-c-relay#107]
Hi - I am new to Linux world so please help me in installing relay-c on linux. Is this avalibel for windows also.

Thanks,
Ravi

**Comment by grobian** [comment]
use your linux distribution's package to install, there is to the best of my knowledge no windows version

**Comment by ravibhooshan** [comment]
Thanks for your reply.  I searched but I didn't find any RPM package link.

**Comment by piotr1212** [comment]
RPM packages for Fedora are in the default repository (# dnf install carbon-c-relay). For RHEL/CentOS 5,6,7 you need to enable the EPEL repo, see: https://fedoraproject.org/wiki/EPEL and then # yum install carbon-c-relay

**Comment by ravibhooshan** [comment]
Thanks.
