### ISSUE TITLE
How to establish how many data-points are being ingested per second?

### ISSUE THREAD

**Issue by francesco-russo** [grobian/carbon-c-relay#110]
Hi there,
more than an issue this is really just a simple question, which I hope can result in a simple answer too :)

We need to monitor the number of individual data-points (I presume you refer to these as metrics) that are sent on a per-second basis to our CC-relay instance(s).

Looking at the code base it seems to me a good candidate might be this (https://github.com/grobian/carbon-c-relay/blob/184c2cafe3ac985869fe4ab9c38f558480598fec/dispatcher.c#L360), which if I am right then results in the "ccRelay.metricsReceived" metric that I can monitor via Graphite i.e.

Can you please confirm or deny my assumption?
What is the default time granularity for "ccRelay.metricsReceived", 60"?
Applying the "scaleToSeconds" function on the "derivative" of that metric should give me the 1" resolution, right?

Thanks in advance for the feedback,
Francesco

**Comment by grobian** [comment]
Completely right!  Default interval is 60 seconds, you can reduce it to 1 (never tested on my end) if you want.  metricsReceived is indeed more like "dataPointsReceived", but you need a (nonNegative)Derivative for it to make sense in a human way.

I hope this answers your questions sufficiently.
Thanks!

**Comment by francesco-russo** [comment]
Perfect, thanks for your prompt feedback! :+1:
