### ISSUE TITLE
Dropped metrics when downstream goes down

### ISSUE THREAD

**Issue by dforste** [grobian/carbon-c-relay#112]
I am trying to test out the latest release of carbon-c-relay and have a stack with go-carbon and multiple relays. I use this to build my relays https://github.com/dforste/carbon-c-relay-docker. Currently a git checkout of tag v0.44. 

Currently it looks like this: 
carbon-c-relay (currently just forward but will eventually be a consistent hash cluster. )
carbon-c-relay (routes to storage or aggregations)
||   carbon-c-relay (aggregations)
go-carbon (persists to disk)

It all seems to be working great but when I for instance take down the routing carbon-c-relay metrics seem to drop and do not buffer. The config in my top relay looks like this:
```
cluster main
  forward
  172.27.1.1:12003
  ;
match *
  send to main
  stop
  ;
```
Even on a pretty low load (~10,000 Metrics per minute) these seem to drop if the relay is down for any period of time.

**Comment by grobian** [comment]
What server queue size do you use?  Default is 25K, so roughtly 2.5m until it is filled up in your scenario in the best case.  I assume you determine the drops from the metricsDropped metric from the relay itself, but since you have one target, how would you read it?

**Comment by dforste** [comment]
Sorry I was wrong The attached capture shows that magnitude does in fact matter. I am using the default queue size. Metrics from the upstream relay do in fact get buffered if there is a short outage (180s) under light load of 10k Metrics per minute. If you do a 10x to it though metrics are missing from the upstream relay showing metrics have been dropped. 

![capture](https://cloud.githubusercontent.com/assets/5168898/10550937/141651b8-7407-11e5-8eff-7f4827b62698.JPG)

This same relay will happily do 1Million metrics per minute as shown here: 
![capture](https://cloud.githubusercontent.com/assets/5168898/10551192/c81b94f6-7408-11e5-9e25-8f78b1d55b0f.JPG)

Judging by the wall time this relay should be able to do 10x that even but I have other downstream that are not as efficient. 3 minutes at 100k is much less than your 2.5Million you estimated. The ability to handle the queued up 300k should be trivial when you can process 1Million per minute. I did notice there is a small amount(<10k) of queuing in the relay as well when running 1million metrics per minute into it.

**Comment by grobian** [comment]
I estimated 2.5 minutes, which is close to your 180 seconds (3 minutes).

So I think we misunderstand each other here.  You want the relay to queue up to 300K of metrics, yet the queue size of the relay is limited to 25K of metrics.  If your application needs a bigger queue, just increase the queue size.  Run carbon-c-relay with -q 500000 for example to get a 500K queue size limit (per server).

Note that the queue will be used a lot when downstreams are not as fast as the upstreams are.  In certain scenarios, we see downstreams that choke or have huge overhead on small/single submissions of metrics, so the queue fills up, then larger batches (see batch-size setting of the relay) are attempted which allows the queue to empty itself to a level where it matches the upstream speed on the grand totals.  It does mean it needs to be able to store bursts like that.  The 25K default is based on our setup, where we only have bare-metal machines, more or less dedicated to the job, so queues are usually at a few thousands of metrics while the upstreams produce between 1 to 3 million of metrics per minute.

**Comment by grobian** [comment]
There is not much I can do here.
