### ISSUE TITLE
Allow custom prefix for internal metrics

### ISSUE THREAD

**Issue by hpresnall** [grobian/carbon-c-relay#113]
Currently the internal metrics are hardcoded to be written to `carbon.relays.<hostname>`. I'd like to have the ability to specify this manually, like the `CARBON_METRIC_PREFIX` setting in carbon-relay.

Ideally you would set this in the config file, but a command line switch would be acceptable.

**Comment by grobian** [comment]
you can use a rewrite rule like this to do this:
```
rewrite carbon.relays.([^.])
    into whatever.you.want.\1;
```
Would this be sufficient for you?

**Comment by hpresnall** [comment]
Yes, that works perfectly. Wasn't thinking about rewrite rules.

For anyone else trying this, just make sure you put the rewrite before any matches.
