### ISSUE TITLE
freebsd compile fix

### ISSUE THREAD

**Issue by chipitsine** [grobian/carbon-c-relay#119]
# gmake
cc -fopenmp -O2 -Wall -DGIT_VERSION=\"bca1be\" -pthread   -c -o relay.o relay.c
cc: warning: argument unused during compilation: '-fopenmp'
cc -fopenmp -O2 -Wall -DGIT_VERSION=\"bca1be\" -pthread   -c -o md5.o md5.c
cc: warning: argument unused during compilation: '-fopenmp'
cc -fopenmp -O2 -Wall -DGIT_VERSION=\"bca1be\" -pthread   -c -o consistent-hash.o consistent-hash.c
cc: warning: argument unused during compilation: '-fopenmp'
cc -fopenmp -O2 -Wall -DGIT_VERSION=\"bca1be\" -pthread   -c -o receptor.o receptor.c
cc: warning: argument unused during compilation: '-fopenmp'
cc -fopenmp -O2 -Wall -DGIT_VERSION=\"bca1be\" -pthread   -c -o dispatcher.o dispatcher.c
cc: warning: argument unused during compilation: '-fopenmp'
dispatcher.c:172:22: error: variable has incomplete type 'struct sockaddr_in6'
        struct sockaddr_in6 saddr;
                            ^
dispatcher.c:172:9: note: forward declaration of 'struct sockaddr_in6'
        struct sockaddr_in6 saddr;
               ^
1 error generated.
gmake: *** [dispatcher.o] Error 1

**Comment by grobian** [comment]
added necessary include
