### ISSUE TITLE
document self statistics

### ISSUE THREAD

**Issue by ravibhooshan** [grobian/carbon-c-relay#122]
Hi,
I am facing issue where when we start carbon-c-relay service with either -d or -s switch, it stops sending its own metric  (like - metric received, metric dropped etc.) Is this normal behavior or I am missing something.
Second question I am using blackhole  cluster also. Is there any way to measure how much metric is being sent to blackhole cluster.
Also wanted to check do we have any documentation which explains all carbon-c-relay metric.

Thanks,
Ravi Bhushan

**Comment by grobian** [comment]
-d prints its own metrics to the stdout
-s doesn't write any metrics

from help:
    "  -d  debug mode: currently writes statistics to log, prints hash\n"
    "      ring contents and matching position in test mode (-t)\n");
    "  -s  submission mode: don't add any metrics to the stream like\n"
    "      statistics, report drop counts and queue pressure to log\n");

See the metricsBlackholed metric to get an idea how much goes by without sending it elsewhere.

It's a good idea to add an explanation of the self metrics to the README.  I'll do that later.

**Comment by ravibhooshan** [comment]
Thanks for your reply and explanation.
So if I understand correctly, Carbon-c-relay internal metric will be either logged into log or will be sent to Graphite.

**Comment by grobian** [comment]
metricsBlackholed is in there since v0.45

**Comment by ravibhooshan** [comment]
Thanks. I am using 0.44, I will upgrade to 0.45.

**Comment by ravibhooshan** [comment]
Thanks for updating documentation.
