### ISSUE TITLE
Carbon-c-relay to Skyline Horizon

### ISSUE THREAD

**Issue by mehmood-007** [grobian/carbon-c-relay#124]
i've to send metric from carbon-c-relay to Skyline Horizon, and skyline Horizon just receive Pickle and Messagepack-encoded UDP packets

I've tried both UDP & TCP in carbon-c-relay but not receiving data.

Skyline Horizon Conf
"""
Horizon settings
"""

//// The IP address for Horizon to listen on.  Defaults to gethostname()
HORIZON_IP = '0.0.0.0'

/// This is the port that listens for Graphite pickles over TCP, sent by Graphite's
/// carbon-relay agent.
PICKLE_PORT = 2024

/// This is the port that listens for Messagepack-encoded UDP packets.
UDP_PORT = 2025

Your Help is required.

**Comment by grobian** [comment]
carbon-c-relay supports neither pickles, nor messagepack.  Your only option is to add a listener to skyline if you need it, or run a traditional carbon-relay.py instance just before skyline in order to transform the line-mode metrics into pickle metrics.
