### ISSUE TITLE
High CPU load when using many workers

### ISSUE THREAD

**Issue by chbuescher** [grobian/carbon-c-relay#126]
Hi @grobian,

we are using carbon-c-relay as a simple load balancer for 2 sites a 3 carbon caches. We have quite 2 number of clients sending metrics, and lsof shows about 2500 open connections. We first ran out of file handles - which flooded our log files - and after fixing that i increased the number of worker threads from 4 to 16. This resulted in an increase of CPU usage in top from 50% to 150-200%.
Profiling with valgrind / callgrind did not help much, must cpu time was used in dispatcher_runner and dispatch_connection in both cases.
My clients are sending new metrics every 15 seconds, so most of the time the work variable in dispatch_runner is non-zero and the workers seldom sleep. They keep polling connections, which leads to the high load observed.
I'm testing a "fix", where each thread handles only part of the connections by starting the connections index with self->id -1 and increasing by workercnt. This reduces the CPU usage to about 16% for 16 worker threads. But this could lead to problems, if a worker threads dies/hangs.

**Comment by grobian** [comment]
Are you sure the cpu usage is caused by the polling of connections?

If what you say is true, increasing threads makes cpu load go up, without changing the input load, then that is a serious problem.  I should be able to reproduce that and test it.

**Comment by chbuescher** [comment]
Based on the callgrind data i'm quite sure the connection polling is causing the high cpu load.
I had a better idea to limit connection polling by saving the timestamp of the last successful connection polling and not polling it again the next 100 ms. This should be more reliable and also reduced the CPU load to about 16%. See my pull request

**Comment by grobian** [comment]
wow, thanks!

**Comment by grobian** [comment]
I took a slightly different approach, see comment for explanation why.  I hope this works for your scenario.

**Comment by chbuescher** [comment]
In my patch, the timestamp in lastprocessed was only updated when the call to dispatch_connection returned 0. So the stall of 100 ms should only happen when the recent data was completely  processed. Anyway, your approach did not work for me. Sorry.
![carbon-c-relay](https://cloud.githubusercontent.com/assets/16101913/11719058/3f17b08c-9f59-11e5-85fa-1263d5834ed7.png)

**Comment by chbuescher** [comment]
One Moment, i think, i analyzed an old Version. Sorry.

**Comment by chbuescher** [comment]
The new Version is better than Version 1.1 (in the screenshots). Now i get the following values:
CPU User 3%, System 4%, Dispatch Walltime 90% ( scale(persecond(dispatch_walltime_us), 0.0001) )
But still much higher than those of my patch.

**Comment by grobian** [comment]
Hmmm, ok, I'll try and see if I can replicate this behaviour.  I couldn't in our environment.  The pre-post graphs in my setting are identical (we do 800K/min but the dispatchers are mostly idle).

**Comment by grobian** [comment]
I have a problem, for I cannot reproduce this at all. I make 3000 dormant connections to a relay, and it simply does nothing.  I believe you have an issue, but I'm clueless how to reproduce it.

**Comment by grobian** [comment]
So, you say 3% user CPU utilitation, that sounds pretty low to me.  Is your problem that you see much more time being spent by the dispatchers than the servers?

**Comment by chbuescher** [comment]
Currently i can reproduce the high load only in our production environment, but not with a graphite stresser tool (carbon-load-test.py from graphite modified for using many connections)
We are using jmxtrans as main data source.
The cpu numbers are pretty low because the server has 24 logical cores and the 3% is for all cores.

**Comment by grobian** [comment]
Ok, we use similar hardware.  So the problem still persists.  We use 24 workers.

**Comment by chbuescher** [comment]
The load on the production server is too high to analyze it with valgrind. So i tried the poor man's profiler with your fix. Only one to three threads are read() ing in dispatch_connection, the rest is sleeping. No sign of excessive polling. And a strace over 8 seconds shows 720k read() calls, and half of them get a EAGAIN. This seems reasonable: A thread try to read further data from a connecion, and if it gets nothing, the connection isn't polled for some time. My issue - the increase in CPU utilization when increasing the thread number - seems to be solved. And i see your point with very busy connections like simple forwarders.

But one of your recent commits "server: free up correctly" has a new problem.
When stopping the relay, i get a core dump from a double free, or in valgrind:

==25659== Invalid read of size 8
==25659==    at 0x412E29: server_shutdown (server.c:593)
==25659==    by 0x405AEE: ch_free (consistent-hash.c:480)
==25659==    by 0x40F331: router_free (router.c:2015)
==25659==    by 0x403879: main (relay.c:582)
==25659==  Address 0x4c8ee30 is 80 bytes inside a block of size 176 free'd
==25659==    at 0x4A06430: free (vg_replace_malloc.c:446)
==25659==    by 0x405B02: ch_free (consistent-hash.c:481)
==25659==    by 0x40F331: router_free (router.c:2015)
==25659==    by 0x403879: main (relay.c:582)
==25659==
==25659== Invalid free() / delete / delete[] / realloc()
==25659==    at 0x4A06430: free (vg_replace_malloc.c:446)
==25659==    by 0x405B02: ch_free (consistent-hash.c:481)
==25659==    by 0x40F331: router_free (router.c:2015)
==25659==    by 0x403879: main (relay.c:582)
==25659==  Address 0x4c8ede0 is 0 bytes inside a block of size 176 free'd
==25659==    at 0x4A06430: free (vg_replace_malloc.c:446)
==25659==    by 0x405B02: ch_free (consistent-hash.c:481)
==25659==    by 0x40F331: router_free (router.c:2015)
==25659==    by 0x403879: main (relay.c:582)
==25659==

**Comment by grobian** [comment]
Yeah, thanks, that's issue #131, I'll fix that ASAP, that is, when I have a spare cycle.  Hopefully tomorrow.

**Comment by grobian** [comment]
ok, with the crash solved and your remark that it "seems to be solved", I'm closing this
