### ISSUE TITLE
carbon-c-relay1.1 error 

### ISSUE THREAD

**Issue by ravibhooshan** [grobian/carbon-c-relay#128]
Hi - I am installing carbon-c-relay1.1 and getting below error:
invalid cluster 'cluster_a': replication count (1) is larger than the number of servers (1)
[2015-12-03 14:07:05] (ERR) failed to read configuration '/etc/carbon-c-relay.conf'

My cluster configuration as below and it is working fine in carbon-c-relay0.44 & 0.45.
cluster cluster_a
     carbon_ch
        127.0.0.1:2023=a
;

cluster cluster_b
     carbon_ch
        127.0.0.1:2033=b

;
cluster cluster_c
     carbon_ch
        127.0.0.1:2043=c
;
cluster cluster_d
     carbon_ch
        127.0.0.1:2053=d
;
cluster cluster_e
     carbon_ch
        127.0.0.1:2063=e
;
cluster cluster_f
     carbon_ch
        127.0.0.1:2073=f
;

**Comment by grobian** [comment]
Thanks, I've fixed this already in current master.  The best workaround sofar is for these kind of clusters to replace them with forward clusters.  I hope to release 1.2 soon.

**Comment by ravibhooshan** [comment]
Thanks Grobian.
I will wait for next release and will continue using 0.45.
