### ISSUE TITLE
Negative regex not supported?

### ISSUE THREAD

**Issue by AlexAkulov** [grobian/carbon-c-relay#129]
I try use 
```
match ^DevOps\.mongodb\.host-mongo[0-9]\.mongo\.locks\.(?!\_global\_)
    send to blackhole
    stop
  ;
```
and get "Invalid preceding regular expression"

**Comment by grobian** [comment]
This has to do with the regex implementation carbon-c-relay uses from the libc.  I guess for something like this we would have to link against a library like pcre.

**Comment by grobian** [comment]
by the way in this example you could easily match and blackhole, e.g.
```
match ^DevOps\.mongodb\.host-mongo[0-9]\.mongo\.locks\._global_
    send to your-cluster
    stop
  ;
match ^DevOps\.mongodb\.host-mongo[0-9]\.mongo\.locks\.
   send to blackhole
   stop
;
```

I'm not going to implement this now, as it requires an external library to be used.
