### ISSUE TITLE
kill -HUP crash carbon-c-relay 1.3 with a glibc double free

### ISSUE THREAD

**Issue by sbarrier** [grobian/carbon-c-relay#132]
In /etc/logrotate.d/carbon-c-relay the postrotate do a kill -HUP to rehash daemon after the log rotation
`[ ! -f /var/run/carbon-c-relay/carbon-c-relay.pid ] || /bin/kill -HUP $(cat /var/run/carbon-c-relay/carbon-c-relay.pid)`

This crash carbon-c-relay with a double free:

[2015-12-21 00:48:25] (MSG) caught SIGHUP...
[2015-12-21 00:48:25] (MSG) closing logfile
[2015-12-21 00:48:25] (MSG) reopening logfile
[2015-12-21 00:48:25] (MSG) reloading config from '/etc/carbon-c-relay.conf'...
[2015-12-21 00:48:25] (MSG) reloading worker 2 3 4 5 6 7 8 9
[2015-12-21 00:48:26] (MSG) reloading collector
*** glibc detected *** /usr/bin/carbon-c-relay: double free or corruption (!prev): 0x0000000001e4ebd0 ***

Distribution Centos 6.x 64 bits, configuration used :

**/etc/carbon-c-relay.conf**
cluster graphite
  carbon_ch
    127.0.0.1:2013=a
    127.0.0.1:2023=b
    127.0.0.1:2033=c
    127.0.0.1:2043=d
  ;
match *
  send to graphite
  stop
  ;

**/etc/sysconfig/carbon-c-relay**
ARGS="-p 2003 -w 8 -i 192.168.0.100 -m -b 2500 -q 25000 -l /var/log/carbon-c-relay/carbon-c-relay.log"

After few hours of debug, this is a proposal patch for this issue :

```c
--- a/consistent-hash.c 2015-12-21 05:48:24.000000000 -0500
+++ b/consistent-hash.c 2015-12-21 05:54:58.000000000 -0500
@@ -478,9 +478,9 @@
 
        for (; ring->entries != NULL; ring->entries = ring->entries->next) {
                server_shutdown(ring->entries->server);
-               free(ring->entries->server);
-
+
                if (ring->entries->malloced) {
+                       free(ring->entries->server);   
                        if (deletes == NULL) {
                                w = deletes = ring->entries;
                        } else {
```

**Comment by piotr1212** [comment]
I can reproduce this (not after every sighup)

```
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: [2015-12-21 21:57:51] reloading worker*** Error in /usr/bin/carbon-c-relay: double free or corruption (fasttop): 0x00007f15a80370a0 ***
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: ======= Backtrace: =========
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(+0x77e35)[0x7f15c3eeee35]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(+0x8051a)[0x7f15c3ef751a]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(cfree+0x4c)[0x7f15c3efaccc]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /usr/bin/carbon-c-relay(+0x8df1)[0x55ea2827adf1]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /usr/bin/carbon-c-relay(+0x3a4d)[0x55ea28275a4d]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(+0x34b20)[0x7f15c3eabb20]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(__select+0x33)[0x7f15c3f6fd83]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /usr/bin/carbon-c-relay(+0x6346)[0x55ea28278346]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libpthread.so.0(+0x760a)[0x7f15c423f60a]
Dec 21 21:57:52 pontifex.localdomain carbon-c-relay[1800]: /lib64/libc.so.6(clone+0x6d)[0x7f15c3f79a9d]
```

**Comment by grobian** [comment]
hey, thanks, that looks correct to me

**Comment by grobian** [comment]
I think this is the same problem as the last comment in issue #131

**Comment by grobian** [comment]
the patch isn't right, because it simply leaks the other servers

The valgrind trace in #126 shows that the server that is shut down is actually garbage, so the problem lies elsewhere.

**Comment by grobian** [comment]
This was a stupidity, your fix was in the right direction, but shutting down the servers needed the same treatment.  Feedback on whether it solves the issue for you would be much appreciated.  Thanks!

**Comment by grobian** [comment]
By the way, I didn't catch this because the jump_fnv1a_ch hash doesn't replicate each server 100 time to place them on a ring, therefore the top loop was actually only dealing with "malloced" entries.

**Comment by sbarrier** [comment]
I confirm it fixed our issue as it was easily reproducible with a kill -HUP and that's why i included the proposal patch :)

**Comment by grobian** [comment]
Ah, thanks!  I'm going to run valgrind through all of the issues and possibly some more scenarios I can find, then if that's all ok, will release v1.4.
