### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by bzed** [grobian/carbon-c-relay#137]
Hi,

in Debian we are able to run automated tests on built binary packages - so it would be great if you could provide something to test carbon-c-relay after it was built on our buildds. We have some weird architectures with weird "features" - so some extra testing wouldn't be bad.

thanks,

Bernd

**Comment by grobian** [comment]
I haven't had bright ideas yet on how to test the software, except from ripping it apart and trying unit-tests, but that would mean a major investment which I can't make right now.

**Comment by grobian** [comment]
I've made a start with this in master.  It isn't as extensive as one would hope, but it's something.

**Comment by grobian** [comment]
there are tests, and they nowadays run per commit via github's actions
