### ISSUE TITLE
carbon-c-relay statistics

### ISSUE THREAD

**Issue by ravibhooshan** [grobian/carbon-c-relay#138]
Hi - Can we send send carbon-c-relay internal metric to Graphite along with -d & -s switch.

**Comment by grobian** [comment]
-s is the flag meant for /not/ doing that, -d is debugging, so why exactly would you want that?

**Comment by szibis** [comment]
As far i know there is now option to use -d and -s in same time. @grobian maybe i would be good to have stats in logs and in graphite ?

**Comment by grobian** [comment]
... aren't the stats by default in graphite?  logs make no sense to me.

**Comment by grobian** [comment]
different question: what do you think -s does?

**Comment by ravibhooshan** [comment]
I tried without -s also but still its sending data only to logs.

When I remove both -d & -s it starts sending data to Graphite but not to log.
This is what I understand -s says it writes error to log so it shoudl sned to Graphite if I remove -s, but this not working.

**Comment by grobian** [comment]
-d means debug, that mode should never be used unless you try to figure out what the **** the relay is doing.
So, the only option left for you is -s.  This option does suppress sending the relay's statistics.

**Comment by grobian** [comment]
here is what help says:
```
  -d  debug mode: currently writes statistics to log, prints hash
      ring contents and matching position in test mode (-t)
  -s  submission mode: don't add any metrics to the stream like
      statistics, report drop counts and queue pressure to log
```

**Comment by ravibhooshan** [comment]
ok so if i use only -d then carbon-c-relay should log events into log and also send metrics to Graphite,

**Comment by grobian** [comment]
no, because it writes statistics to log.

What are you trying to achieve?

**Comment by ravibhooshan** [comment]
I want to log events into log file along with statistics into graphite.

**Comment by grobian** [comment]
then I suggest you create a file cluster and route the carbon.* traffic to that cluster also.

**Comment by ravibhooshan** [comment]
can you please tell me little details of this solution.

**Comment by grobian** [comment]
```
cluster stats-to-log
    file
        /path/to/my/file.log
   ;
match ^carbon\.
    send to stats-to-log
    ;
```

**Comment by grobian** [comment]
Even something like this might do what you want:
```
cluster stats-to-log
    file
        /dev/stdout
    ;

match ^carbon\.
    send to stats-to-log
    ;
```

**Comment by ravibhooshan** [comment]
Thanks very much it worked.
