### ISSUE TITLE
[Feature Request] add a input data syntax check filter.

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#142]
Could be interesting if c-relay could add a syntax filter avoiding sending malformed data:

"metric-name value timestamp"

to the graphite backend.

A logfile with this errors and the IP origin will be wellcomed also.

Thank you very much.

**Comment by grobian** [comment]
I think this request is similar to PR #78 right?

**Comment by toni-moreno** [comment]
Hi @grobian . This issue is similar but not exactly the same.

in https://github.com/grobian/carbon-c-relay/pull/87  , you will log "unwanted" this is metrics that you don't have any "match" rule.

In this issue  what I need is a syntax check for valid metrics.

These metrics are valid metrics to graphite in "PlainText Format"

```
system.cpu.wait  80 1454056517
system.disk.io  25.0 1454056517

```

and these other are invalid to graphite

```
system.cpu.wait  OK 1454056517              #bad value
system.cpu.wait  OK 12343                   #bad timestamp
system.cpu.wait  25 OK                      #bad timestamp
system   cpu  wait  25.0 1454056517         #bad number of parameters
```

Right now carbon-c-relay is relaying invalid metrics if a correct match rule found. I need to stop these invalid metrics before to reach the graphite backend.

**Comment by piotr1212** [comment]
I'm not sure if I understand, that is exactly what is requested in https://github.com/grobian/carbon-c-relay/pull/87
And partially implemented in https://github.com/piotr1212/carbon-c-relay/commits/filter2
@grobian made some changes since than and suggested to use a regex which is a much better idea than the ugly parsing I did...

**Comment by grobian** [comment]
@toni-moreno do you mean #78 (iso #87)?  It's all a bit confusing right now :)

**Comment by toni-moreno** [comment]
Hi @grobian what @piotr1212 have been done at https://github.com/grobian/carbon-c-relay/pull/87  is exactly what we need.

Thank you !!!

**Comment by grobian** [comment]
I've introduced a `validate` clause to match rules
