### ISSUE TITLE
GCC doesn't define ENABLE_OPENMP

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#145]
From change here. https://github.com/grobian/carbon-c-relay/commit/b4db03b11690f97cd9185b757c0cc03df4e200a8

I could raise a PR which adds ``|| defined(_OPENMP)``. Though I'm not sure of the rationale for changing guards.

**Comment by iain-buclaw-sociomantic** [comment]
This is not a real concern for me, as I set the number of workers explicitly.

**Comment by grobian** [comment]
what version of gcc do you have this problem with?

indeed, openmp is only used to get the number of cores on your system

**Comment by iain-buclaw-sociomantic** [comment]
I believe our build server is using gcc-4.8.  However this affected by all versions of GCC.

**Comment by grobian** [comment]
Odd, because I tested this with 4.7.3 on Solaris and 4.9.3 on Linux, both worked without problems.

What is the error you get?

**Comment by grobian** [comment]
Oh, you just see it defaulting to 5.  Right, joy.

**Comment by grobian** [comment]
can you test if above commit works for you?

**Comment by iain-buclaw-sociomantic** [comment]
@grobian - Yes that would do the trick.

**Comment by iain-buclaw-sociomantic** [comment]
I see it's been committed, so I did a test rebuild.
```
$ ldd relay
	linux-vdso.so.1 =>  (0x00007fff7ec90000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7dd6e18000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f7dd6bf6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7dd69d8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7dd6613000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7dd640f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7dd711e000)
```

Yep, OMP is linked in again.
