### ISSUE TITLE
maximum throughput problem, investigate contentions

### ISSUE THREAD

**Issue by grobian** [grobian/carbon-c-relay#148]
it seems relay goes stalling on bursts, in some cases even seriously stalling, need to find if locking contention is part of the problem why it can't switch fast enough here

**Comment by ethan-eb** [comment]
I've got steadily increasing stall rate I am worried about right now. Do you have any general advice on dealing with that? 

Metrics queued goes up and down, while  metrics received goes up and pulls stalls up too. No drops so far. We're at about 2.8M metricsReceived.

I am set up like this: https://dl.dropboxusercontent.com/u/98935037/graphite-arch.png so I realize I could balance the incoming traffic between the two graphite servers to relieve pressure (at least to the front relay). Any other ideas?

**Comment by grobian** [comment]
the problems we're seeing, which we're unsure where they come from yet, are a cap on how fast we can redistribute metrics.

Currently I've established (v1.8) the following:
- input rate of roughly 100K/s can be spooled through to another c-relay which writes to file, it fluctuates a bit
- input of 50K/s was causing problems on local carbon-c-relay due to stalls from upstream carbon-c-relay (fixed now)
- upstream carbon-c-relay seemed to just take 8K/s when configured with many clusters/matches, workers aren't busy though

**Comment by mhollick** [comment]
Hi,

Not a solution, but a small suggestion for your architecture.
I think that you should be able to do without the second layer of carbon-c-relays.
Something like:

cluster myself
  forward 127.0.0.1:2013
  ;

cluster partner
  forward www.xxx.yyy.zzz <http://www.xxx.yyy.zzz/>:2003
  ;

match *.processed
  send to myself
  stop
  ;

rewrite *
  into \1.processed
  ;

match *
  send to myself
               partner
  stop
  ;

Of course, you might not wish to use the string ‘processed’ at the end of all your metrics, but most metrics - especially statsd - need some kind of tidy up which you could use as an anchor.

Matthew Hollick
mhollick@gmail.com <mailto:mhollick@gmail.com>
07903 447 669

**Comment by grobian** [comment]
tomorrow I want to compare raw sending speed with something like nc to c-relay -> c-relay to see if it is significant

**Comment by ethan-eb** [comment]
thanks @grobian maybe I should try v1.8 ... currently v1.1

@mhollick that makes sense, simpler setup, thanks

**Comment by ebpitts** [comment]
Interesting idea @mhollick . We aren't doing any rewriting now though, so I'd be nervous about the performance/complexity impact of introducing that. It's certainly something we can test to see if it helps!

**Comment by grobian** [comment]
rewrites should be relatively cheap operations

**Comment by grobian** [comment]
problem identified to be a downstream server, not coping with the load
