### ISSUE TITLE
relay favoring 2 instances over others

### ISSUE THREAD

**Issue by wstiern** [grobian/carbon-c-relay#149]
Hi there. I'm working through some performance tuning issues with Graphite+CCRelay. Here's a link to the graphite-dev issue I started: https://answers.launchpad.net/graphite/+question/285063

And here's relevant content from my relay.conf:

`
root@lga-graphite01 ~ # cat /opt/graphite/bin/ccrelay.conf 
cluster lga
    carbon_ch
	0.0.0.0:2013=a
	0.0.0.0:2113=b
	0.0.0.0:2213=c
	0.0.0.0:2313=d
	0.0.0.0:2413=e
	0.0.0.0:2513=f
;

match *
	send to lga
;
`

The only remaining problem I'm having with this configuration is that carbon-c-relay seems to be favoring two instances of carbon-cache over the others, causing them to hit their MAX_CACHE_SIZE value.

Any assistance would be appreciated.

**Comment by wstiern** [comment]
Dashboard screenshot with Graphite/Carbon-C-Relay stats: https://imgur.com/YkcjRsJ

**Comment by piotr1212** [comment]
this is a known issue with the hashing algorithm, see https://github.com/graphite-project/carbon/issues/485 for details.

**Comment by wstiern** [comment]
So I should be using jump_fnv1a_ch instead of carbon_ch?

**Comment by piotr1212** [comment]
graphite-web only support carbon_ch.

Looking at your screenshot a bit better I noticed that there is a big difference between max and min metrics received per cache, see cache a which has a max 2M and min 500K, might there be some other issues?

**Comment by wstiern** [comment]
Thanks for your response. :)

The jaggy freakshow at the bottom of the Metrics Recieved graph shows what happens when instances A and F reach MAX_CACHE_SIZE.

**Comment by grobian** [comment]
If you use any_of (which is essentially fnv1a_ch, but without the _ch part, thus cheaper/more flexible) you should see close to fair/equal distribution over all caches.  You can verify that by drawing something like nonNegativeDerivative(carbon.relays.<your-relay>.destinations.*:2*13.sent).  If that shows misalignment for your current usage, you can improve it by using any_of.
I agree with piotr1212 and others though, that graphite-web doesn't quite grok any other hash algorithm, so if you rely on the cache, this will cause different issues.

Just for some background, we use SSDs in separate machines and let our relays fan out the metrics over those machines (say 5) and then use carbonzipper with carbonserver to retrieve them, that is, graphite-web thinks there is only one store.  This setup may or may not work for you, but it helped for us balancing the load.

**Comment by wstiern** [comment]
Thanks for your reply, grobian!

Can you go into further detail on why hashed balancing is preferred to just straight round-robin or other common balancing algorithms?

Is there any additional documentation available for the carbonserver/zipper/api/mem projects?

**Comment by wstiern** [comment]
Also as far as https://github.com/graphite-project/carbon/issues/485 is concerned, does it mean that if I  readjust my port numbering, the balancing issue should weaken a bit?

**Comment by grobian** [comment]
carbon-cache.py maintains a cache (duh) for the metrics it writes.  When you use round-robin, all of your caches will receive points for the same metric.  This results in contention: when one cache starts to write, it was written by another one, etc. If you use a hashing technique here, all points for the same metric will go to one and the same cache, thus avoiding this problem.  any_of is just less strict than a _ch hash, in that it will ignore unreachable targets, which is what you want in this case.  If you bring down a carbon-cache, or it crashes, you just want the remaining ones to be used.

**Comment by wstiern** [comment]
That makes sense. Thanks again for your input.

I've implemented carbonserver/carbonzipper/carbonapi and am (of course) quite happy with the performance on the front-end. The cache issue is the only pain point right now.

Should I try crunching the port number range? I have another server that I'll be adding to the mix later but it's for redundancy purposes (hosted at another DC) and will be hosting a copy of the data on this server.

Also, aliasByNode() function doesn't seem to be alphabetically sorting the series that are returned by the query -- is that by design?

**Comment by wstiern** [comment]
Also also, could I work around the imbalance with the hashring algorithm by enabling WHISPER_LOCK_WRITES in carbon.conf and any_of or some other function in carbon-c-relay?

**Comment by deniszh** [comment]
> Also, aliasByNode() function doesn't seem to be alphabetically sorting the series that are returned by the query -- is that by design?
Yoa can use sortByName() function for sorting.

**Comment by wstiern** [comment]
> You can use sortByName() function for sorting.

Yeah a quick scan of the Graphite functions list sorted that out, just wasn't sure if it was intentional.

**Comment by grobian** [comment]
not sure if there's anything I can do here

**Comment by wstiern** [comment]
I've tried reducing the port number range but it doesn't appear to have made much of a difference. Two instances are still favored over others. Sometimes A and F, right now D and F. It just seems that the hashing algorithm is imbalanced and that's what https://github.com/graphite-project/carbon/issues/485 was all about.

**Comment by grobian** [comment]
I'm affraid you're right, but I can't solve that here.  One needs more changes in the stack to account for a different hash distribution.

**Comment by wstiern** [comment]
What can I do to help contribute constructively to the expedited resolution of https://github.com/graphite-project/carbon/issues/485 ? My business users have come to rely heavily on Graphite and we could possibly even offer a bounty.

**Comment by wstiern** [comment]
Time will tell, but I appear to have worked around this issue by doing the following:

* Enabled WHISPER_LOCK_WRITES in carbon.conf.
* Reconfigured carbon-c-relay to use any_of distribution algorithm.
* Increased running carbon-cache instances from 6 to 16.

Between those two changes, cache sizes are way way down and metrics all arriving in a timely fashion. Nice equal distribution of volume between running instances.
