### ISSUE TITLE
relay not recognizing system max file descriptors

### ISSUE THREAD

**Issue by rrpolanco** [grobian/carbon-c-relay#151]
I'm running carbon-c-relay v1.8 on Ubuntu 14.04. 
I see the following message in the logs:
`[2016-02-25 21:40:17] process configured maximum connections = 4096, consider raising max open files/max descriptor limit
[2016-02-25 21:40:17] dispatch: failed to accept() new connection: Too many open files`

`ulimit -Hn` shows:
65535

`ulimit -Sn` shows:
65535

How do I resolve this message?

Thanks.

**Comment by rrpolanco** [comment]
No bug here. Limit settings are not applied to carbon-c-relay since it is launched by start-stop-daemon,which doesn't pass through PAM.

I worked around this by setting `ulimit` within my init.d script and things are back to normal.

**Comment by grobian** [comment]
Ok, good to know!  I guess with 1.8 this can be changed, since carbon-c-relay grew the option to create a pidfile and to daemonise itself.
