### ISSUE TITLE
Questions about queue

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#155]
>   -b  server send batch size, defaults to 2500
>   -q  server queue size, defaults to 25000

- How long are metrics stored in queue?
- What resource does queue use? memory, disk, other?
- "server send batch size". What exactly is this? pros/cons of increasing/decreasing?

In the event that one or all backend carbon server(s) go down... 
- I would like to have the largest queue possible 
- keep metrics in the queue for as long as possible

**Comment by grobian** [comment]
time is irrelevant here, it's just the number of metrics the relay can hold
queues use memory, therefore a limit is applied such that the process won't grow infinitely
the batch size is basically how many metrics at once are attempted to be sent, the effects of changing the value is minimal as far as I have observed

**Comment by druchoo** [comment]
Is there anyway to figure out memory requirements for a given queue size? Or can I just set a really high value and let the limit decide what to do?

**Comment by grobian** [comment]
well, in practice, the limit just means sizeof(ptr) * queuesize as default footprint, e.g. 8byte * 25000 = 195Kbyte.  However, those 25000 entries can be filled with metric strings.  Suppose your average metric is something like 100bytes (characters), then you store 100 * 25000 = 2.5Mbyte on memory per server.  However, this depends on the size of your metrics.

**Comment by druchoo** [comment]
I want to set "server queue size" to utilize as much memory as possible without starving or impacting system. How can I do that?

**Comment by grobian** [comment]
that's impossible with the current state of the code, you'll have to do the maths yourself and monitor it closely

**Comment by deniszh** [comment]
@druchoo, sorry for intervening, but IMO incoming queue was designed to remove metrics bursts and not as a persistent buffer in case of unavailable destinations. Carbon-c-relay usually using at such message rate that any reasonable amount of buffer will be consumed in seconds...
You can use `file` cluster for having a copy of all metrics on disk and then or use something like http://www.circlemud.org/jelson/software/emlog/ for a controllable circular buffer or create some script to clean up disk space periodically. But it looks like a very crappy solution...

**Comment by piotr1212** [comment]
You could also consider using a Kafka bus as a persistent queue/journal.
I've used it in combination with Heka and some custom producers/consumers.

**Comment by deniszh** [comment]
Kafka is nice, but you need some custom way to put metrics there - carbon-c-relay has no such functionality. Parsing file on disk... meh.

**Comment by piotr1212** [comment]
You can use Heka as a bridge from carbon-plaintex -> kafka ->
carbon-plaintex. The team had written their own producer/consumer (more for
fun than actually needed). Not sure what they are using now as I don't work
there anymore.

**Comment by druchoo** [comment]
Thanks all for the feedback/suggestions. @deniszh makes a good point and I'll leave it at that and close this out.

> incoming queue was designed to remove metrics bursts and not as a persistent buffer in case of unavailable destinations.

Thanks again to all for the prompt responses.
