### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#158]
Hi Grobian,

Could you please keep a changelog so its easy to check whats different between releases?

I was trying to find the release in which 'match * send to ...' started to support multiple clusters, but I could not find it.

I am sure you know what a changelog is, but here is an example: https://github.com/grafana/grafana/blob/master/CHANGELOG.md

Much appreciated!

**Comment by grobian** [comment]
Right, that's a good suggestion.  I kept some of it in our local specfile, so maybe I can put something together easily.

**Comment by rtoma** [comment]
Thanks :+1:
