### ISSUE TITLE
carbon.relay.* metrics get corrupted if a file cluster has a too long path (yes really)

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#159]
With v1.10 (and v1.8):

Use this config:
```
cluster upstream forward 127.0.0.1:12003;
cluster blacklisted file /tmp/1234567890123456789012.log;
match * send to upstream;
```

Please observe the unused file cluster and a silly long name. Note the length of the path.

Start with `./relay -f ./bla.conf -p 2003 -S 5 -H HOST`. Check the metrics send to the upstream cluster and find these:
```
...
carbon.relays.HOST.metricsSent 1 1458056827
carbon.relays.HOST.metricsQueued 0 1458056827
...
```

Now add a character to the file cluster path name:
```
cluster upstream forward 127.0.0.1:12003;
cluster blacklisted file /tmp/12345678901234567890123.log;
match * send to upstream;
```
The file cluster is still unused.

Start the relay with the same parameters. Check the metrics stream and now you'll find these:
```
...
carbon_relays_HOST_metricsSent 187 1458056783
carbon_relays_HOST_metricsQueued 0 1458056783
...
```

See the dots are translated into underscores? That's the issue.

Bonus: the metrics stream now also contains monsters like these:
```
carbon_relays_HOST_destinations._tmp_12345678901234567890123_logcarbon_relays_HOST_\
  destinations._tmp_12345678901234567890123_logcarbon_relays_HOST_destinations._tmp\
  _12345678901234567890123_logcarbon_relays_HOST_destinations._tmp_12345678901234\
  567890123_logcarbon_relays_HOST_destinations._tmp_12345678901234567890123_logcarb\
  on_relays_HOST_destinations._tmp_12345678901234567890123_logcarbon_relays_HOST\
  _destinations._tmp_12345678901234567890123_logcarbon_relays_HOST_destinations.wall\
  Time_us 22 1458056783
```

Smells like a bufferoverflow or one-off?

**Comment by grobian** [comment]
errr yeah this is stupid.

**Comment by rtoma** [comment]
Thanks for the quick fix!

```
...
carbon.relays.HOST.destinations._tmp_12345678901234567890123xxxxxxxxxxxxxxxxxxxxxxxxxxxx_log.wallTime_us 8 1458068838
carbon.relays.HOST.metricsSent 32 1458068838
carbon.relays.HOST.metricsQueued 0 1458068838
...
```

**Comment by grobian** [comment]
Just to be sure, those xxxxx things are what you expect to see right?  Given your config the xxxxx-es shouldn't be there...

**Comment by rtoma** [comment]
Yeah those x's are as expected. Its my quick & dirty attempt to create a looooooong path.
