### ISSUE TITLE
metricsBlackholed stays zero when blackhole is used

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#160]
Consider this configuration:
```
cluster upstream forward bla:2003;

cluster redologs file /srv/carbon_redologs/active.log;

cluster blacklisted file /srv/carbon_blacklist/drop.log;

match ^statsd\.(tst|acc|pro)\. send to upstream redologs stop;
match ^applications\.(tst|acc|pro)\. send to upstream redologs stop;
match ^carbon\.relays\. send to upstream redologs stop;

match * send to blacklisted blackhole;
```

One would except the metric `carbon.relays.HOST.metricsBlackholed` to increase if metrics are send to cluster `blacklisted`, but it does not.

Probably because the `blackhole` target disappears when a real cluster is specified, but I wonder what makes more sense.

**Comment by grobian** [comment]
hah!
what you do is as follows:

```
match *
   send to blacklisted
   ;
match *
   send to blackhole
   stop;
```

So the metric is sent to a non-blackhole cluster (blacklisted) and therefore not counted as blackholed.

You could argue that because you explicitly send it to blackhole, it should be counted.

Apart from that semantical discussion, I guess you want a counter of what's in your file with blackholed crap, right?

**Comment by grobian** [comment]
I think this should do it:
```
diff --git a/router.c b/router.c
index 1e5eec7..6eb2f65 100644
--- a/router.c
+++ b/router.c
@@ -2301,6 +2301,7 @@ router_route_intern(
                        for (d = w->dests; d != NULL; d = d->next) {
                                switch (d->cl->type) {
                                        case BLACKHOLE:
+                                               *blackholed = 1;
                                                break;
                                        case FILELOGIP: {
                                                servers *s;
```

**Comment by grobian** [comment]
no it doesn't.

**Comment by rtoma** [comment]
Ah of course!

> Give me a hammer and I'll use it on anything.

I was so happy with multi cluster support in matches, that I used it everywhere including the blacklisted + blackhole. Its just fine to use 2 matches.

Thanks for the patch!
