### ISSUE TITLE
Error Msg: 'failed to write() to <host>: uncomplete write'

### ISSUE THREAD

**Issue by rrpolanco** [grobian/carbon-c-relay#161]
Hello,

I'm running carbon-c-relay 1.8 on Ubuntu Trusty and getting the following errors when carbon-c-relay is running: 
```
[2016-03-18 18:32:30] failed to write() to 10.146.19.56:2003: uncomplete write
[2016-03-18 18:32:30] server 10.146.19.56:2003: OK
```

My carbon-c-relay.conf is as follows:
```
cluster local_carbon
  any_of
    127.0.0.1:2013
    127.0.0.1:2113
    127.0.0.1:2213
    127.0.0.1:2313
    127.0.0.1:2413
    127.0.0.1:2513
    127.0.0.1:2613
    127.0.0.1:2713
  ;

cluster remote_carbon
  any_of
    10.146.19.56:2003
  ;

match ^collectd.* send to remote_carbon;
match * send to local_carbon stop;
```
The relay is supposed to only write non-collectd metrics locally and send collectd data to another node to be processed. However, since it can't seem to write to the remote node, the collectd metrics are being written to the local node.

What is the root cause for the uncomplete write message? Any guidance/help is much appreciated.

**Comment by rrpolanco** [comment]
Just realized that my match expression for collectd is incorrect. It should be `^collectd\.` and should also end with `stop`. This seemed to have fixed the issue as to why collectd metrics weren't being routed correctly. I'm now seeing less _uncomplete write_ messages but still curious as to what could be the cause.

**Comment by grobian** [comment]
The uncomplete write happens when the relay wasn't able to send a full metric at a time at once to the server.  This may be somewhat clumpsy to bail on it, since it is not an error or weird condition.

**Comment by grobian** [comment]
although, on a second thought, the socket is in blocking mode...

**Comment by rrpolanco** [comment]
Would it be possible for the relay to re-send the remaining bytes for the metric after an uncomplete write?

**Comment by grobian** [comment]
I need to check this in the docs, but since I'm using blocking sockets, I expect an incomplete write to be followed by a failure, so re-send won't work, therefore I disconnect and reconnect to try the full metric again, else the metric would get lost.

**Comment by rrpolanco** [comment]
I see. Good to know that you retry and bail if you can't. I'll continue to monitor these messages and hope this was something transient on my end.

**Comment by Civil** [comment]
In my case, the same problem was caused by the following situation:
For some reason one of carbon-caches dies and carbon-caches were listening to ports above 32768, which by default is in net.ipv4.ip_local_port_range.
So in my case, carbon-c-relay from time to time connects back to itself (src port assigned by OS was the same as dst port of dead carbon-cache) and that cause a trouble.

But maybe you have a different situation.

**Comment by rrpolanco** [comment]
Thanks @Civil. All the ports I have assigned to the caches are well below 32768. Not sure what the cause was but I'm chalking it up to a coincidental transient issue in the system.
