### ISSUE TITLE
[Feature Request] Split relay.conf into multiple conf files

### ISSUE THREAD

**Issue by liyichao** [grobian/carbon-c-relay#165]
When there are lots of rules, users want to organize conf files with directories and files, it is good if relay can support this. For example, support this syntax:

```
include conf1.conf
include conf2.conf
include conf/*.conf
```

**Comment by grobian** [comment]
I assume you want to see the expanded in total, such that conf2 can use clusters defined in conf1 or something.

**Comment by grobian** [comment]
I didn't implement the glob.  Wouldn't be impossible, but I'd like to know if there's a real usecase for that first.

**Comment by grobian** [comment]
glob was implemented as part of #174
