### ISSUE TITLE
Statistic send is broken in current master

### ISSUE THREAD

**Issue by Civil** [grobian/carbon-c-relay#166]
Fails with the following error:
```
[2016-04-15 13:21:52] failed to write() to internal:2003: Socket operation on non-socket
```

**Comment by Civil** [comment]
Sorry, was not a clean build, after 'make clean' - works.

**Comment by grobian** [comment]
current master may not be suitable to use at the moment

**Comment by Civil** [comment]
Well, I'm trying to create a patch for #154, just using a master as a base (it's good enough for testing on a single box). After I'll get something working, I'll anyway rebase it against v1.11 for my needs.
