### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by nitr0dv** [grobian/carbon-c-relay#167]
Hello!

I'm testing carbon-c-relay now and can't see any logs except logs of process start. I tried different command like args - -d, -m, -s - but...
I need them - logs - to find a problem in my aggregation - I'm pushing 2.5k metrics and have some multiple (two steps) aggregation. And often I see that the aggregated graph has only a partial sum of metrics.
Here is my carbon-c-relay.conf -
```
cluster some_cluster # 4 local carbon-caches
  fnv1a_ch
    127.0.0.1:2103=a
    127.0.0.2:2105=b
    127.0.0.3:2107=c
    127.0.0.4:2109=d
  ;

cluster logging
  file
    /var/log/carbon-c-relay/log
  ;

rewrite ^(some_pattern_[a-zA-Z0-9]+_meta_.+)\.stat\.counter\.(.+)
  into \1.stat.\2
  ;

aggregate ^(some_pattern_[a-zA-Z0-9]+_meta_.+)\.stat\.(.+)\.hosts\..+\.clients_count
  every 60 seconds
  expire after 90 seconds
  compute sum write to # that's OK
    \1.stat.\2.hosts_total_clients_count
  compute sum write to # problem here - partial sum
    some_pattern_meta_aggregated.stat.\2.hosts_total_clients_count
  send to
    some_cluster
  ;

match ^(some_pattern_[a-zA-Z0-9]+_meta_.+)\.stat\.(.+)\.hosts\..+
  send to
    some_cluster
    stop
  ;

aggregate ^(some_pattern_[a-zA-Z0-9]+_meta_.+)\.stat\.(.+)
  every 60 seconds
  expire after 90 seconds
  compute sum write to
    some_pattern_meta_aggregated.stat.\2
  send to
    some_cluster
  ;

match ^some_pattern_
  send to
    kldfs
    stop
  ;
```

P.S.: I have CentOS 7 and carbon-c-relay v1.10

**Comment by nitr0dv** [comment]
Problem with a partial sum was fixed. It was because of 'per metric' write into the carbon-c-relay, not in a batch mode.
But problem with a logging still present.

**Comment by grobian** [comment]
The logging you want doesn't exist.  Most information can be retrieved from the internal statistics of the relay.  You'd be interested in the received, sent and drops for the aggregator I presume.

**Comment by nitr0dv** [comment]
Hello!
Yes and no. Yes - I'm interested in recieved, sent and dropped count, bu no - also I need some debug to see what metrics/values ware aggregated to see what is wrong. Ex.

[aggregation]
rule = ^some_pattern
func = sum
matches = [
  'matric1' => value1,
  ...
  'metricN' => valueN
]
result_metrics = [
  'res_metric1' => value1,
  ...
  'res_metricN' => valueN
]
And then I'll be able to see if all metrics ware aggregated or not. For now I've fixed my bugs (see the previous comment), but I think that such statistics will be helpful.

**Comment by grobian** [comment]
So, you'd like to see how much data went in and what it would become?  That's going to be potentially a lot of data!  Have you looked at the output of the -t (test) mode if you enter your metric?  Would that help you to understand if the rules are setup correctly or not?

**Comment by nitr0dv** [comment]
No I haven't see the -t output. Will see.
Thanks! I think that I can close this issue - there is no problem for now :)

**Comment by grobian** [comment]
awesome :)
