### ISSUE TITLE
systemd: carbon-c-relay.service doesn't starts properly

### ISSUE THREAD

**Issue by nitr0dv** [grobian/carbon-c-relay#170]
Hello again!

I've one more strange thing. When I'm using systemd to start the carbon-c-relay service (with the settings in the /etc/sysconfig/carbon-c-relay file, like -B, -b, -q) I have the starting log with default command line values, not these from /etc/sysconfig/carbon-c-relay.

And I have to start it from the command line and then I have all my values.

How can I make it starts properly?

P.S.: and I think that I have one more problem with the `not systemd` start - I have no statistics (starting w/o -s or -d). When I start carbon-c-relay w/ systemd I have all statistics.

OS: CentOS 7.1, carbon-c-relay: 1.10 (2016-03-15)

Thanks!

**Comment by Civil** [comment]
What service file you are using? For example we've got our custom service:
```
[Unit]
Description=Enhanced C implementation of Carbon relay, aggregator and rewriter, role: %i

[Service]
User=carbon
Type=simple
EnvironmentFile=/etc/sysconfig/carbon-%i
ExecStartPre=/bin/bash -c 'echo | /usr/bin/carbon-c-relay -f /etc/carbon-%i.conf $ARGS -t'
ExecStart=/usr/bin/carbon-c-relay -f /etc/carbon-%i.conf $ARGS
ExecReload=/bin/bash -c 'echo "Reloading carbon-c-relay, role %i, pid=$MAINPID"; echo | /usr/bin/carbon-c-relay -f /etc/carbon-%i.conf $ARGS -t && kill -HUP $MAINPID'
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by nitr0dv** [comment]
Hello!

I have the standard one -

```
[Unit]
Description=Enhanced C implementation of Carbon relay, aggregator and rewriter

[Service]
User=root
Type=simple
EnvironmentFile=-/etc/sysconfig/carbon-c-relay
ExecStart=/usr/bin/carbon-c-relay -f /etc/carbon-c-relay.conf ${ARGS}
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Will try your service file now.

**Comment by Civil** [comment]
Note that for your service to work you must have /etc/sysconfig/carbon-c-relay and you should have "ARGS" variable specified there.

**Comment by piotr1212** [comment]
Are you using the epel package?

**Comment by nitr0dv** [comment]
Yes, piotr1212, I have an EPEL package - v1.10.

Civil, can you tell what roles on carbon-c-relay do you have? I saw that you're using %i in your service file to start multiple instances of the carbon-c-relay.

**Comment by piotr1212** [comment]
@nitr0dv , I think I found the issue, actually I found two issues related to user/permissions.

in the  unit file user should be carbon-c-relay instead of carbon. The directory /var/log/carbon-c-relay should be created with owner carbon-c-relay.
You can do this manually now while I update, push and test the package.


ps. the correct place is to report EPEL issues is: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL

**Comment by Civil** [comment]
nitr0dv, at this moment we have 4 roles:
1. submission. It's installed on all the servers and serves as a load balancer across central relays
2. relay - sends the data to appropriate cluster or to aggregators
3. aggregators
4. store - load balancer for carbon-cache's.

**Comment by nitr0dv** [comment]
@Civil thanks!
@piotr1212 I'll try to do this w/ user/permissions, thanks!

**Comment by piotr1212** [comment]
I've created https://bugzilla.redhat.com/show_bug.cgi?id=1329568

**Comment by piotr1212** [comment]
Actually, your logs should be in the journal:

journalctl _SYSTEMD_UNIT=carbon-c-relay.service

**Comment by nitr0dv** [comment]
With the @Civil UNIT file and w/o -D -l <log_path> options carbon-c-relay started properly.

**Comment by Civil** [comment]
Yeah, with systemd you shouldn't use carbon-c-relay's daemonization and logging facilities.

**Comment by grobian** [comment]
I believe this is sufficiently handled downstream by the distros, and c-relay doesn't have to change for this.

**Comment by diuis** [comment]
Hi @nitr0dv , hi all.
The standard rpm for carbon-c-relay was fixed today by the mantainer (Piotr Popieluch, @piotr1212 ).
The braces before and after ARGS variable on the systemd configuration file are not correct (the custom file posted by @Civil is ok!).

http://koji.fedoraproject.org/koji/buildinfo?buildID=801673
_Changelog:
* Fri Sep 16 2016 Piotr Popieluch <piotr1212@gmail.com> - - 2.2-2
- Remove braces from systemd service file to correctly interpret arguments_
