### ISSUE TITLE
Incoming UDP metrics are not relayed

### ISSUE THREAD

**Issue by alchuk** [grobian/carbon-c-relay#171]
My freshly built instance doesn't seem to accept any data coming in over UDP.
Running in debug mode only shows statistics get sent to configured carbon daemons.
The config is quite simple

cluster local_carbon
  carbon_ch
    127.0.0.1:2013=writer1
    127.0.0.1:2023=writer2
    127.0.0.1:2033=writer3
    127.0.0.1:2043=writer4
  ;
match *
  send to local_carbon
  stop
  ;

How do I make sure that is or is not a bug?

**Comment by grobian** [comment]
You are sending metrics to the relay over udp?  Can you share how?

**Comment by alchuk** [comment]
Sure. Proxmox VE since version 4.1 has the ability to send graphite metrics, but only over UDP.

**Comment by grobian** [comment]
I will try and see what/if it does for me.

**Comment by grobian** [comment]
I started a server:
```
parsed configuration follows:
cluster x
    forward
        127.0.0.1:2004
    ;

match *
    send to x
    ;

[2016-04-26 11:46:01] listening on tcp4 0.0.0.0 port 2003
[2016-04-26 11:46:01] listening on tcp6 :: port 2003
[2016-04-26 11:46:01] listening on udp4 0.0.0.0 port 2003
[2016-04-26 11:46:01] listening on udp6 :: port 2003
[2016-04-26 11:46:01] listening on UNIX socket /tmp/.s.carbon-c-relay.2003
[2016-04-26 11:46:01] starting 2 workers
[2016-04-26 11:46:01] starting statistics collector
[2016-04-26 11:46:01] starting servers
[2016-04-26 11:46:25] failed to connect() for 127.0.0.1:2004: Hangup
[2016-04-26 11:49:49] server 127.0.0.1:2004: OK
```

Then used nc to send an entry over udp:
```
% echo "a.b.c 1 2" | nc -u mymachine 2003
```

Afterwards I opened up a listener on mymachine to see if the event went through:
```
% nc -l -p 2004
a.b.c 1 2
```

Which suggests to me it works to a certain extent.  Does tcpdump or something show the traffic arriving?  Does the relay report it's listening for udp connections?

**Comment by alchuk** [comment]
I'm sorry I bothered you. A little experiment with netcat helped me find out that it's a bug in Proxmox.
It doesn't supply metrics with \n, so that they are thrown out to carbon as a single line.
Thank you

**Comment by grobian** [comment]
No problem!  If you can't get Proxmox to fix that easily, maybe I can look into getting the relay to work with those "packets" when sent via UDP.

**Comment by alchuk** [comment]
I don't think it's reasonable to write a workaround code for such an easy-to-fix issue.
Thank you again (:
