### ISSUE TITLE
shutting down a large configuration takes ages

### ISSUE THREAD

**Issue by grobian** [grobian/carbon-c-relay#177]
The server changes to allow inheriting and sanity checks have removed the ability to do parallel distruction of the servers.  In configurations with a large amount of hosts (~200) it takes very long to shut down, simply because all hosts are one by one shut down, which often reside in a ~400ms sleep.

**Comment by Civil** [comment]
https://github.com/grobian/carbon-c-relay/blob/master/server.c#L570
