### ISSUE TITLE
Default service script has User as 'carbon' but RPM install creates 'carbon-c-relay' user

### ISSUE THREAD

**Issue by iDemonix** [grobian/carbon-c-relay#179]
New to carbon-c-relay, so unsure whether this is due to legacy or similar reasons.

Installed carbon-c-relay from EPEL to find it would not start with any variation of config using the service script. Starting the application manually logged in as root worked fine. Looking in the service script I noticed that

`[Service]
User=carbon`

But the RPM installation had created

`carbon-c-relay:x:994:992:Carbon cache daemon:/:/sbin/nologin`

Renaming the user to carbon fixed the issue. Unless I'm missing something, the service script should be amended to carbon-c-relay as the user, or the RPM installation should result in the carbon user being created. 

I can modify and submit a PR if required.

**Comment by grobian** [comment]
This sounds like a mistake in the spec-file then.  @piotr1212 is this something you can pick up?

**Comment by piotr1212** [comment]
Thanks, I'm pushing fixed version to testing repos right now.

**Comment by piotr1212** [comment]
You can follow the update here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-276c44163b
It will take a day or two before this is pushed to epel-testing repo and all mirrors. It needs to stay in testing for two weeks before it can be pushed to epel-stable.

**Comment by iDemonix** [comment]
Thanks guys.

So I can modify my current installation, and so I don't have issues in future, could you let me know whether you changed the created user, or the configured user?

**Comment by piotr1212** [comment]
I changed the user in the service file to carbon-c-relay

see:
http://pkgs.fedoraproject.org/cgit/rpms/carbon-c-relay.git/diff/carbon-c-relay.service?id=9bc62c7306efa81f4fb9985b9381917e1616e159

**Comment by druchoo** [comment]
@piotr1212, Can you build for EL6 as well?

**Comment by piotr1212** [comment]
@druchoo EL6 does not have systemd but uses sysv init, the sysv script did have the correct user set so it does not need an update. Do you experience issues with the epel6 package?

ps. official place to report issues with epel packages is bugzilla.redhat.com (new -> Fedora -> Fedora EPEL). But I don't mind checking github.

**Comment by druchoo** [comment]
@piotr1212, Sorry I just meant could you build 1.11 for EL6. The latest I see on https://bodhi.fedoraproject.org is 1.10.

**Comment by piotr1212** [comment]
sure, just pushed a new build to epel6-testing.

EPEL update policy is quite conservative. I try to build and test first on Fedora and epel7 and keeping it there for a while before pushing to older el releases.
https://fedoraproject.org/wiki/EPEL/GuidelinesAndPolicies#Digest
