### ISSUE TITLE
Router optimise doesn't work with regex grouping.

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#184]
Now that the number of rules has grown to a big enough size to trigger `router_optimise` to walk through all patterns. I've noticed that some aggregations have stopped, where a rule like so exists.
```
aggregate
    (foo|bar)\.(.+)
  # ...
  ;
```

What happens is that a `bar` group is created, and all rules that match `bar` go into it.  But when a metric `foo` comes in, it never hits the rule.

**Comment by grobian** [comment]
Ok, it's a matter of removing the optimiser code, or making it deal with simple expressions only.  (I guess its heuristics still work out well for a pattern like '.*foo.*bar.*')

**Comment by iain-buclaw-sociomantic** [comment]
Yes.  Although that's not to say that being aware of regex groups is not a bad thing, where in the above example, two groups are created with the same rules inside.

However for simplicity, something like the following works well enough.
```
                /* strip off chars that won't belong to a block */
                int ingroup = 0;
                while (
                                p > rwalk->pattern &&
                                ingroup > 0 ||
                                (*p < 'a' || *p > 'z') &&
                                (*p < 'A' || *p > 'Z') &&
                                *p != '_'
                          ) {
                        if (*p == ')')
                                ingroup++;
                        else if (*p == '(' && ingroup > 0)
                                ingroup--;
                        p--;
                }

```
So a pattern like `foo\.(bar|baz)` will go inside a rule for `foo`

**Comment by grobian** [comment]
That works too.  The code was originally setup to be very rule-of-thumb-like (WorkingForUs(tm)) and quite naive, but worked wonders back then.  Perhaps skipping the complex part would be smartest thing to do here indeed.
