### ISSUE TITLE
[Question] What is connection listen backlog?

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#186]
`#  -B  connection listen backlog, defaults to 3`

#143 
> currently the listen backlog is hardwired to 3, which isn't even near to sufficient on machines that handle 10K+ of connections per second, so we should be able to increase the backlog there.
> 
> This should allow resolving the
> possible SYN flooding on port 2003. Sending cookies.
> message

Can someone please explain what connection listen backlog is and elaborate on how changing this setting impacts performance?

**Comment by grobian** [comment]
I though I answered this in length, apparently not

**Comment by redbaron** [comment]
has it?  setting it to 512 will do no harm whatsoever, but would make it more reliable against short burst of new incoming connections. setting it to 3 is just silly and have no reason to exist

**Comment by grobian** [comment]
If you want to advocate changing the default to 512, then go ahead, no reason not to change it if there is a good reason for it. File a new issue for it.

**Comment by druchoo** [comment]
My question has been answered and created #203 to increase default value to 512. Closing issue.

http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html for further reading on connection listen backlog
