### ISSUE TITLE
Looks like any_of is duplicating metrics?

### ISSUE THREAD

**Issue by didip** [grobian/carbon-c-relay#191]
Hi all, we are using carbon-c-relay as a proxy running on every box. The intent for this daemon is to simply perform round-robin forwarding to dedicated graphite boxes. See example:

```
cluster graphite
    any_of
       some-remote-ip-1:2003 proto udp 
       some-remote-ip-2:2003 proto udp 
       some-remote-ip-3:2003 proto udp 
       some-remote-ip-4:2003 proto udp 
    ;

match *
    send to graphite
    ;
```
*some-remote-ip-x* are the carbon-cache instances.

As we keep increasing more instances of `some-remote-ip`, we are seeing that this metric: `carbon.agents.{host}.metricsReceived` increased proportionally.

Our expectation is that only one host should be picked.

Are we doing something wrong here? Maybe we are using wrong load balancing strategy?

**Comment by grobian** [comment]
Yes, my expectation would be the same.  I've not used UDP a lot, so perhaps something goes wrong there.  Would it possible to quickly establish if it sends double using tcpdump or something?

**Comment by didip** [comment]
When trying to simulate this on localhost, we do not see if duplications are happening.

Our suspicions are around how the carbon-c-relay behave when there are high number of UDP InErrors.

Quick question, carbon-c-relay does not do anything like retries when on UDP, correct?

**Comment by grobian** [comment]
Correct, it cannot see whether or not UDP got delivered (it's UDP...) so it always assumes success.  On localhost this is on Linux guaranteed to arrive, so perhaps this changes something.  If the write fails for some reason, the relay will retry that write, but it should do that on the same destination, unless the queues are really filled up.

**Comment by didip** [comment]
Thank you so much for taking the time to answer my questions. I think for us, the quick solution is to switch to TCP and observe the behavior again.

**Comment by grobian** [comment]
np, let me know if you find out more
