### ISSUE TITLE
 IO timeout command line option discrepancy

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#201]
Manpage/carbon-c-relay.md:

`-I : Specifies the IO timeout in milliseconds used for server connections. The default is 600 milliseconds, but may need increasing when WAN links are used for target servers. A relatively low value for connection timeout allows the relay to quickly establish a server is unreachable, and as such failover strategies to kick in before the queue runs high.`

$ carbon-c-relay --help | grep 'IO timeout'
```
-T  IO timeout in milliseconds for server connections, defaults to 600
```

**Comment by grobian** [comment]
Thanks, fixed in e9df1b2
