### ISSUE TITLE
Multiple clusters under one send_to does not work?

### ISSUE THREAD

**Issue by didip** [grobian/carbon-c-relay#202]
Hi all, I am trying to forward the same thing to 2 different clusters. Example:

```
match ^awesome\.(.+)
    send to
        my_cluster
        my_homie_cluster
    stop
    ;
```

I expect that to work, but I got this in my log file:

```
[2016-07-11 23:08:59] expected 'stop' and/or ';' after 'my_cluster' for match ^awesome\.(.+)
[2016-07-11 23:08:59] failed to read configuration '/path/to/relay.conf'
```

Should I do this instead?

```
match ^awesome\.(.+) send to my_cluster;
match ^awesome\.(.+) send to my_homie_cluster stop;
```

**Comment by grobian** [comment]
hmmm, that should have worked, what version are you using?

**Comment by grobian** [comment]
it works fine for me here, I suspect you use a version of the relay which doesn't have this feature yet (and I failed to document it in the changelog it seems).

**Comment by didip** [comment]
Thanks for the help once again, I will get the latest version then.
