### ISSUE TITLE
[Feature Request] command line to determine where metrics would go given a consistent-hash strategy.

### ISSUE THREAD

**Issue by didip** [grobian/carbon-c-relay#205]
When having a large number of metrics, it's hard to debug which carbon-cache they are going to.

**Comment by piotr1212** [comment]
Is this what you are looking for?
https://github.com/graphite-project/carbonate

Op 19 jul. 2016 6:25 a.m. schreef "Didip Kerabat" <notifications@github.com

**Comment by grobian** [comment]
Another one to look at is https://github.com/jjneely/buckytools.
You can use the -t mode of carbon-c-relay, but if you have to process a large list of them, you need some script-foo, or compile a (modified) example-program from contrib to just output the target in an easily consumable manner.

**Comment by didip** [comment]
Thank you for the reply guys, quick follow up questions if you don't mind,

1. Looks like both `carbonate` and `buckytools` does not support `fnv1a` hashing is that correct? It would be cool to have a tool that support `https://github.com/grobian/carbon-c-relay/blob/master/consistent-hash.h#L30`

2. This one is somewhat unrelated if you don't mind, the reason i asked for this ticket is because I am curious of the `fnv1a` hashing strategy. Could you explain to me on why it could be useful? I have a hard time understanding it from the README.

**Comment by grobian** [comment]
carbon_ch relies on md5, which is somewhat slow.  In addition, the algorithm uses two bytes from each hash, which at the time I felt introduced a lot of unbalancedness.  Hence fnv1a, which is a much faster hash, but should also be producing the best for the effort we put into it (see wikipedia).  So apart from it taking slightly different input (server ports are for instance part of the hash) it behaves similarly.

**Comment by grobian** [comment]
Basically, if you use -t -d you will see a dump of the hash-maps that the consistent-hash is built on, those basically show how routing will happen.  Please reopen if you have additional questions/needs.
