### ISSUE TITLE
[bug] randomly some metrics are renamed from "^[a-zA-Z]*." to "^_+[a-zA-Z]*"

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#206]
Hi @grobian 

Today at 3:14 AM  has apeared metrics like 

```
[PRODUCTION][graphiterelay01].root:metrics > ls -ltr
total 28
drwxr-xr-x 3 carbon carbon 4096 Jul 21 03:14 ____tag01
drwxr-xr-x 3 carbon carbon 4096 Jul 21 03:18 _tag02
drwxr-xr-x 3 carbon carbon 4096 Jul 21 03:18 __tag02
```

In fact metris named "tag01.XXXX" and "tag02.XXXX" exist but doen't exist metrics with "_" as the first character.

I've seen this behaviour  twice from the last update done 1 week ago to the carbon-c-relay v2.1 (b8e663), and never before.

Do you know what can be and any workarround to avoid that?

**Comment by grobian** [comment]
Hi Toni,

Do you use -HUP to reload the relay?  Your other bug indicated something weird is going on there, perhaps this bug is related.

**Comment by toni-moreno** [comment]
No,  tonigth nothing done..  I was sleeping at home :)

and also nothing in the log , last msg from the las HIP sent some days ago.

```` 
[PRODUCTION][graphiterelay01].root:~ > tail -4f /logs/apps/graphite/carbon-c-relay/carbon-c-relay.log
[2016-07-15 07:57:56] (MSG) reloading collector
[2016-07-15 07:57:57] (MSG) interrupting workers
[2016-07-15 07:57:57] (MSG) reloading workers
[2016-07-15 07:57:57] (MSG) SIGHUP handler complete

**Comment by piotr1212** [comment]
I've seen this happen as well.

It doesn't happen a lot and it was on an very old version, I see there is an hup in the daily logrotate. I assumed it was some user sending crap and didn't investigate it ;)

**Comment by AlexAkulov** [comment]
I have the same problem.
The most part of bad metrics have "_" at the beggining of their name, I detele them via cron but sometimes there are names like on the screenshot.
https://gyazo.com/62d8eedc2dfb4bba083ddab3c4ff0de8
There is garbage only on first part of metric name.


I use carbon-c-relay v1.7 from epel and I use HUP for config reload.

**Comment by nisc-acooper** [comment]
I can confirm we have seen this as well.  It does appear to be related to HUP (which we were doing for log rotate).

**Comment by grobian** [comment]
Ok, I suggest not to use SIGHUP any more if possible on versions <2.2.
@Civil and @dgryski pointed out some race behaviour that I wasn't aware of to exist, in the current development head I put some changes for that in place.  The problem is that those fixes could magically fix this problem, for the effect of them cannot be explained easily.

Since I don't have a large volume instance at my disposal anymore, I rely on other people trying out the changes and reporting whether things improved.  However, I haven't been able to fix everything yet due to other obligations.

**Comment by bilsch** [comment]
We are also seeing this with version 2.1

```
ll -d _*
drwxr-xr-x. 3 root root 21 Aug 27 00:48 _Hqeht
drwxr-xr-x. 3 root root 21 Aug 20 02:48 _Hxwqefghx
drwxr-xr-x. 3 root root 21 Aug 20 01:19 _Hxxxxxxxx
drwxr-xr-x. 3 root root 21 Aug 20 01:20 __yyyyy
drwxr-xr-x. 3 root root 21 Aug 27 00:43 __cxasgarg
drwxr-xr-x. 3 root root 20 Aug 20 02:48 __adfhgbb
drwxr-xr-x. 3 root root 21 Aug 20 02:40 __adtgjh
```

the leading `_H` and `__` are left intact the rest of the directories ( hostnames ) are obfuscated

**Comment by piotr1212** [comment]
I've just seen this happen on 2.2, I'm not 100% certain as we still have some 2.1 relays running which might have forwarded those metrics (although they shouldn't).

Interesting part: this wasn't during sighup. (checked all possisbly sending relays)

I'm updating all relays now to 2.3. Will keep an eye on it.

**Comment by grobian** [comment]
keep me posted, I'm still looking for clues on this one

**Comment by grobian** [comment]
Is this by chance with the use of UDP transport?

**Comment by AlexAkulov** [comment]
Problem is still present in version 2.3

**Comment by grobian** [comment]
and when using TCP connections?

**Comment by grobian** [comment]
For those that can sort of reproduce this, I'd love to hear if 2.4 still has the problem.

**Comment by cekstam** [comment]
I can confirm that 2.4 still has this issue;

[chek01@ifx01 carbon]$ /opt/carbon-c-relay/relay -v
carbon-c-relay v2.4 (65d425)

[chek01@ifx01 whisper]$ ls -l
drwxr-xr-x 5 graphite graphite 49 Jan 10  2014 carbon
drwxr-xr-x 3 graphite graphite 23 Jan 16 18:04 Ce_q__q_a
drwxr-xr-x 5 graphite graphite 38 Nov 17 12:13 datacenter
drwxr-xr-x 3 graphite graphite 20 Jan 16 14:31 E__q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 16 17:37 k_z_q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 15 14:08 L_q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 15 03:05 m___q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 15 06:02 _____q__q_a
drwxr-xr-x 4 graphite graphite 37 Jan 15 09:23 ____q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 14 11:22 ___q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 15 09:24 __q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 14 08:52 _q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 14 08:44 _SA_q__q_a
drwx------ 4 graphite graphite 35 Jan 13 23:05 skyline
drwx------ 5 graphite graphite 42 Jan 13 20:41 stats
drwx------ 4 graphite graphite 29 Jan 13 22:39 stats_counts
drwx------ 2 graphite graphite 25 Jan 13 20:44 statsd
drwxr-xr-x 3 graphite graphite 20 Jan 15 09:23 w__q__q_a
drwxr-xr-x 3 graphite graphite 23 Jan 15 09:23 w_q__q_a

Pushing about 3M metrics/min through it, with the following config (names redacted);
cluster foo-1
    fnv1a_ch replication 1
        127.0.0.1:2013
        127.0.0.1:2014
        127.0.0.1:2015
        127.0.0.1:2016
        127.0.0.1:2017
        127.0.0.1:2018
        127.0.0.1:2019
        127.0.0.1:2020
    ;

cluster foo-influx-1
    fnv1a_ch replication 1
        127.0.0.1:8889
    ;

cluster foo-skyline-analyzer
    fnv1a_ch replication 1
      80.72.15.79:2023
    ;

cluster foo-cyanite-cassandra
    fnv1a_ch replication 1
      127.0.0.1:62003
    ;

aggregate
        ^foo1\.foo2\.foo3\.foo4\.([^.]+)\.([^.]+)\.count
    every 10 seconds
    expire after 35 seconds
    compute sum write to
        foo1.foo2.foo3.foo4.\1.\2.count
    send to g30-1
    stop
    ;

match *
    send to foo-1
    ;

match *
    send to foo-influx-1
    ;

match foo1\.foo2\.foo3\.foo4\.foo5\.foo6-
    send to g30-skyline-analyzer
    ;

match foo\..*\.bar\.if_(dropped|errors)-
    send to g30-skyline-analyzer
    ;

match foo\..*\.bar-.*\.if_(dropped|errors)\.
    send to g30-skyline-analyzer
    ;

match .*\.foo\.bar.*
    send to g30-skyline-analyzer
    ;

match foo-*-bar
    send to g30-skyline-analyzer
    ;

Please let me know if you need anything other.

Best regards,
Christian

**Comment by grobian** [comment]
thanks, I'll have a look at it later.

**Comment by grobian** [comment]
just to be sure, foo-1 is your cluster of which you showed the directory contents of one of the members right?

**Comment by cekstam** [comment]
Yep, correct

**Comment by grobian** [comment]
the foo1 from your aggregation, is it visible in the directory contents you showed in your post?

**Comment by grobian** [comment]
More specifically, the metrics that seem prefixed with garbage, are they from the aggregate rule, or from the match rule?

**Comment by piotr1212** [comment]
We see the underscores and don't use aggregations at all. Interesting is
that on hosts with whitelisting the problem does not occur. I assume they
are appended before the match rules are processed.

Op do 19 jan. 2017 09:54 schreef Fabian Groffen <notifications@github.com>:

**Comment by grobian** [comment]
indeed, it suggests the problem is introduced while reading

**Comment by grobian** [comment]
.. unless there is another c-relay in front of it which introduces the problem while writing

**Comment by piotr1212** [comment]
No, we only use it on the receiving servers.

Op do 19 jan. 2017 10:49 schreef Fabian Groffen <notifications@github.com>:

**Comment by grobian** [comment]
that reduces the candidate list a lot then, thanks

**Comment by cekstam** [comment]
Our underscores are from non-aggregated datapoints, and the carbon-c-relay is the only thing between the clients and the carbon-cache-processes.

**Comment by grobian** [comment]
would you classify the carbon-cache.py processes to be fairly busy?

**Comment by piotr1212** [comment]
It also happens on systems with low carbon-cache.py usage (just 1500 metrics/minute/cache). Also seen it with go-carbon backend. All here runs on VM's, random freezes can occur sometimes.

PS. just recently started updating from 2.3 to 2.5, not seen it happen on 2.5 yet.

**Comment by grobian** [comment]
I'm tryng hard to think about ways to allow me to narrow down to the root of this problem, but I can't seem to get a grip on it.  Since the garbage only appears to happen at the start of a metric, I'm wondering if clients do something like keep-alive probes or that the relay is adding those on outgoing traffic (but inspecting that code didn't reveal anything that looks suspicious).

**Comment by piotr1212** [comment]
Can imagine. I have no clue how to reproduce this, doesn't happen that often either. If there is anything I could do let me know.

**Comment by cekstam** [comment]
> would you classify the carbon-cache.py processes to be fairly busy?

Somewhere around 20-40% CPU constantly, the load is pretty much constant. I'm getting around 1-5 new metrics per minut (which are broken ones), so if there's anything I can do to help debug it I'm all yours :)

**Comment by grobian** [comment]
Perhaps you could run a tcpdump on the input and output ports of the relay and share the transcript with me if a broken metric was created (please send the file by email).  Perhaps the dump can tell me how the metric went in and out.

**Comment by piotr1212** [comment]
Just found out it the underscores are triggered by a vulnerability scanner. Don't know yet which one and what it does.

**Comment by dgryski** [comment]
Scanner should probably ignore carbon-c-relay then.  Also, I doubt the parser has been sufficiently fuzzed.

**Comment by grobian** [comment]
@piotr1212: following a lead here, I think I already found it ... oops
@dgryski: correct, only the config parser was fuzzed, because I couldn't find a way to use socket IO + verification

**Comment by grobian** [comment]
Lead was a dead end, I suspected a non-initialised buffer, but that's not the case. :(

**Comment by piotr1212** [comment]
I think this is fixed in 730743bb2a24256d6ccf6206afe10faf3c845460 version v2.5

Pre:
`echo -n "%" | nc -u 127.0.0.1 2003; echo "bla 42 $(date +%s)" | nc -u 127.0.0.1 2003`
Gives:
`_bla 42 1485207625`

After that commit it gives:
`bla 42 1485207625`

Only thing is that the metrics we see going wrong are not sent over UDP but TCP. I tried mixing up UDP and TCP but don't get this result.

**Comment by grobian** [comment]
That's the thing that's bothering me.  For UDP I get it, and fixed it, but for TCP – which is repeatedly reported as the transport being used – I don't see yet how it can trigger.
You mentioned the vulnerability scanner likely causing this for you, it should still produce the same thing on v2.5 then.  Also @cekstam are you on v2.5?

**Comment by piotr1212** [comment]
Got it reproduced:
`echo -e '%\x00\x20' | nc localhost 2003`
It is the NULL character which passes the strchr test...

**Comment by grobian** [comment]
darn, that's a good find!

**Comment by grobian** [comment]
@piotr1212 I slightly changed your patch to make it also cover values and timestamps.  Thanks, applied now.  Will release shortly.
