### ISSUE TITLE
Make UDP recv buffer size adjustable

### ISSUE THREAD

**Issue by drawks** [grobian/carbon-c-relay#207]
I'm not much of a C coder, but I can't seem to find any explicit set of socket options to set udp receive buffer size. I'm running at very high throughput and attempting to tune carbon-c-relay it would be very nice if I could explicitly set the udp receive buffer socket option so that I don't have to ham fistedly increase the default for my whole system.

**Comment by grobian** [comment]
Hmmm, that shouldn't be too hard, it appears we can do setsockopt with SO_RCVBUF.  I'll look into it later.

**Comment by grobian** [comment]
I gave this a shot, might need some small refinements, but it should be a start.
