### ISSUE TITLE
Incorrect program name in usage message?

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#210]
https://github.com/grobian/carbon-c-relay/blob/master/relay.c#L303

Currently:
`Usage: relay [-vdst] -f <config> [-p <port>] [-w <workers>] [-b <size>] [-q <size>]`

Should be? 
`Usage: carbon-c-relay [-vdst] -f <config> [-p <port>] [-w <workers>] [-b <size>] [-q <size>]`

Maybe update with options that aren't currently listed too?

**Comment by grobian** [comment]
in a way ... the makefile produces a binary called "relay", perhaps I should change that because it's more suited for upstreams like redhat/debian

**Comment by mhollick** [comment]
Haven't we been here before?  ;-)

**Comment by grobian** [comment]
uhm, yeah, I think that was issue #13

**Comment by piotr1212** [comment]
relay is already being installed as /usr/bin/carbon-c-relay on Fedora and Red Hat. The name in the manpage is also carbon-c-relay. It would make sense to rename it in the makefile to carbon-c-relay as well for consistency.
I guess the usage text should not hard-code it but print argv[0]..

**Comment by grobian** [comment]
I tend to agree, on Gentoo and Debian it's carbon-c-relay too.
