### ISSUE TITLE
Aggregator sends nan to carbon-cache

### ISSUE THREAD

**Issue by kshcherban** [grobian/carbon-c-relay#211]
Hello,

I'm using 2.1 version of c-relay and have set the following aggregation rule. Collectd sends metrics every minute.

```
aggregate
  ^collectd\.servers\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.interface-.+\.if_octets\.[^.]+
  every 60 seconds
  expire after 70 seconds
  compute sum write to
    collectd.sum.if_octets.total
  ;
```

And seeing some strange null points every several minutes

```
tcpdump -A -i lo port 2003 | grep collectd.sum.if_octets.total
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
"..."..Scollectd.sum.if_octets.total 8493552654.250317 1472122500
"..-"...collectd.sum.if_octets.total 8321547501.755362 1472122560
".".".".collectd.sum.if_octets.total nan 1472122620
".].".]Ecollectd.sum.if_octets.total 8391914814.025881 1472122680
collectd.sum.if_octets.total 8408852262.608275 1472122740
```

Can you shed some light why aggregator sends NaN values?

**Comment by grobian** [comment]
My first shot would be that this is a divide by zero: for some reason the bucket (60 seconds) didn't receive any values.  If the problem happens often enough, it would be good to know if increasing the expiry time from 70 to something like 85 reduces/removes the problem.

**Comment by kshcherban** [comment]
@grobian i've tried increasing expire time to 90 and it didn't help. Do you need some additional information?

**Comment by grobian** [comment]
Ok, then I'd like to know if collectd is able to deliver the metrics to the relay, a tcpdump around a nan value should help here.

Also, I just realised that if a bucket is empty, it won't send anything, so I'll have a look later to see what could result in that behaviour.

**Comment by kshcherban** [comment]
Collectd is sometimes sending incomplete data, like this. But the overall amount of correct data is greatly higher and if i manually render sum in graphite web in works fine.
```
collectd.servers.x.x.x.server1.interface-dummy0.if_octets.tx 0.
```

**Comment by grobian** [comment]
Right, it looks like there's a "garbage value" which ends up being NaN, and math on NaNs end up being NaN.

Question right now is (given we can't fix why incomplete data is being received/sent) if the relay should ignore NaNs in the aggregator or not.

**Comment by kshcherban** [comment]
Ignoring NaN makes sense as it's garbage and aggregated metric shouldn't be affected by some seldom garbage. Strange that collectd sends garbage over TCP, looks like bug.

**Comment by grobian** [comment]
Ok, I tried this on my Mac and Linux boxes, and couldn't get nan, unless I insert nan as value.  So I'd like to see what values go into the relay when you get nan as output, if possible.

**Comment by kshcherban** [comment]
This is what i've got from tcpdump. Log is not complete and i changed metric names

```
tcpdump -A -i eth0 port 2013 | grep 'collectd.servers.*if_octets'

collectd.servers.x.x.x.x.interface-eth0.if_octets.rx 489.966782 1472125946
collectd.servers.x.x.x.x.interface-eth0.if_octets.tx 392.
collectd.servers.x.x.x.x.interface-eth1.if_octets.rx 0.000000 1472125946
collectd.servers.x.x.x.x.interface-eth1.if_octets.tx 0.000000 1472125946
...
collectd.servers.x.x.x.x.interface-dummy0.if_octets.tx 0.000000 1472125943
collectd.servers.x.x.x.x.interface-eth0.if_octets.rx 
collectd.servers.x.x.x.x.interface-eth0.if_octets.tx 881498.494642 1472125943
...
collectd.servers.x.x.x.x.interface-eth0.if_octets.tx 3
```

**Comment by grobian** [comment]
question: do you use SIGHUP to reload the config of the relay by chance?

**Comment by kshcherban** [comment]
nope, i use init script from debian package and it has only restart option

**Comment by grobian** [comment]
I'd be very interested to see if this also happens with v2.2

**Comment by kshcherban** [comment]
Yep, i still see nan from aggregator.

**Comment by grobian** [comment]
I'm trying to reproduce this, but can't seem to get the behaviour you see.  How often does this occur?

**Comment by kshcherban** [comment]
Unfortunately yes. It's happening not too often. You can check this [affected graph](https://www.prolinux.org/files/c-relay-aggregator.png).

**Comment by grobian** [comment]
failure to reproduce this issue, cannot pinpoint/fix it for that reason
