### ISSUE TITLE
Stats about metrics from the past/metrics from the future

### ISSUE THREAD

**Issue by Civil** [grobian/carbon-c-relay#217]
It'll be nice to have some statistics (exportable on demand by some tcp/http interface) with the following paramterers (for each metric):
1. How many values were passed in last minute for this metric
2. How many points were from the past (metric timeStamp differs from current timeStamp for more than 1h for example)
3. How many points with time stamp from the future (metric ts > current time).

But to do that efficiently it'll require to convert data to binary protocol on receive (in that case you can have binary receiver and text receiver, if you receive metrics in text from you can convert them into binary from as soon as possible).

**Comment by grobian** [comment]
Doesn't (regardless of communication protocol) this require a ginormous amount of memory and resources to keep this updated?  Isn't that what your graphiteStores are for in a way?

**Comment by dgryski** [comment]
There are streaming algorithms that can give good approximations with low memory and low CPU requirements.  For example, HyperLogLog++ for cardinalities, streaming topk algorithms ( https://github.com/dgryski/go-topk ), streaming approximate counters ( https://github.com/dgryski/go-sscounter ) , ...

**Comment by grobian** [comment]
The problem is 1) it requires an allocation for each and every unique metric seen by the relay (+ matching) which is potentially going to be huge.

Some stats about timestamp offsets 2) and 3) should be less of an issue.

**Comment by Civil** [comment]
It should require (for a counter) about 3*8 bytes per metric, which is overhead of 24 byte per metric. Plus it requires some space to store names, but I think with something like adaptive radix-tree (or something similar) it should be reasonable overhead in terms of memory consumption, but for millions of unique metrics yes it will be several GB of RAM.

**Comment by dgryski** [comment]
For approximate queries, we can do better than linear space.  This is an active area of research.

**Comment by Civil** [comment]
The idea is to have some visibility about who is doing strange sutff (e.x. sending data from N years in the past, or data from the future) - so it requires to have metric paths (or some ability to construct them), but the queries to this thing will be:
1. Give me all metrics from the past or future
2. Give me topK metrics by rate.

As about problems:
> it requires an allocation for each and every unique metric seen by the relay (+ matching)

Yes, but names can be compressed, and 3 counters per metric is not very huge. You can make it optional with a warning, that in that case it might eat 10GB of RAM for 100M of metrics (I actually think it'll take less than that).

> Some stats about timestamp offsets 2) and 3) should be less of an issue.

The issue I see here is that you'll need to parse timestamps for each metric, and string parsing is not very efficient, so to keep with the same level of performance you most probably will want to came up with binary protocol (something simple, just to pass struct{timestamp uint32, value float64, name char*}), parse it on submission and calculate stats at the relay level. In that case getting stats shouldn't affect performance and new messages will be smaller. Also it might help a little bit with aggregator part (reduce CPU consumption and increase throughput a little bit).

**Comment by grobian** [comment]
Throughout all this, I still keep the feeling that this kind of stuff doesn't belong in the "relay".  There is systems like influxdb and stuff that are supposedly very well suited for doing all this kind of ad-hoc analysis.
So, instead of shoe-horning the relay to answer your questions (which will no doubt complicate the relay even more and introduce the necessary problems) I have the feeling it would be better to answer this with a (memory-backed?) system that doesn't have the same requirements are your router (the relay) so it can do the occasional gulp and more as needed.  I recall a project out there that was basically a carbon memory store, but could do top-K queries and store only a recent subset of data.  Perhaps that would be a much more scalable way of doing this?

**Comment by dgryski** [comment]
We are investigating doing this out-of-band and/or off-line.

**Comment by grobian** [comment]
I was looking for https://github.com/dgryski/carbonmem :)

**Comment by grobian** [comment]
This is not going to be on the todo list anytime soon.
