### ISSUE TITLE
segfault during (or right after) sighup, carbon-c-relay 2.2 on rhel6

### ISSUE THREAD

**Issue by piotr1212** [grobian/carbon-c-relay#224]
I've had a carbon-c-relay segfault right after a sighup. Last entries in the logfile were:

[2016-10-30 03:27:06] (MSG) reopening logfile
[2016-10-30 03:27:06] (MSG) reloading config from '/etc/carbon-c-relay.conf'
[2016-10-30 03:27:06] (MSG) no config changes found
[2016-10-30 03:27:06] (MSG) SIGHUP handler complete

I've got a coredump and posted some backtraces here: 
https://paste.fedoraproject.org/466859/27183147/

Might be worth to note is that there was an unreachable destination during the segfault.

If you need more gdb debug info please let me know.

**Comment by grobian** [comment]
Sounds a lot like https://github.com/grobian/carbon-c-relay/issues/188, but that fix should be in 2.2

**Comment by grobian** [comment]
what exactly do you mean by unreachable destination?

**Comment by piotr1212** [comment]
Before the sighup the log had many "failed to connect" errors:
[2016-10-30 03:27:03] (ERR) failed to connect() to somehostname.somedomain:2003: Operation timed out
[2016-10-30 03:27:06] (MSG) caught SIGHUP
[2016-10-30 03:27:06] (MSG) closing logfile

**Comment by piotr1212** [comment]
Just checked to be sure, it really is version 2.2

I managed to reproduce it on this system. After sending 25x a sighup it would crash.

The configuration:

[2016-10-31 21:03:44] (MSG) starting carbon-c-relay v2.2 (2016-09-16), pid=15329
configuration:
    relay hostname = xxx
    listen port = 2003
    workers = 16
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    statistics submission interval = 60s
    listen backlog = 64
    server connection IO timeout = 600ms
    daemon = true
    routes configuration = /etc/carbon-c-relay.conf

parsed configuration follows:
cluster xxxx
    carbon_ch replication 1
        xxx:2203=a
        xxx:2303=b
        xxx:2403=c
        xxx:2503=d
    ;
cluster xxx2
    forward
        xxxx:2003
    ;
cluster xxx3
    forward
        xxxx:2244
    ;
cluster xxxxxx
    forward
        xxx:2003
    ;

match ^carbon\.
    send to xxxx
    ;
match *
    send to xxx
    ;
match *
    send to xxx
    ;
match *
    send to blackhole
    stop
    ;

**Comment by piotr1212** [comment]
Different message this time:
Core was generated by `/usr/bin/carbon-c-relay -P /var/run/carbon-c-relay/carbon-c-relay.pid -D -B 64'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000036d6c440e6 in _IO_vfprintf_internal (s=0x7de630, format=0x4137b3 "%s ", ap=0x7f5b7ebfcb50) at vfprintf.c:1328
1328      outstring ((const UCHAR_T *) format,

**Comment by piotr1212** [comment]
Shouldn't this stall here:
https://github.com/grobian/carbon-c-relay/blob/v2.2/relay.c#L93-L95
be before the switch statement and specifically the dst assignment in there?

**Comment by piotr1212** [comment]
I've done some testing, the segfault is very reproducible when configuring many wrong destinations which forces the relay to log a lot and do a hup then. 
The referenced PR fixes my issue.

**Comment by grobian** [comment]
Thanks, I'll make a new release now.

**Comment by grobian** [comment]
this is in v2.3
