### ISSUE TITLE
whitespace in metric name

### ISSUE THREAD

**Issue by toopa2002** [grobian/carbon-c-relay#228]
Metric that have whitespace in metric name is not dropped by carbon-c-relay. 
For example => echo "test.test test 1478206983" | nc localhost 2003
I think it is better to drop this kind of metric in c-relay rather than allow it pass to Carbon-cache service.

Here is my pull request => https://github.com/grobian/carbon-c-relay/pull/227

**Comment by grobian** [comment]
this should be done via validation instead, this solution might work for you, but isn't generic enough IMO.

**Comment by toopa2002** [comment]
Where should be the place to add this validation?

**Comment by piotr1212** [comment]
See the other pr and referenced commits and comments for some discussion.
My objection to this patch would be that metrics are silently dropped and
not logged.
Besides that, I would really love to see filtering in the relay,
unfortunately I still don't have time to work on it.

Op 10 nov. 2016 7:10 a.m. schreef "Vichan Chutitaporn" <
notifications@github.com>:

**Comment by grobian** [comment]
Sorry, I was indeed referring to @piotr1212 work in an old pull request and other issues.

I want to be able to do somehing like:
```
validate * require data [0-9]+\s[0-9]+;
```

**Comment by grobian** [comment]
or perhaps
```
match * validate [0-9]+\s[0-9]+ [log|blackhole] send to foo
```

**Comment by toopa2002** [comment]
If i understand correctly, "validate" will be new cluster type.  Should the validation perform against the whole line, not just only metric name?  The problem is metric name is string before first space. It can't solve my problem if we not validate the whole line.

**Comment by grobian** [comment]
Correct, the validate will be on the data (so everything after the metric).

I started working on this idea, to validate my thoughts, and it seems doable to implement it this way.

**Comment by grobian** [comment]
please give it a try, syntax ended up a bit more verbose:
`validate <regex> else <log|drop>` (the else was introduced to make the counter action more obvious).

**Comment by piotr1212** [comment]
Great. Will try to do some testing today.

For (the lazy) rhel/centos/fedora users: rpm package with validation support can be found here:
https://copr.fedorainfracloud.org/coprs/piotrp/Graphite/

**Comment by piotr1212** [comment]
Validation seems to work. Interesting behaviour is when I send double spaces, they get truncated to one, eg:

```
match ^foo
    validate ^[0-9]+\ [0-9]+$ else log
    send to local_carbon
    stop
    ; 
```

sending "foo.bar 42     1234" results in the relay forwarding:  "foo.bar 42 1234"

**Comment by grobian** [comment]
Yeah, metric cleanup is done before validation.  It will be hard to change this, and I figured that is more what you want so you don't have to bother about how people send the data.

**Comment by piotr1212** [comment]
Yes, I'm actually happy about it, I was expecting it to be dropped ;)

**Comment by grobian** [comment]
I'll check if I actually documented that "feature", if not I'll add it to make sure people who read won't be surprised :)
