### ISSUE TITLE
[Question] Is there a way to encrypt traffic from carbon c relay to ELB

### ISSUE THREAD

**Issue by pratikp09** [grobian/carbon-c-relay#230]
Hi we need to encrypt all the traffic sent from carbon c relay to ELBs. Is there a way to do it? How does carbon c relay work with the SSL?

**Comment by grobian** [comment]
There's currently no encapsulation for the traffic such as encryption or compression.

**Comment by chbuescher** [comment]
Why not use good old stunnel - stunnel.org - for en-/decryption ?

**Comment by grobian** [comment]
Something like that would have my preference in order to keep the relay simple.

**Comment by ehlerst** [comment]
This is probably what you want for this, im using it together with carbon-c-relay which does aggregation more efficiently.
https://github.com/jamiealquiza/polymur


app -> polymur-proxy -> elb -> polymur-gateway -> carbon-c-relay -> go-carbon

**Comment by grobian** [comment]
In master I'm working on encapsulation, but it'll take a while I'm affraid.  polymur looks interesting and a good alternative.
