### ISSUE TITLE
segfault while reloading (new one) 

### ISSUE THREAD

**Issue by piotr1212** [grobian/carbon-c-relay#231]
Found a new one, you must be hating me now ;)

This is while trying out the new validate log commit, config:

match *
  validate ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\ [0-9]{10}$ else log
  ;

carbon-c-relay[23046]: segfault at ebf2b108 ip 0000000000408d79 sp 00007ffc7fe35ba0 error 4 in carbon-c-relay[400000+1b000]

Loaded symbols for /lib64/ld-2.12.so
Core was generated by `/usr/bin/carbon-c-relay -P /var/run/carbon-c-relay/carbon-c-relay.pid -D -B 64'.
Program terminated with signal 11, Segmentation fault.
#0  router_printconfig (rtr=<value optimized out>, f=0x1189b10, pmode=2 '\002') at router.c:2601
2601					if (d->next == NULL) {

(gdb) bt full
#0  router_printconfig (rtr=<value optimized out>, f=0x1189b10, pmode=2 '\002') at router.c:2601
        or = 0xebf228
        d = 0xebf2b100
        c = <value optimized out>
        r = 0xebf228
        s = <value optimized out>
#1  0x0000000000409745 in router_printdiffs (old=<value optimized out>, new=0xebbbb0, out=0xebbc20)
    at router.c:2672
        f = 0x1189b10
        fd = <value optimized out>
        tmp = <value optimized out>
        patho = "/tmp/carbon-c-relay_route.x28Jpc\000\000\0 << PIOTR: TRUNCATED >> 0"...
        pathn = "/tmp/carbon-c-relay_route.kSgwXD\000\00 << TRUNCATED >> �01\000\000"...
        buf = " ]�  <<TRUNCATED >>>�\031", '\000' <repeats 31 times>, "\<< MORE TRUNCATED>>"...
        len = <value optimized out>
        ret = <value optimized out>
        mask = 18
#2  0x0000000000403c18 in do_reload (argc=<value optimized out>, argv=<value optimized out>)
    at relay.c:165
        newrtr = 0xebbbb0
        newaggrs = <value optimized out>
        numaggregators = <value optimized out>
        id = <value optimized out>
        newfd = <value optimized out>
#3  handle_signal (argc=<value optimized out>, argv=<value optimized out>) at relay.c:271
        sign = <value optimized out>
#4  main (argc=<value optimized out>, argv=<value optimized out>) at relay.c:829
        stream_sock = {0, 2, 0}
        stream_socklen = 2
        dgram_sock = {1, 0}
        dgram_socklen = 1
        id = <value optimized out>
        listenport = <value optimized out>
        listenbacklog = 64
        ch = <value optimized out>
        numaggregators = 0
---Type <return> to continue, or q <return> to quit---
        listeninterface = 0x7d3 <Address 0x7d3 out of bounds>
        allowed_chars = <value optimized out>
        smode = CUM
        pidfile = 0x7ffc7fe39e97 "/var/run/carbon-c-relay/carbon-c-relay.pid"
        pidfile_handle = <value optimized out>
        aggrs = <value optimized out>

Thread 5 (Thread 0x7f6b86bf0700 (LWP 23048)):
#0  0x000000307ccdf283 in __poll (fds=<value optimized out>, nfds=<value optimized out>, 
    timeout=<value optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:87
        __arg2 = 2
        _a3 = 1000
        _a1 = 140099798891808
        resultvar = <value optimized out>
        __arg3 = 1000
        __arg1 = 140099798891808
        _a2 = 2
        resultvar = <value optimized out>
        oldtype = 0
        result = <value optimized out>
#1  0x0000000000406bf0 in dispatch_runner (arg=0xe59bb0) at dispatcher.c:576
        ufds = {{fd = 0, events = 1, revents = 0}, {fd = 2, events = 1, revents = 0}, {
            fd = -2034303552, events = 32619, revents = 0}, {fd = 0, events = 0, revents = 0}, {
            fd = -2034303528, events = 32619, revents = 0}, {fd = 0, events = 1, revents = 0}, {fd = 0, 
            events = 0, revents = 0}, {fd = 2101358466, events = 48, revents = 0}, {fd = 0, events = 0, 
            revents = 0} <repeats 12 times>, {fd = 2092996096, events = 48, revents = 0}, {
            fd = -2013294592, events = 32619, revents = 0}, {fd = 0, events = 0, revents = 0}, {
            fd = -1, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = 5, events = 0, 
            revents = 0}, {fd = 2103541840, events = 48, revents = 0}, {fd = 0, events = 0, 
            revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = 3, events = 0, revents = 0}, {
            fd = 0, events = 0, revents = 0}, {fd = 2088821152, events = 48, revents = 0}}
        fds = 2
        self = 0xe59bb0
        conn = <value optimized out>
        c = <value optimized out>
#2  0x000000307d407aa1 in start_thread (arg=0x7f6b86bf0700) at pthread_create.c:301
        __res = <value optimized out>
        pd = 0x7f6b86bf0700
        now = <value optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140099798894336, -1132034315319391589, 
                208261989216, 140099798895040, 0, 3, 1053061334277933723, -1140872741364839781}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <value optimized out>
        pagesize_m1 = <value optimized out>
        sp = <value optimized out>
        freesize = <value optimized out>
#3  0x000000307cce8aad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
No locals.

**Comment by grobian** [comment]
can't hate you for using my software ... 👍

**Comment by grobian** [comment]
can you test and see if my fix above really solves the issue for you?

**Comment by piotr1212** [comment]
I think i'm running into a different one now. 
With above config, start relay, sighup twice, results in: 

```
configuration:
    relay hostname = fedora
    listen port = 2003
    workers = 4
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    statistics submission interval = 60s
    listen backlog = 32
    server connection IO timeout = 600ms
    routes configuration = carbon-c-relay.conf

parsed configuration follows:
cluster local_carbon
    forward
        127.0.0.1:2013
    ;

match *
    validate ^[-+]?[0-9]*.?[0-9]+([eE][-+]?[0-9]+)?\ [0-9]{10}$ else log
    send to local_carbon
    stop
    ;

[2016-11-23 01:05:40] listening on tcp4 0.0.0.0 port 2003
[2016-11-23 01:05:40] listening on tcp6 :: port 2003
[2016-11-23 01:05:40] listening on udp4 0.0.0.0 port 2003
[2016-11-23 01:05:40] listening on udp6 :: port 2003
[2016-11-23 01:05:40] listening on UNIX socket /tmp/.s.carbon-c-relay.2003
[2016-11-23 01:05:40] starting 4 workers
[2016-11-23 01:05:40] starting statistics collector
[2016-11-23 01:05:40] starting servers
[2016-11-23 01:05:54] caught SIGHUP
[2016-11-23 01:05:54] reloading config from 'carbon-c-relay.conf'
[2016-11-23 01:05:54] no config changes found
[2016-11-23 01:05:54] SIGHUP handler complete
[2016-11-23 01:05:55] caught SIGHUP
[2016-11-23 01:05:55] reloading config from 'carbon-c-relay.conf'
[2016-11-23 01:05:55] no config changes found
Segmentation fault (core dumped)
```

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./relay -f carbon-c-relay.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
234					if (routes->dests->cl->type == GROUP ||
[Current thread is 1 (Thread 0x7fd3852d4b40 (LWP 31216))]
(gdb) bt
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
#1  0x00000000004074f6 in router_free_intern (clusters=0x1d66d90, routes=0x1d66ece)
    at router.c:239
#2  0x000000000040aa53 in router_free (rtr=rtr@entry=0x1d66d50) at router.c:2764
#3  0x00000000004039ba in do_reload () at relay.c:168
#4  handle_signal (sig=1) at relay.c:271
#5  main (argc=<optimized out>, argv=<optimized out>) at relay.c:829
(gdb) 
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
#1  0x00000000004074f6 in router_free_intern (clusters=0x1d66d90, routes=0x1d66ece)
    at router.c:239
#2  0x000000000040aa53 in router_free (rtr=rtr@entry=0x1d66d50) at router.c:2764
#3  0x00000000004039ba in do_reload () at relay.c:168
#4  handle_signal (sig=1) at relay.c:271
#5  main (argc=<optimized out>, argv=<optimized out>) at relay.c:829
(gdb) 
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
#1  0x00000000004074f6 in router_free_intern (clusters=0x1d66d90, routes=0x1d66ece)
    at router.c:239
#2  0x000000000040aa53 in router_free (rtr=rtr@entry=0x1d66d50) at router.c:2764
#3  0x00000000004039ba in do_reload () at relay.c:168
#4  handle_signal (sig=1) at relay.c:271
#5  main (argc=<optimized out>, argv=<optimized out>) at relay.c:829
(gdb) 
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
#1  0x00000000004074f6 in router_free_intern (clusters=0x1d66d90, routes=0x1d66ece)
    at router.c:239
#2  0x000000000040aa53 in router_free (rtr=rtr@entry=0x1d66d50) at router.c:2764
#3  0x00000000004039ba in do_reload () at relay.c:168
#4  handle_signal (sig=1) at relay.c:271
#5  main (argc=<optimized out>, argv=<optimized out>) at relay.c:829
(gdb) bt full
#0  router_free_intern (clusters=clusters@entry=0x0, routes=0x1d66f7e) at router.c:234
No locals.
#1  0x00000000004074f6 in router_free_intern (clusters=0x1d66d90, routes=0x1d66ece)
    at router.c:239
No locals.
#2  0x000000000040aa53 in router_free (rtr=rtr@entry=0x1d66d50) at router.c:2764
        s = <optimized out>
#3  0x00000000004039ba in do_reload () at relay.c:168
        newrtr = 0x1d66d50
        newaggrs = <optimized out>
        numaggregators = <optimized out>
        id = <optimized out>
        newfd = <optimized out>
#4  handle_signal (sig=1) at relay.c:271
        sign = <optimized out>
#5  main (argc=<optimized out>, argv=<optimized out>) at relay.c:829
        stream_sock = {3, 4, 7}
        stream_socklen = 3
        dgram_sock = {5, 6}
        dgram_socklen = 2
        id = <optimized out>
        listenport = <optimized out>
        listenbacklog = <optimized out>
        ch = <optimized out>
        numaggregators = 0
        listeninterface = <optimized out>
        allowed_chars = <optimized out>
        smode = <optimized out>
        pidfile = <optimized out>
        pidfile_handle = <optimized out>
        aggrs = <optimized out>
```

**Comment by grobian** [comment]
yes, this is different, I'll have a look shortly.

**Comment by grobian** [comment]
I think I got it
