### ISSUE TITLE
'include' directive doesn't care about rewrites

### ISSUE THREAD

**Issue by jensenja** [grobian/carbon-c-relay#240]
I have quite a few rewrite rules that I wanted to put in a different file to keep them from cluttering up the main config. The issue appears to be that the include directive doesn't care about rewrites. When I create a test config with additional `cluster` directives to use in the `include`, they are parsed as I would expect. Example:

carbon-c-relay.conf:

```
cluster default
    forward
        127.0.0.1:2003
    ;

#include carbon-c-rewrites.conf
#    ;

include carbon-c-test.conf
    ;

match *
    send to default
    ;
```

Running carbon-c-relay:

```
root@host:/usr/local/src/graphite/conf# /usr/local/src/graphite/bin/relay -f /usr/local/src/graphite/conf/carbon-c-relay.conf -p 2069 -t
[2016-12-18 19:49:13] starting carbon-c-relay v2.3 (5b1e04), pid=33623
configuration:
    relay hostname = host
    listen port = 2069
    workers = 16
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    statistics submission interval = 60s
    listen backlog = 32
    server connection IO timeout = 600ms
    routes configuration = /usr/local/src/graphite/conf/carbon-c-relay.conf

parsed configuration follows:
cluster default
    forward
        127.0.0.1:2003
    ;
cluster default-a
    forward
        127.0.0.1:2004
    ;
cluster default-b
    forward
        127.0.0.1:2005
    ;
cluster default-c
    forward
        127.0.0.1:2006
    ;
cluster default-d
    forward
        127.0.0.1:2007
    ;

match *
    send to default
    ;
```

When I comment out the test `include` and uncomment the `include` for the rewrites, they are not parsed:

```
root@host:/usr/local/src/graphite/conf# /usr/local/src/graphite/bin/relay -f /usr/local/src/graphite/conf/carbon-c-relay.conf -p 2069 -t
[2016-12-18 19:51:32] starting carbon-c-relay v2.3 (5b1e04), pid=33630
configuration:
    relay hostname = host
    listen port = 2069
    workers = 16
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    statistics submission interval = 60s
    listen backlog = 32
    server connection IO timeout = 600ms
    routes configuration = /usr/local/src/graphite/conf/carbon-c-relay.conf

parsed configuration follows:
cluster default
    forward
        127.0.0.1:2003
    ;

match *
    send to default
    ;
```

Also, I'm running this on debian servers that don't have `carbon-c-relay` in their repositories. Is the recommended way to install in this case just to `git clone` the master branch and build with `make`? Thanks.

**Comment by grobian** [comment]
Above fix seems to do the trick for me.  About Debian, I thought there was upstream support for it, but maybe that's only Ubuntu or newer Debian?  I'm not very familiar with the process there.

**Comment by jensenja** [comment]
It's possible that it's in the repositories for sid (unstable) but the servers are running jessie (latest stable) and it's not in the repos there.

Thank you for the fix - I'll rebuild from master and let you know!

Also, apologies, but one last question - does `carbon-c-relay` support reading updates to the config files in place, or is one supposed to modify the config files and then restart (assuming `kill -HUP?) the process? Thanks again!!!

**Comment by grobian** [comment]
any feedback on the fix is appreciated ;)

What do you mean with in place?  If you SIGHUP the process, it'll re-read the config and apply it if changes were found.

**Comment by jensenja** [comment]
Confirming the fix worked - thank you for the quick response!!!!

I guess I meant like certain Graphite configuration files, where if a change is detected in the file the configuration is applied immediately without needing to restart the process. But SIGHUP works just as well for me. Thanks again.

**Comment by grobian** [comment]
ah, I see.  No, the relay doesn't detect changes to its config file(s).
