### ISSUE TITLE
Set SO_LINGER to zero?

### ISSUE THREAD

**Issue by didip** [grobian/carbon-c-relay#243]
Hi all, I am back :)

I see that `carbon-c-relay` open and close connections all the time, should it then set `SO_LINGER` to zero when dispatching? to avoid a lot of connections in `TIME_WAIT` state?

**Comment by grobian** [comment]
It shouldn't really open/close all the time, but it can do that under certain circumstances yes.  Your suggestion makes sense, I'll look into it.

**Comment by grobian** [comment]
Hmmm, reading up on it, using SO_LINGER seems discouraged a lot.  Do you see TIME_WAIT problems on your server?

**Comment by didip** [comment]
I do see a lot of `TIME_WAIT` piling up on the server, which then followed up by a lot of `CLOSE_WAIT` (based on lsof).

This problem could be solved by setting kernel params:

```
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_tw_reuse=1
```

But some users may not have root privileges to the servers they are in.
