### ISSUE TITLE
AMQP as input source

### ISSUE THREAD

**Issue by mgrzybek** [grobian/carbon-c-relay#245]
The python-based Graphite service offers an input able to consume metrics from a MQ service. This approach can be very useful:
* in a DMZ environment. The secured area (where Graphite is) can connect against an insecured service (RabbitMQ);
* in order to make bursts smoother. The back-office won’t be overloaded as it consumes the messages as its own speed;
* in case of crash. If the back-office is unavailable, the buffering system won’t let you loose metrics.

For instance, the only reliable way to achieve this is using Logstash:
* rabbitmq input;
* complicated filter rules;
* graphite output.

**Comment by szibis** [comment]
You just define Telegraf.

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/rabbitmq

Support filtering, templates, aggregations and processing.

Support graphite output and many more features.

**Comment by mgrzybek** [comment]
It makes me think of collectd: an interesting monitoring tool. However there is no proper amqp consumer plugin.

**Comment by grobian** [comment]
In the current code, this would be possible to implement, as the readers can be stacked.  It would require a way to read AMQP/RabbitMQ and unpack it into graphite metrics.

**Comment by grobian** [comment]
I don't have time/resources to implement such new input source.
