### ISSUE TITLE
Using `stop` in a `match` rule does not stop metrics from being processed afterwards

### ISSUE THREAD

**Issue by poblahblahblah** [grobian/carbon-c-relay#246]
Hello,

We have a number of rules that look like this:
```
# sin_host_000-049
match ^sin\.foobar\.sin_1a_host0[0-4][0-9]\..+ send to graphite001:d stop;

# sin_host_050-099
match ^sin\.foobar\.sin_1a_host0[5-9][0-9]\..+ send to graphite005:c stop;
```

We also have a rule at the very end to catch metrics which we aren't specifically sending anywhere:
```
# push all the rest to graphite004:d
match * send to graphite004:d stop;
```

What I am seeing is that the `stop` in all of the rules is not being honored so we end up slamming our `graphite004:d` carbon-cache instance. For the ruleset labeled `sin_host_000-049` (and others) I have verified that carbon-c-relay is sending metrics to both `graphite001:d` and the default `graphite004:d`.

When we remove the default rule things go back to normal, as expected. carbon-cache's creates.log file created 25243 whisper files in a single minute at one point when we had this "default" backend in place.

edit: I forgot to mention OS and carbon-c-relay versions.

OS: Ubuntu 14.04 x86_64
carbon-c-relay: carbon-c-relay v2.5 (4616ad)

**Comment by poblahblahblah** [comment]
Interestingly enough, when I have a decent amount of match rules (69 match rules in the config) I see this behavior, but when I have very few rules (2) this does *not* happen.

**Comment by grobian** [comment]
this would be the optimiser kicking in and probably screwing it up

**Comment by grobian** [comment]
Got it, the optimiser wasn't the culprit, the group execution was.
