### ISSUE TITLE
Add program option to validate config and exit

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#247]
Currently can get the desired behaviour by running:
```
echo -n | ./relay -t -f routes.conf
```

But it would be more handy for the relay to have an option to exit success/failure immediately after parsing the config.

**Comment by grobian** [comment]
I actually always thought -t < /dev/null was supposed to be for this purpose.  IIRC some init scripts even use it before reload to chkconfig().

**Comment by grobian** [comment]
I think I got an idea, `-tt` might be easily possible to suppress any output but errors as well.
