### ISSUE TITLE
Dropping metrics

### ISSUE THREAD

**Issue by mgravlin** [grobian/carbon-c-relay#251]
We are using carbon-c-relay as a top level relay to send to a custom program written in Go that that processes, enhances and transforms metrics into other formats. We are seeing drops from carbon-c-relay for nearly 2/3 of the metrics sent to the custom program and zero drops to other carbon-c-relays and carbon-caches. I increased the queue size all the way to 1,000,000 without success, it basically delayed dropping metrics for a longer period of time while the queue was filling up. While we are working to improve the custom program, any additional insight or suggestions how to perhaps throttle, increase timeouts or the like sending metrics to a remote destination?

**Comment by Civil** [comment]
From my experience, you can use receiver code from https://github.com/lomik/carbon-clickhouse/tree/master/receiver or from https://github.com/lomik/go-carbon/tree/master/receiver - both of them have no problems talking with carbon-c-relay.

Carbon-c-relay usually have those kind of problems with slow receivers - your receiver should accept connection and read data as fast as possible - if you'll do heavy processing in the same goroutine, you have pretty high chances to see this kind of behavior.

**Comment by grobian** [comment]
It's hard to throttle for the relay without holding up who is sending to the relay ... one of the beliefs behind it is that one component not coping with the load shouldn't cause a slowdown (or meltdown) for the entire system.

**Comment by piotr1212** [comment]
Increase the buffer even more and set max stalls higher (-L 15). Defaults are quite low if you process high bursts of metrics. 

iirc I had to put the buffer on 10 million and -L 12 to be able to process a 20 million metric burst in 2 seconds to go-carbon.

**Comment by grobian** [comment]
I don't think there's much we can do here, except indeed experimenting with increasing the buffer, batch and stall sizes
