### ISSUE TITLE
3.x master branch doesn't match documentation on cumulative metrics

### ISSUE THREAD

**Issue by tehlers320** [grobian/carbon-c-relay#255]
`To obtain a more compatible set of values to carbon-cache.py, use the reset counters after interval clause to make values non-cumulative, that is, they will report the change compared to the previous value.`

However it looks like the stats by default are now behaving like carbon-cache.py in the latest build by default.

**Comment by grobian** [comment]
yes, stupid bug, above commit should fix it.
