### ISSUE TITLE
carbon-c-relay statistics name

### ISSUE THREAD

**Issue by nejec** [grobian/carbon-c-relay#256]
We are using carbon-c-relay v2.6 with following config (plain forwarding to two different carbon-cache.py instances).
```
cluster carbon_cluster
  forward
    192.168.1.94:2023
    192.168.1.85:2023
  ;

match *
  send to carbon_cluster
  stop
  ;

send statistics to carbon_cluster
  stop
  ;
```

As the docs say, `carbon-c-relay` will send out the statistics in format `carbon.relays.$hostname.*`, but in our case, we are just getting statistics in format `carbon_relays_$hostname.*`.

It is the same if we change `forward` to `carbon_ch`, or write a rewrite rule that would change `_` to `.`.

What are we doing wrong?

**Comment by grobian** [comment]
This may be related to issue #249, any chance I could have you try the git master version?

**Comment by grobian** [comment]
To make it more clear: I don't see anything wrong with your config, it seems fine.

**Comment by nejec** [comment]
I've tried `master` branch and it works in the expected way. When the new release will be available, we will use that one. Thank you.

**Comment by grobian** [comment]
I think I should release the master branch one of these days, thanks for testing!

**Comment by nejec** [comment]
great and thank you for you awesome `carbon-c-relay`!
