### ISSUE TITLE
match on negative lookahead regex failing

### ISSUE THREAD

**Issue by ra-dft** [grobian/carbon-c-relay#257]
Hello,

I'm in the processing of porting over my "blacklists" from carbon-cache to match+send to blackhole rules and currently carbon-c-relay won't start when I have the following rule in place:

> ^aerospike\.profiling\..+\..+\.service\.(?![batch_errors|batch_queue|client_connections|read_th.*|stat_proxy_errs|stat_proxy_reqs|stat_proxy_success|stat_read_reqs$|stat_read_success|stat_write_errs$|stat_write_reqs$|stat_write_success|storage.*|system_s.*|uptime|waiting.*|objects|record_locks]).+$

I know the regex is working for carbon-cache and I've checked it here https://regex101.com/ as well.

**Comment by grobian** [comment]
I have the impression that the problem may be in (?! ... ) sub.  See man -S7 regex, for the particular syntax in use.

**Comment by grobian** [comment]
(It is a feature request to switch to PCRE to get more regex features.)

**Comment by dgryski** [comment]
It's arguable that the move should be to move to re2 instead to avoid exponential behavior on certain matched.

**Comment by grobian** [comment]
indeed, preferably a less heavy-weight implementation (hence the usage of the libc-provided one)

**Comment by grobian** [comment]
v3.3 features support for external regex libraries like libpcre(2), and oniguruma, which should allow you to do these things.
