### ISSUE TITLE
whitespace in metric name... again

### ISSUE THREAD

**Issue by damienclaveau** [grobian/carbon-c-relay#258]
Hi,
Unlike https://github.com/grobian/carbon-c-relay/issues/228
in the case of a received metric like "my server name 99 1491575986",
I don't want to drop the metric, but I would prefer to replace the spaces (but not the last 2 spaces of course) with an underscore _ character, then apply rewrite rules.
Neither the "-c" launch parameter nor the rewrite rules like \s or [:space:] seem to do the trick,
because the current implementation processes space separators from left to right, right ?
How can I deal with that problem please ?

**Comment by grobian** [comment]
Currently it is impossible to deal with this.  Since rewrites only operate on the cleaned up metric part (= the block of chars from the start up to the first space) you won't have access to this to "fix it up".  Changing this would be challenging, and expensive.  Since this is a clear violation of the graphite line protocol, it seems to me the producer of this metric should be dealt with instead.

**Comment by damienclaveau** [comment]
Thank you. Given what I looked in the code, I was fearing such an answer.
The producer is a class in the Hadoop project that flattens a bunch of K/V pairs into the metric name https://github.com/apache/hadoop/blob/master/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/metrics2/sink/GraphiteSink.java#L81 without replacing forbidden characters.
It can take a while until it will be fixed.
Anyway, your project is still very useful. We are using it in production for several years with great success.

**Comment by grobian** [comment]
Thanks for the details.  It looks as if they write multiple metrics in one go (metrics 2.0?) format or something?  The loop with name=val confuses me, since they're appending to the same string all the time.

**Comment by randallt** [comment]
I deal with this issue too. We have some legacy Ganglia metric names with spaces, and Ganglia improperly emits them to Graphite with the spaces intact. How would it be more expensive to parse the metric line from right to left, tokenize on spaces, and join anything after the timestamp and value with an underscore as the metric name?
