### ISSUE TITLE
carbon-c-relay core dump when cluster config like '127.0.0.1:2003=1'

### ISSUE THREAD

**Issue by pengyusong** [grobian/carbon-c-relay#261]
cluster config as follows:
`cluster graphite  
      fnv1a_ch  
           127.0.0.1:2003=1  
           127.0.0.1:2003=2  
     ;  
`

core dump screen shot

>(graphite) [root@MONITOR_SERVER storage]# carbon-c-relay -f /etc/carbon-c-relay.conf 
[2017-04-20 16:33:39] starting carbon-c-relay v3.0 (2017-04-13), pid=6233
configuration:
    relay hostname = MONITOR_SERVER
    listen port = 2003
    workers = 6
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    listen backlog = 32
    server connection IO timeout = 600ms
    configuration = /etc/carbon-c-relay.conf

> /opt/carbon-c-relay/conf/cluster.conf:5:23:  syntax error, unexpected intval, expecting string
        127.0.0.1:2003=1
                       ^

> segment fault (core dumped)

**Comment by grobian** [comment]
That's odd, this is in a test and doesn't segfault on Darwin or Linux.  Is it possible to share your entire config?  Or is that bit you posted enough for you to trigger it?

**Comment by grobian** [comment]
ohhhh, this is v3.0 isn't it?

**Comment by grobian** [comment]
I can't reproduce the crash with v3.0 either, would you have a backtrace by chance?

**Comment by pengyusong** [comment]
Ummm, i install it in epel-testing repo. 
I just replace "1" to "a", it's strange, it should take "1" as string too.
I still close this issue, because it's not very important. But i think it should be fixed

**Comment by grobian** [comment]
yes indeed, in https://github.com/grobian/carbon-c-relay/commit/d9a6f4eaaa80920f455947b507692ac3254b6e1e I fixed this (which would be v3.1)
