### ISSUE TITLE
carbon_ch hash algorithm change between 2.5 and 3.0

### ISSUE THREAD

**Issue by Farfaday** [grobian/carbon-c-relay#264]
Hi,

We are running carbon-c-relay using the following docker container: https://hub.docker.com/r/bodsch/docker-carbon-c-relay/~/dockerfile/ with for now carbon-c-relay v2.5 (2017-01-14) with following cluster configuration:

```
  cluster local_cluster
    carbon_ch replication 1
        graphite-aaa.xxx.com:2003=a
        graphite-aab.xxx.com:2003=b
    ;
  cluster replication_cluster
    carbon_ch replication 1
        graphite-baa.xxx.com:2003=a
        graphite-bab.xxx.com:2003=b
    ;
    [...]     and finaly    [...]
    match *
    send to
        local_cluster
        replication_cluster
    stop
    ;
```

We have two cluster aa* and ba*, sharding their data over 2 nodes.
The data are not equally sharded in both clusters (so node aaa has not the same dataset of whisper files as node baa).
Maybe the letters defining each nodes(=a, =b) are not taken into account ??

Upgrading to 3.0 (with the same config, ip/dns/ports have not changed) leads to important changes in the routing of the metrics: we had to quickly rollback as the routing changes had created many new whisper files, filling up our drives. (per node, 16k additional new metrics to the 87k we have normally)

The only thing I found on that topic is this: https://github.com/grobian/carbon-c-relay/commit/2cf84998bdae633c38fd1b6e9b600ff47a98b383 but it is really
old and has been fixed a long time ago.

Did we misunderstood the concept of the carbon_ch hash algorithm ?

Many thanks for your time !

**Comment by grobian** [comment]
No, it seems to me you understood the concept very well.  I'll see to generating the hashmap with 2.5, this should stand out immediately in the tests I added around v3.0.

**Comment by grobian** [comment]
Hmmm, I see no change in the ring.  Would it be possible for you to run `relay -dtf <your-conf> < /dev/null >ring-vX.Y` for both X.Y=2.5 and 3.0?  Then diff both files, only differences in "hash ring for XXX follows:" blocks matter.

**Comment by Farfaday** [comment]
Hi !
Seems we have got something :) 

Our hosts have names in the form:       
     graphite-aaa.srv.intelliad.com:2003=a
     graphite-aab.srv.intelliad.com:2003=b

Version 2.5 prints something like that:
```
cluster replication_cluster
    carbon_ch replication 1
        graphite-baa.srv.intelliad.com:2003=a
        graphite-bab.srv.intelliad.com:2003=b
    ;
# hash ring for replication_cluster follows
  172@graphite-baa.srv.int   935@graphite-bab.srv.int   955@graphite-bab.srv.int
 1155@graphite-baa.srv.int  1465@graphite-bab.srv.int  2780@graphite-baa.srv.int

```
Seems that v2.5 doesn't like too many subdomains. Whereas version 3.0 resolves DNS to IPs and prints:
```
cluster replication_cluster
    carbon_ch replication 1
        10.128.0.54:2003=a
        10.128.0.55:2003=b
    ;
# hash ring for replication_cluster follows
  276@10.128.0.54:2003=a     537@10.128.0.55:2003=b     840@10.128.0.55:2003=b  
 1532@10.128.0.54:2003=a    1569@10.128.0.54:2003=a    1600@10.128.0.55:2003=b  
 1736@10.128.0.55:2003=b    1992@10.128.0.55:2003=b    2088@10.128.0.54:2003=a  
```
I attached both files.

[ring-v3.0.txt](https://github.com/grobian/carbon-c-relay/files/959633/ring-v3.0.txt)
[ring-v2.5.txt](https://github.com/grobian/carbon-c-relay/files/959634/ring-v2.5.txt)

Thanks for your help !

**Comment by grobian** [comment]
Ahhhh, that makes a huge difference in the ring distribution.  Explains why my testing didn't catch this, I can't rely on DNS resolution so I tested IP addresses only.

**Comment by Farfaday** [comment]
Hi,
I guess the easiest way to solve this is now to update carbon-c-relay to v3.0 and move the all the whisper data to their right place, using the carbonate toolbox. https://github.com/graphite-project/carbonate

How could I check if carbon-c-relay is now properly using the letter (=a, =b) before upgrading carbon-c-relay on my prod cluster ?

**Comment by grobian** [comment]
No, please don't.  This behaviour is a bug, I am working on the fix, and will release 3.1 shortly after.  The positions of metrics in your cluster shouldn't change!

**Comment by grobian** [comment]
This behaviour was fixed in commit 886bc471fc61f7c3be5a5eee28e781d892311843.  The latest master will work better in this scenario.  If possible, I'd appreciate if you could test latest master with the `-dtf` thing to compare the hash lists didn't change.

**Comment by Farfaday** [comment]
Hi, 
just tested latest master!
The diff between ring-latest.txt and ring-v2.5.txt is almost empty :) (just stuffs about statistics). The new file is attached. [ring-latest.txt](https://github.com/grobian/carbon-c-relay/files/963965/ring-latest.txt)

Thanks !

PS: If this is the normal behaviour, I did not understand why we then do not have the same metric repartition between node a and b for both clusters. Are the letters defining each nodes(=a, =b) taken into account or not?

**Comment by deniszh** [comment]
>Are the letters defining each nodes(=a, =b) taken into account or not?

They are, but hostname is taking to account too.

**Comment by grobian** [comment]
Thanks for testing, this looks good indeed.  @deniszh is correct, the host (name or ip) and instance together form the basis for the hash, so port is ignored for carbon_ch (and only carbon_ch).
