### ISSUE TITLE
UDP packet drops: enhance documentation

### ISSUE THREAD

**Issue by Farfaday** [grobian/carbon-c-relay#270]
Hi,
we were, until today having "holes" in our graphs: points were randomly dropped by the kernel due to the UDP receive socket being sometimes full.

Reading:
http://stackoverflow.com/questions/30933563/udp-receive-queue-full
http://stackoverflow.com/questions/16460261/linux-udp-max-size-of-receive-buffer
http://stackoverflow.com/questions/36466744/use-of-recv-q-and-send-q
and using following commands:
```
netstat -uanp 
netstat -us 
```
showed me that the Recv-Q column from **netstat -uanp** was most of the time not empty.
The output of **netstat -us | grep "receive errors"** was constantly increasing.

I had to set following values (for our usage/setup):
```
sysctl -w net.core.rmem_default=1703936
sysctl -w net.core.rmem_max=3407872
```
The output of **netstat -us | grep "receive errors"** is now a constant, and the holes in the graphs are now gone.

I tried to change those values using "-U bufsize" as written in the carbon-c-relay.md, but with no success. (always got a warning message that this was not possible).
I am also guessing, from that doc, that this may only applies to TCP sockets. (?)

So in fact I am just requesting here a small documentation update, so that other people having this sort of issue are informed :)

Thanks,
François

**Comment by grobian** [comment]
would you have a documentation update suggestion?

**Comment by piotr1212** [comment]
IMHO it might be better to add an option to set the UDP buffer size. Documenting that unreliable protocols are unreliable seems a bit redundant to me ;)

**Comment by grobian** [comment]
I wonder if is it possible to set this at all, if not run as root.  Feels like the OS needs to allow it.

**Comment by grobian** [comment]
The `-U` option sets the receive buffer size for both TCP and UDP connections.

**Comment by grobian** [comment]
I'm not sure what I can do about this.

**Comment by Farfaday** [comment]
Thanks for approving my PR :)
Seems to me that this issue can now be closed, but I let that up to you :)
