### ISSUE TITLE
Q: legacy carbon_ch cluster, rep 1, migrate to any_of, rep 2?

### ISSUE THREAD

**Issue by blysik** [grobian/carbon-c-relay#277]
Hi,

Got a question.  I have a 3 node carbon_ch cluster with a replication of 1.  I'd like to add 4 more nodes, and then switch to an "any_of" cluster, with a replication factor of 2.  (I want high availability for storing metrics, as well as retrieval.)

Is there anything I could do to spread out metrics beforehand?  Or should I just add the 4 nodes, change the config, and move forward.  Or any other consideration I should take?  Should I consider a hashing function instead of "any_of" ?

Thanks!

**Comment by grobian** [comment]
I think you definitely want to use fnv1a_ch or jump_fnv1a_ch cluster.  any_of won't give you any guarantees that values for metrics end up on the same nodes.

**Comment by blysik** [comment]
If I'm using carbonzipper, does that matter?  Since carbonzipper polls all servers.

**Comment by grobian** [comment]
carbonzipper will hide it, but it will be very inefficient, since a) carbonzipper needs to merge the maximum amount of files for every request and b) each metric is (partly) stored on all nodes so you waste a huge amount of diskspace.

**Comment by blysik** [comment]
Ah, ok.  That makes sense.  So then the question is: if I decide to use fnv1a_ch or jump_fnv1a_ch, is there a migration path I should take to go from 3 nodes, to 7 nodes?  Or should I just handwave that?
Thanks!

**Comment by azhiltsov** [comment]
Instead of replication factor 2 we choose to use replication factor 1 with multiple destinations on the carbon-c-relay. Together with jump_fnv1a_ch you will have exact and predictable matching between nodes, and in case of failure you will have to replicate data from one machine only.
Our config looks like:

cluster a
 jump_fnv1a_ch
  host1a
  host2a
;
cluster b
 jump_fnv1a_ch
  host1b
  host2b
;
match *
 send to 
  a
  b
;

If you will choose this way, then you may find handy the buckytools for reballancing and resyncronisation https://github.com/jjneely/buckytools which support this hashing algorithm but only for replication factor 1.
Migration may look like this:

Create new clusters,
point extra copy of metrics to it with carbon-c-relay,
perform back-filling of metrics with buckytools,
then point a zipper to the new clusters

**Comment by grobian** [comment]
That is indeed a very good approach if you have the number of machines to do it.

**Comment by dgryski** [comment]
@grobian Which we do ;)

**Comment by grobian** [comment]
Of course, but since the OP was about to extend a cluster from 3 to 5 iso build a new one from 5 and decommission the old 3 once migrated, I assumed this wasn't about a 200+ server cluster or something :)

**Comment by blysik** [comment]
I can go up to a total of 7 or 8 machines.  The old machines can still be used.  So I'm trying to figure out the best way to get there.  It sounds like two clusters of 4 machines each, might be best, and use @azhiltsov approach.

**Comment by grobian** [comment]
perhaps you can first start a new cluster of 4 in addition to the old one, then pull in all old data, and finally repurpose the old cluster +1 for the mirror cluster of 4.

**Comment by blysik** [comment]
Ok!

1. Set up 4 more machines for a new fnva1 cluster (B).
2. Use buckytools to take 3 machines carbon_ch cluster (A), and copy to cluster B.
3. Start writing to both clusters in parallel, until ensuring contents are equivalent.
4. Cut over to cluster B for read/writes
5. Re deploy old machines +1 into a new fnva1 cluster. (New A)
6. Start writing to both clusters now.
7. Use buckytools to get cluster B data syncd back to new A.

That sound about right?

**Comment by grobian** [comment]
yup, totally

**Comment by azhiltsov** [comment]
I would suggest the different approach @blysik .

1. Set up 4 more machines for a new fnva1 cluster (B).
2. Start writing to both clusters in parallel for day or so (depends how rare you are sending the rarest metrics) doing so you will have most of the metrics created on the disk with current data
3. Use buckytools to reballance cluster B by using extra machines from cluster A, with nodelete option
4. Cut over to cluster B for read/writes
5. Re deploy old machines +1 into a new fnva1 cluster. (New A)
6. Start writing to both clusters now.
7. Use buckytools to get cluster B data syncd back to new A (the same way as before).

Swapping 2 and 3 will eliminate a gaps in the whisper files between operations.

**Comment by grobian** [comment]
@blysik do you need more help/info for this issue?

**Comment by blysik** [comment]
This was great help, thanks!  Closing.
