### ISSUE TITLE
how to config c-relay open more than one output connection?

### ISSUE THREAD

**Issue by toopa2002** [grobian/carbon-c-relay#278]
Hi,
I have set up the environment as follow pic.
![blank diagram - page 1](https://cloud.githubusercontent.com/assets/14920157/26718922/d33d4d7e-47ac-11e7-8352-a8090746412d.jpeg)

The C-relay-ingestion has responsibility for forwarding metric data from client to load balancer in front of Graphite node as following config.
```
cluster send-through
forward
       graphite-vip:2003
;
match *
send-to send_through
stop;
```

With this setting C-relay-ingestion open only 1 connection to Graphite-vip. This make metric ingest to only one graphite node.  

I have try to use "fnv1a_ch" hash to open more connection to Graphite-VIP as below, but it make the error "cannot set instance 'a02' for server Graphite-VIP:2003: server was previously defined with instance 'a01'"
```
cluster hash
    fnv1a_ch
    Graphite-VIP:2003=a01
    Graphite-VIP:2003=a02
    Graphite-VIP:2003=a03
    Graphite-VIP:2003=a04
    ;
match *
  send to hash
  stop
  ;
```

Are there anyway set c-relay as a proxy to balance the load and open more than 1 connection to Graphite-VIP?

**Comment by grobian** [comment]
Each destination is a single connection, why do you want more than 1 connection? It shouldn't improve throughput in any way AFAICT.

**Comment by toopa2002** [comment]
Hi @grobian ,  In my case the destination of C-relay-Ingestion is loadbalancer (Graphite-VIP) and behind this loadbalancer are 12 graphite nodes.  I want metrics to be equally distributed from loadbalancer to 12 graphite nodes.  The problem I found at this time is the metric only send to 1 Graphite node and found many metric drop.

**Comment by piotr1212** [comment]
@toopa2002 Do you really need the loadbalancer? c-relay can load balance as well (see any_of) and is protocol aware (i.e. can buffer/resend/try to be consistent). IMO the loadbalancer just makes your design more complex and lowers the availability (more components in serial in the chain).

P.S. Not knowing your specific use case but you could probably drop the second relay on the cache hosts (c-relay-internal) as well. Or even not run relays at all on the cache hosts.

**Comment by grobian** [comment]
I also feel you should cut the loadbalancers out of the picture for the graphite traffic.  If possible, run carbon-c-relay in `-s` mode at the client machine to send metrics to your dedicated c-relay machines which directly send to all the carbon-caches.

**Comment by grobian** [comment]
@toopa2002 do you need more help/info/changes for this issue?

**Comment by toopa2002** [comment]
@grobian , thank you. I'm considering to remove LB from this picture as you recommend.
