### ISSUE TITLE
aggregate sum metrics experiencing gaps and not summing correctly

### ISSUE THREAD

**Issue by mwtzzz** [grobian/carbon-c-relay#280]
After making some changes to our environment, I'm seeing two issues; (a) aggregated sums start to experience gaps several hours after restarting carbon-relay; (b) aggregated sums are not summing correctly they are only about 25%-50% the value of what they should be.

The environment consists of a front-end UI cluster running httpd and memcached; a middle-layer cluster running carbon-c-relay; and a backend cluster running httpd, memcached, carbon-c-relay, and carbon-cache. 

The change I made was to replace the front end cluster with new hardware; and replace the middle layer relay cluster with new hardware; and to add a new backend cluster that is being sent a copy of metrics.

The non-aggregated metrics are fine. There is no problem with those. The problem is with the aggregated metrics which start to show gaps several hours after a restart of relay services.

The middle relay layer is virtually idle, there are no bottlenecks in CPU, nor disk i/o, nor memory.
The back end layer is busy, but is the same busy as it was before the changes were made.

The aggregation looks as follows:
in the middle layer:
`cluster backend1 fnv1a_ch host:port1=a ...;
cluster newbackend fnv1a_ch host:port1 .. ;
match ^agg\. send to backend1 newbackend;
match ^agg\. send to blackhole stop;
aggregate
    ^(.+)\.sum\.([^.]+)$
  every 60 seconds
  expire after 90 seconds
  timestamp at end of bucket
  compute sum write to agg.\1.sum_all.hosts
  ;
match * send to backend1 newbackend`

In the backend:
`cluster cache fnv1a_ch 127:0.0.1:2015=2105 ... ;
match * send to debug;
aggregate
    ^(us-east-1\.)?agg\.(.+)$
  every 60 seconds
  expire after 90 seconds
  timestamp at start of bucket
  compute sum write to \2
  ;
match ^agg\. send to blackhole stop;
match * send to cache stop;
`

Any thoughts on why it's experiencing gaps and not computing the sum correctly?

**Comment by mwtzzz** [comment]
It turns out the fix for this was to add more hosts to the relay cluster. Since the relay hosts were cpu idle, disk idle, and not memory constrained, this means there was a bottleneck somewhere in the network stack. 

when I had looked at the relay hosts during the problem, I had seen about 300 tcp established connections, which seemed ok. I don't know what other networking stuff to check on the linux side, or whether the bottleneck was in Amazon's network. 

In any event, in case other people run into a simliiar problem, our solution was to spread the network load out more by using more relay hosts. These are i3 instance types in EC2, which advertise a network performance of up to 10GB.

**Comment by grobian** [comment]
I'm not sure if you have stats about the machines, but you could perhaps plot a graph of the network usage.  If you reached the bandwidth limit (as you say you did) that should show up.  Also, the self stats of the relay could be interesting to check the metricsDropped counters.  An increase in these counters could give some hints about the problems.

**Comment by mwtzzz** [comment]
Looking at the relay hosts, I found a couple interesting things; first dmesg was showing "possible SYN flood", and secondly netstat -s was showing growing numbers for things like "packets pruned from receive queue because of socket buffer overrun" and "times the listen queue of a socket overflowed."

Researching what those things are, I found that it basically means packets are dropped because the application's tcp socket backlog queue was being filled up. Two things control the size of the socket backlog queue: (a) when the application calls listen(); and (b) /proc/sys/net/core/somaxconn and net.core.tcp_max_syn_backlog. If any of these has too low a value for the workload, packets will be dropped.

Our problem went away by adding hosts to the cluster, which spreads the load.
carbon-c-relay uses '-B' to set the size of the backlog queue. By default it is 32, so I wonder whether increasing this to something like 1028 would allow us to run the cluster with fewer hosts.

**Comment by grobian** [comment]
I think the -B option should help a bit here.  Also the -U option could help with things.  Both were introduced to cope with high load scenarios.

**Comment by mwtzzz** [comment]
Looking through relay.c, I see that SO_RCVBUF on sockets is set to 0. Is there a reason for this? This turns off buffering which means that if the application doesn't process every packet as it arrives then packets will get discarded. Wouldn't it better to set this to a value between the system's default and max? 
net.core.rmem_default=124928
net.core.rmem_max=16777216

**Comment by grobian** [comment]
ok, so does a recent version with these options suffice?

**Comment by mwtzzz** [comment]
Unfortunately (as I discuss in the other new issue I opened), the recent version is unusable due to a weird issue with CLOSE_WAIT states taking over and rendering the relay unresponsive. It's probably some weird thing in our environment, although I can't think of what.

**Comment by grobian** [comment]
Also, I think SO_RCVBUF is only set when the option is set, so the behaviour should be the same when the option isn't set.

**Comment by grobian** [comment]
This is a performance problem, if it isn't a network or cpu boundness.  I might have introduced some slight improvement on this point recently.
