### ISSUE TITLE
Q: using carbon_ch/fnva1_ch together with graphite's CARBONLINK_HOSTS

### ISSUE THREAD

**Issue by zdenekpizl** [grobian/carbon-c-relay#285]
Greetings,

 we are going to replace carbon-relay with carbon-C-relay in near future. As we use consistent hashing there has arose an question whether to use carbon_ch or fnva1_ch.

The carbon-relay is set up to shard data among multiple carbon-cacheprocesses running on multiple instances:

REPLICATION_FACTOR = 1
DESTINATIONS = carbon-cache01.int.companydomain:2004:0, carbon-cache01.int.companydomain:2014:1, carbon-cache01.int.companydomain:2024:2, carbon-cache02.int.companydomain:2004:0, carbon-cache02.int.companydomain:2014:1, carbon-cache02.int.companydomain:2024:2, carbon-cache03.int.companydomain:2004:0, carbon-cache03.int.companydomain:2014:1, carbon-cache03.int.companydomain:2024:2, carbon-cache04.int.companydomain:2004:0, carbon-cache04.int.companydomain:2014:1, carbon-cache04.int.companydomain:2024:2

Each carbon-cache is running graphite-web with settings like:

CARBONLINK_HOSTS = ["carbon-cache01.int.companydomain:7002:0", "carbon-cache01.int.companydomain:7012:1", "carbon-cache01.int.companydomain:7022:2"]

Question: We do need to keep the metrics distribution, so I suppose we will have to use carbon_ch method. Am I right?

Thank you, best regards .zp.

**Comment by deniszh** [comment]
Indeed, if you need to keep the metrics distribution, you will have to use carbon_ch method. Also please note that graphite cluster re-balancing tools (carbonate and buckytools) don't support `fnv1a_ch` at all.

**Comment by zdenekpizl** [comment]
Thank you, just to make it really clear - in case of non-compatible hashing method usage there will be more (at least two) occurrences of metrics' data file, right?

**Comment by deniszh** [comment]
More occurrences of metrics' data file, old files will stop updating, new files will have no old data, plus your cache will be effectively broken. IMO it's better to wipe all data then.

**Comment by azhiltsov** [comment]
May I ask you @zdenekpizl , why do you need to keep the metric distribution intact?
Is there technical or business decision behind that?

If you consider [carbonzipper](https://github.com/go-graphite/carbonzipper) and can afford doubling of consumed disk space during migration then you may try this flow:
1. set go-carbon on each carbon-cache host, replacing all carbon-cache by one go-carbon
2. configure carbonzipper to read from all go-carbon
3. configure graphite-web to talk to carbonzipper using CLUSTER_SERVERS
4. change carbon-relay to carbon-c-relay
5. change hashing from carbon_ch or jump_fnva1_ch (it give you equal distribution of metrics between machines)
6. rebalance cluster using buckytools.
7. consider carbonapi as an alternative rendering tool

**Comment by zdenekpizl** [comment]
Well, that's why I am asking actually. We keep nearly a year history of millions of metrics, so wiping data is 'no-go' probably. 

@azhiltsov That's an answer about the reasoning. But I would keep it as much intact as possible. Just replacing carbon-relay by carbon-c-relay and simplify data flow as now there are 3 layers of transport and it lacks  HA/Failover in fact too.

I have seen some feature in Carbon/Graphite being able to merge datapoints from multiple sources. Would it be applicable here?

**Comment by grobian** [comment]
I think the answers by @deniszh and @azhiltsov are the best we can do here.  Thanks!
