### ISSUE TITLE
very minor bug with "warning: OS rejected socket bufsize"

### ISSUE THREAD

**Issue by mwtzzz** [grobian/carbon-c-relay#287]
This bug is so minor, I really don't want to waste your time, but I figure I should mention it. 
It does not affect performance or functionality in any way.

This line in relay.c:
`if (sockbufsize != (unsigned int)val)`
should be changed to:
`if (sockbufsize != 2 * (unsigned int)val)`
as per socket(7):

```
              kernel doubles this value (to allow space for bookkeeping
              overhead) when it is set using setsockopt(2), and this doubled
              value is returned by getsockopt(2). 
```

and you might want to include the `sockbufsize` number in the warning message so that the user will be aware of which value was assigned.

**Comment by grobian** [comment]
I think I should change it to `sockbufsize > (unsigned int)val`, because the OS might align values or anything, the doubling may be Linux (kernel) specific

**Comment by grobian** [comment]
actually `<` to trigger an warning only when the set size is smaller than what was requested

**Comment by grobian** [comment]
I pushed a fix, thanks.

**Comment by mwtzzz** [comment]
Awesome, thanks!
