### ISSUE TITLE
Official Docker image for carbon-c-relay

### ISSUE THREAD

**Issue by ehlerst** [grobian/carbon-c-relay#290]
As more and more folks start using mesos/k8s it would be nice to be able to pull down an official carbon-c-relay docker image via automated build from dockerhub.

**Comment by grobian** [comment]
I have no idea how I'd even begin to create a docker image, or what it should provide.

**Comment by ehlerst** [comment]
I know how to create one, i think the official repo should provide the simplest possible container from which other projects can build from. There are already community carbon-c-relays on dockerhub with all sorts of features such as templates to write the config and so on. 

Ill give the merge a go during my off time if you like.

**Comment by grobian** [comment]
Any help would be much appreciated!

**Comment by ehlerst** [comment]
https://github.com/grobian/carbon-c-relay/pull/291

example use of this bare-bones container
`
sudo docker run -it -p 2003:2003 -p 2003:2003/udp -v $PWD/issues/issue94.conf:/etc/carbon-c-relay/carbon-c-relay.conf  ehlers320/carbon-c-relay '-p 2009'`

**Comment by grobian** [comment]
closing this for now, as I don't have the resources
