### ISSUE TITLE
Relay version 3.1 missing datapoints in it's metrics

### ISSUE THREAD

**Issue by deejay1** [grobian/carbon-c-relay#292]
Seems like the relay misses/duplicates some datapoints when sending it's statistics, which results in holes in the data. A quick tcpdump resulted in:
```
carbon.relays.relay_host.metricsDropped 38777423 1499944086
carbon.relays.relay_host.metricsDropped 38884789 1499944326
carbon.relays.relay_host.metricsDropped 39008357 1499944806
carbon.relays.relay_host.metricsDropped 39008357 1499944866
carbon.relays.relay_host.metricsDropped 39065223 1499945226
carbon.relays.relay_host.metricsDropped 39065223 1499945226
carbon.relays.relay_host.metricsDropped 39078790 1499945646
```

Stat configuration is standard:
```
cluster graphite_cluster
    forward
        graphite.example.com:2003 proto tcp
    ;

statistics
        send to graphite_cluster
        stop
    ;
```

**Comment by grobian** [comment]
that's really odd behaviour, sending doubly is very unexpected.

**Comment by grobian** [comment]
Is the relay reporting any connection issues?  The only reason I can think of now why this happens is if writing the metrics to the remote graphite server fails for some reason.

**Comment by deejay1** [comment]
During this time no connection errors were logged, it was straight from a tcpdump from the relay. One potential point we're investigating right now is bonding issues on the receiving hosts or something similar because we route the metrics back to the load balanced relay pool, which are then forwarded to two graphite clusters - one with fnv1a_ch replication (where we're seeing the gaps) and one "normal" which seems to be fine

**Comment by grobian** [comment]
closing this issue for now, please reopen if the problem persists
