### ISSUE TITLE
carbon-c-relay won't start if one of destinations in any_of in maintenance/redeploy

### ISSUE THREAD

**Issue by martin-ducar-gd** [grobian/carbon-c-relay#293]
I'm not sure if this is designed or just a bug but consider this scenario
1) We have a config file for carbon-c-relay with any_of cluster of nodes (currently 6 nodes)
2) This config is rather static as only solution I found to make the cluster dynamic is using DNS round robin or DNS of service discovery and have just one record in any_of cluster
3) At the same time we are doing maintenance/redeploy of one of the cluster nodes
4) Client is being deployed and carbon-c-relay is issued start
5) carbon-c-relay fails on the new client due to not all nodes in cluster having been up or having resolvable DNS with this message:
```
[2017-07-31 11:06:30] (MSG) starting carbon-c-relay v3.1 (2017-07-31), pid=27549
configuration:
    relay hostname = example-client1
    workers = 4
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    listen backlog = 32
    server connection IO timeout = 600ms
    extra allowed characters = -_:#^
    configuration = /etc/carbon-c-relay.conf

[2017-07-31 11:06:30] (ERR) failed to read configuration '/etc/carbon-c-relay.conf'
```

Is this designed behaviour? Because it looks there is already a code to detect these conditions when service is up but it would be nice to have the same during startup.
We have tried with version 3.1 and the latest master at the time of writing

**Comment by grobian** [comment]
can you share your (anonymised) configuration file?  This looks rather odd to me (and a bug).

**Comment by martin-ducar-gd** [comment]
here is the config
```
cluster internal_stats
  file
    /var/lib/carbon-c-relay.stats
  ;

match carbon.relays.*
  send to internal_stats
  ;

cluster test_issue293_proxies
  any_of
    server1.example.com:2003 server2.example.com:2003
  ;

match *
  send to test_issue293_proxies
  ;
```

And in /etc/sysconfig/carbon-c-relay
```
ARGS="-c '-_:#^' -p 2003 -w 4 -b 2500 -q 25000 -l /var/log/carbon-c-relay/carbon-c-relay.log"
```

**Comment by martin-ducar-gd** [comment]
Ensure that make server2.example.com is unresolvable, try to start the carbon-c-relay.

Expected behaviour:
carbon-c-relay starts but ignores that server

Actual behaviour:
carbon-c-relay can't start

**Comment by grobian** [comment]
Hmmm, I need to check if the error message comes out clean, but that behaviour isn't supported yet.  I can have a look and see if it would be possible to ignore a resolution error for this kind of cluster.  In principle it could be treated as a server that cannot be connected to, except we don't have an address.

**Comment by grobian** [comment]
I assume you'd want the relay to keep on trying to resolve the non-resolving address right?

**Comment by grobian** [comment]
Another question, currently when the relay has resolved an address and that address suddenly doesn't resolve any more, it sticks to the previously known address (the idea was failing resolution path or something not leading to a total drama).  However, would that be ok in your scenario?  Since the relay only re-resolves once it was "idle" or "interrupted" on that connection, a sudden resolv failure would only be noticed when traffic is low.

**Comment by martin-ducar-gd** [comment]
Yes ideally keep trying. Also using previous known address is fine in redeploy there should be new one and dns record modified, it would also meen the node was "interrupted" state. During some intermittent dns issue also keeping previous known address should be ok.

**Comment by grobian** [comment]
Ok, so it looks like it's relatively easy to add support for ignoring non-resolving addresses, and treating those as failed servers.  Regarding the keeping the addresses, I'm leaning towards removing that, such that removing a dns entry could shut down the metric flow.  I'm going to think about it a bit longer.

**Comment by zdenekpizl** [comment]
:+1:

**Comment by grobian** [comment]
I think cc7c0d0 implements the behaviour you're looking for.

**Comment by martin-ducar-gd** [comment]
@grobian great it works now, just one small nitpick in commit https://github.com/grobian/carbon-c-relay/commit/cfe6f6957e4ed2b0208d61ee8a7c237241a8c1c0 you forgot the newline at the end and now in log I can see:
```
[2017-07-31 14:38:04] (ERR) failed to resolve server2.example.com:2003, server unavailable[2017-07-31 14:38:04] (ERR) failed to resolve ...
```

**Comment by martin-ducar-gd** [comment]
sorry thats another err mesage I meant this one https://github.com/grobian/carbon-c-relay/blob/master/server.c#L253

**Comment by grobian** [comment]
good catch, will fix now, thanks!

**Comment by grobian** [comment]
if you create a PR for your test, I can merge it

Not entirely sure if we should always run it, since it will require a dns lookup, but having the test is a good thing.

**Comment by grobian** [comment]
This should be good now for the next release.
