### ISSUE TITLE
How queue size is intended to work?

### ISSUE THREAD

**Issue by zdenekpizl** [grobian/carbon-c-relay#297]
Greetings,

 we're using (among other options) "-b 2500 -q 25000 " options and we are observing longer delays until metrics are delivered to storage than before.

Does it means that carbon-c-relay somehow waits till its queue is fulfilled and only then it will start to forward data to defined upstream servers?

Thank you, best regards Zdenek Pizl

**Comment by grobian** [comment]
`-q` should just allow to absorb more metrics before it starts dropping them, it shouldn't affect delays or anything.  `-b` on the other hand is the 'batch' size, so the maximum amount of metrics that are sent in one go.  Depending on your application, large(r) batches can be good or bad for performance.

**Comment by zdenekpizl** [comment]
How often is batch of metrics send from queue to upstream (in our case it is carbon-relay)? According to code I undestand it will send number of metrics equal to min(batchsize, len(queue)). 

The question is whether sending larger batches using line protocol to original pythonic carbon-relay would help or would it be better to send smaller batches more often?

Thank you, you're doing such great job, with regards .zp.

**Comment by grobian** [comment]
the sending threads do small sleeps (<1s) when they have nothing to do, but other than that, as soon as there's something to send, they will try to send, so you only use the batchsize when the queue is filled enough.  I don't know how the python carbon-relay behaves wrt to this, the relay doesn't really close the connection or anything, it's more a lock optimisation inside carbon-c-relay than that it affects how data is written.  Perhaps you should experiment a little with it to see if it makes any difference.  I don't expect much.

**Comment by zdenekpizl** [comment]
Thank you for explanation. I will play with it little bit.

Regards, .zp.
