### ISSUE TITLE
v3.1 does not compile under FreeBSD

### ISSUE THREAD

**Issue by mallniya** [grobian/carbon-c-relay#299]
Hi,
while making FreeBSD port of carbon-c-relay I've faced the following problem:
```
server.c:398:31: error: use of undeclared identifier 'IPPROTO_TCP'
                                        if (setsockopt(self->fd, IPPROTO_TCP, TCP_NODELAY,
                                                                 ^
```
After googling this I figured out, that adding `#include <netinet/in.h>` in relay.c and server.c helps.
But next error was:
```
relay.c:492:12: warning: implicit declaration of function 'socket' is invalid in C99 [-Wimplicit-function-declaration]
                                sock = socket(PF_INET, SOCK_STREAM, 0);
                                       ^
```
and additional `#include <sys/socket.h>` to relay.c worked to finish the build.
Please consider this as a patch or precaution to use carbon-c-relay on FreeBSD.

**Comment by grobian** [comment]
I would appreciate it if you could test latest master, to see if any more includes are missing.  Thanks!

**Comment by mallniya** [comment]
Master and v.3.1 with ec45239 patch both compiles, thanks.
