### ISSUE TITLE
non alphanummeric metric names

### ISSUE THREAD

**Issue by z710x40** [grobian/carbon-c-relay#302]
L.S.
I don't know how they do it but someone is sending metrics with non alphanummeric characters. 

I see in the log of the carbon-cache the following errors:
15/08/2017 03:32:04 :: invalid line (▒▒Y▒OBkEpyeLjgFYWJnL9LKrSF8pUFEuG4▒▒▒▒▒▒▒▒▒▒▒▒̭▒▒▒▒▒▒▒|▒}̪▒▒▒▒▒▒▒~▒▒▒▒▒▒▒+▒▒▒,▒r▒▒s▒̩▒▒̬▒/▒0▒v▒▒w▒̨▒-▒.▒t▒▒u▒▒1▒2▒x▒▒y▒▒▒▒▒▒▒▒▒▒▒▒▒̫▒▒▒▒▒▒̮▒▒▒▒▒▒▒z▒{ce28D▒f▒▒▒▒▒39E▒▒
06B▒
▒17C▒▒:F▒▒▒     ▒) received from client 10.77.168.46:57476, ignoring
▒▒▒08/2017 03:32:04 :: invalid line (▒▒▒▒▒▒▒▒▒▒▒▒▒
   ▒
▒▒▒▒▒)&*'+(#"%!$ ▒▒▒▒ba`▒▒▒▒) received from client 10.77.168.46:57476, ignoring

Is there a way to prevent or filter this in the carbon-c-relay?
Erwin

**Comment by grobian** [comment]
yes, you can use the `validate` clause from `match`, e.g. to filter at a global level: (not tested)
```
match *
    validate "[a-zA-Z.]+ [0-9.e+-]+" else drop
;
```

**Comment by z710x40** [comment]
Great! Is there a reason why this is not filtered in the code itself?

**Comment by grobian** [comment]
On the one hand because of performance reasons, on the other because perhaps one wants to write stuff like json as data value, and the relay doesn't prohibit that this way.  As you observed, even binary fragments (as long as terminated by a newline) are preserved.

**Comment by grobian** [comment]
Above reply was regarding why the code doesn't filter it by itself.

What you see is not a metric name, because that one is sanitised.

**Comment by grobian** [comment]
I think you can use validate to filter the values, the metric is already sanitised with underscores.
