### ISSUE TITLE
gzip transport between relays does not seems to work

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#303]
build from e26c4c4
source config
```
listen
type linemode
  4003 proto tcp ;
cluster relays
  any_of 
  10.1.1.1:5003 proto tcp transport gzip
  10.1.1.2:5003 proto tcp transport gzip
   ;
match .*
  send to relays
  stop ;
```
destination config
```
listen
    type linemode transport gzip
    5003 proto tcp ;
cluster test
    jump_fnv1a_ch replication 1
        127.0.0.1:42003=000   ;
match .*
    send to test 
    stop;
```

Metrics seems to never leave the source host. It establish tcp connection only to the first server (10.1.1.1) in the list and tcpdump shows minimal activity. 
Replacing destination with 
```
nc -k -l 6003 | gunzip
```
does not work.

Replacing source relay with 
```
echo 'carbon.test 111 111' | gzip | nc 10.1.1.1 5003
```
works just fine
Seens receiving part is able to decompress , but sending is not. carbon-c-relay is compiled --with-gzip

**Comment by grobian** [comment]
eh, yes, you're a too early adoptor :)

I noticed the behaviour of the compression stuff here is annoying to say at least.

**Comment by grobian** [comment]
The gzip listener is much more useful now.
