### ISSUE TITLE
Build without gzip is broken

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#305]
[carbon-c-relay-95f2c57883d79e404170b5d06f2b72ae25c5b13e-build-log.txt](https://github.com/grobian/carbon-c-relay/files/1238454/carbon-c-relay-95f2c57883d79e404170b5d06f2b72ae25c5b13e-build-log.txt)
I have tried to build without compression  the 95f2c57883d79e404170b5d06f2b72ae25c5b13e but it fails.
--with-gzip builds fine

**Comment by grobian** [comment]
fixed this, plus extended travis to test some of these combinations
