### ISSUE TITLE
Process hang on ctrl+c with FUTEX_WAIT_PRIVATE

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#306]
Build from ac8b8ce with --with-gzip
Was running on the console over the weekend with config:
```
cluster local_submission_relay
    forward
        127.0.0.1:3002 type linemode    ;
statistics
    submit every 60 seconds
    send to local_submission_relay
    stop    ;
listen
    type linemode
    6003 proto tcp    ;
listen
    type linemode transport gzip
    5003 proto tcp
    5004 proto tcp    ;
cluster test
    jump_fnv1a_ch replication 1
        127.0.0.1:42003=000    ;
match .*
    send to
        test
    stop;
```
Once I hit ctrl+c it hanged with next messages in strace
`
$ strace -p 57295
Process 57295 attached
futex(0x6264ac, FUTEX_WAIT_PRIVATE, 96152, NULL) = 0
futex(0x6264ac, FUTEX_WAIT_PRIVATE, 96153, NULL^CProcess 57295 detached
`
gdb stack trace is attached
[carbon-c-relay-stack-ac8b8ce.txt](https://github.com/grobian/carbon-c-relay/files/1239130/carbon-c-relay-stack-ac8b8ce.txt)

**Comment by grobian** [comment]
If you're testing gzip, I think you want at least 95f2c57.  I don't think that will explain the hang though.

**Comment by azhiltsov** [comment]
It happened only once and it was heavily consuming CPU, I thought you might me interested in this. 
Of course I moved on to the latest commit since then.

**Comment by grobian** [comment]
Thanks for reporting.  I'm indeed interested in this.  I couldn't find a reason why from the stack trace though.  From your description it sounds like a loop that has no way out, which 95f2c57 could fix, but I'm not sure.

**Comment by grobian** [comment]
Since the code changed considerably, this bug is hard to track, if it is still there at all.  I've seen similar hangs caused by locked up servers.
