### ISSUE TITLE
Multiple gzip destination in the cluster but used only first.

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#307]
In configuration like
```
cluster graphite_server_relays
 any_of
  storerelay-1001:3003 transport gzip
  storerelay-1002:3003 transport gzip
  storerelay-1003:3003 transport gzip
  storerelay-1004:3003 transport gzip
  storerelay-1005:3003 transport gzip
;
```
only first relay is actually used, build from 95f2c57 --with-gzip

**Comment by grobian** [comment]
How did you test this?  With a load of distinct metrics?  `any_of` is hashing the input metrics, and relocates when servers become unavailable. You don't happen to see uncomplete writes, do you?

**Comment by azhiltsov** [comment]
I have put it under light load of 100 servers sending metrics and what I saw is only one connection was opened per cluster.
Connection diagram as following:
server(any_of 5 relays)-plain tcp->local_relay(any_of 5 relays)-gzip->store_relay(jump_hash many stores_I 
a local relay was opening only one connection to a store relay.
I will check this further tomorrow, as I was unable to reproduce this on the test bench.

**Comment by grobian** [comment]
the routing is unaware of the server type/transport, are you still seeing this behaviour?
