### ISSUE TITLE
Broken jump hash ring with 12 servers after migration to 3.1

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#310]
I have tried migrate the carbon-c-relay to 3.1 95f2c57 from 2.6 and faced the bug when hosts with ring positions 0 and 1 seems was excluded from the ring in all clusters.
We have the 4 clusters with config as follows:
cluster blabla-1
    jump_fnv1a_ch replication 1
        10.1.1.45:2003=9
        10.1.1.40:2003=11
        10.1.1.24:2003=8
        10.1.2.26:2003=2
        10.1.2.33:2003=1
        10.1.2.7:2003=5
        10.1.2.9:2003=6
        10.1.2.3:2003=3
        10.1.2.4:2003=4
        10.1.2.21:2003=7
        10.1.2.1:2003=0
        10.1.2.39:2003=10
Exclusion pattern is the same in all clusters.
Results of such bug immediatelly caused disk space exaustion. 
![image](https://user-images.githubusercontent.com/8709761/30170402-5a4c8fc6-93ef-11e7-90da-364cab6699a0.png)

**Comment by grobian** [comment]
the image you post is diskspace free, and hosts for key 0 and 1 are unaffected, e.g. all their metrics go to the rest, is that's what you're saying here?

**Comment by Civil** [comment]
It seemed so - for key0 and 1 everything was ok, but all other keys acted as there is no key0 and key1.

**Comment by grobian** [comment]
The list was sorted as string, so after 0 and 1, followed 10 and 11, which completely messed up the list ordering and hence output.  I've fixed this now.
