### ISSUE TITLE
Feature request: support graphite tags

### ISSUE THREAD

**Issue by xyntrix** [grobian/carbon-c-relay#311]
https://github.com/graphite-project/graphite-web/pull/2002

Tags support has been merged into Graphite.  It would be great if we could get tag support added to carbon-c-relay.  This should probably apply to all the core functions: routing, filtering, etc.

**Comment by grobian** [comment]
Just asking, would you want to route/filter based on tags?

**Comment by grobian** [comment]
https://github.com/graphite-project/carbon/pull/674

`<metric>;<tag1>=<value1>;<tag2>=<value2>`

I'm assuming this is followed by value and timestamp as before.

**Comment by grobian** [comment]
I have no clue if what I did makes sense, I'd appreciate some feedback.

**Comment by mmclanerh** [comment]
I apologize of the lack of input here.  Lots of changes in my personal life as of late. 

Filtering based on tags would be another depth of being able to route and direct metrics to different targets.

As an example:  foo.bar.count;env=prod vs foo.bar.count;env=dev ,      
- I might send all the env=prod metrics off to a cluster distinct from env=dev  (where say, env=dev has a retention period of 24 hours and prod has a default retention period of 90 days).

I might also want to use tags to help in the rewrite logic for a metric name or blackhole metrics that meet certain tag criteria..

My current focus has changed away from metric collection on a day to day, if I find some time I'll look at some testing of this and provide PR/feedback.  Thank you, very much, for looking into this -- I'm sure folks out in the community greatly appreciate it.   FWIW, current documentation on graphite tags can be found: http://graphite.readthedocs.io/en/latest/tags.html

**Comment by lfundaro** [comment]
Hi folks, any update on this or progress ?

**Comment by grobian** [comment]
Does this mean you want c-relay to inject tags based on an input metric?  It should be able to forward tags just fine as is right now.

**Comment by lfundaro** [comment]
Hi @grobian , mm no, I just need the relay to forward the tags. I see that release of version 3.3 now supports that so I will give it a try. Shouldn't this issue be closed then ? It's a bit confusing to read the thread an see no reference of a merged PR for this. Thank you !

**Comment by grobian** [comment]
https://github.com/grobian/carbon-c-relay/commit/be795894fedfb0cdf6dde9849bea2426755c948a

it wasn't a PR, I did it myself
