### ISSUE TITLE
SSL transport not working

### ISSUE THREAD

**Issue by bobapple** [grobian/carbon-c-relay#312]
I am trying to use the ssl transport to send metrics from one carbon-c-relay to another, however I am not able to get this working.

On the server side I have the following configuration:
```
[...]
listen
    type linemode transport ssl /root/relay.pem
        3003 proto tcp
    ;
[...]
```

This seems to work, with the `openssl` command I can connect and send metrics

```
root@localhost:/# openssl s_client -connect localhost:3003
CONNECTED(00000003)
depth=1 CN =  ...
verify return:1
depth=0 CN = ...
verify return:1

[...]

---
SSL handshake has read 1747 bytes and written 879 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated

    Start Time: 1505994293
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
test.metric 1505988774 123
```

If i try to send metrics from an "agent" carbon-c-relay, I get a meaningless error message.
This is my configuration on the agent side:

```
listen
    type linemode
        4003 proto tcp
    ;

cluster relay-server
    forward
        127.0.0.1:3003
            proto tcp
            transport ssl
    ;

match
    *
    send to relay-server
    stop
    ;
```

The error message I get:
```
[2017-09-21 13:41:58] listening on tcp4 0.0.0.0 port 4003
[2017-09-21 13:41:58] listening on tcp6 :: port 4003
[2017-09-21 13:41:58] starting 4 workers
[2017-09-21 13:41:58] starting statistics collector
[2017-09-21 13:41:58] starting servers
[2017-09-21 13:41:58] startup sequence complete
[2017-09-21 13:42:27] failed to write() to 127.0.0.1:3003: Success
```

Versions:
* carbon-c-relay: `v3.1 (e46092-dirty)`
* libssl-dev: `1.0.2g-1ubuntu4.8`
* Operatingsystem: `Ubuntu 16.04.03`

**Comment by grobian** [comment]
yeah, sorry, I'm still working on this bit

**Comment by postwait** [comment]
I think you need a function like:

const char *error_s = self->strmerror(self->strm);

For POSIX streams, make it return `strerror(errno);`, but for OpenSSL streams we need ask the library for the last SSL error on that connection.

**Comment by grobian** [comment]
Ah thanks.  I wrote the codepath quickly and didn't have the chance to figure out correctness yet.  I had my fun with the zlib part, and am currently trying to get the bzip2 part to work properly.  SSL will be next.

**Comment by postwait** [comment]
@grobian off topic, but I have a lot of experience using gzip and bzip2.  It is almost never worth bzip2, it's punishing on the compression side so much that it makes little sense for a transport encoding.
Gzip actually shares some of the same concerns though it is very popular.

I would consider using lz4f to do the compression -- you'll get "very good" compression while maintaining extremely competitive throughput.

**Comment by grobian** [comment]
Thank you!  I'm about to give up with bzip2, it's not sending the bzip header "BZh" and I'm done debugging the bzip code to see what I could possibly do wrong.  It feels they don't like me flushing the stream, which is essential to get some sort of timely delivery of metrics.
Now I'm thinking of it, a light-weight alternative against the relatively heavy beast that gzip is wouldn't be wrong at all.  Good thing I didn't make any release with bzip2 yet.  I'll drop it.

**Comment by dgryski** [comment]
Snappy or one one of the speedy LZ variants is probably the way to go.

**Comment by grobian** [comment]
Doing LZ4 now.  Don't like Snappy very much (sorry) because it assumes unaligned access is cheap and favours little-endian.  It just discriminates my powerpc and sparc machines :)  I guess we can add it on demand later though :)

**Comment by grobian** [comment]
How about the ssl support now? I merged PR #313 that ought to fix this.

**Comment by bobapple** [comment]
SSL transport is working for me now, thank you! 👍

**Comment by grobian** [comment]
nice, thanks for reporting back!
