### ISSUE TITLE
Add option to verify SSL with custom CA.crt

### ISSUE THREAD

**Issue by bobapple** [grobian/carbon-c-relay#314]
The SSL transport currently doesn't verify the certificates. It would be nice to set (optionally) a custom `CA.crt`.

This could look like this:
```
cluster relay-server
    forward
        127.0.0.1:2003
            proto tcp
            transport ssl /tmp/CA.crt
    ;
```

What do you think?

**Comment by grobian** [comment]
I think strict verification is a nice to have, I assumed an alternative CA can easily be added, but perhaps this isn't the case for all distros/setups.  I see a problem with this syntax if giving a CA is optional, which I think is certainly a valid use-case.

**Comment by grobian** [comment]
perhaps a commandline argument that sets either a CA cert via file, or disables verification (default behaviour, use system chains).

**Comment by grobian** [comment]
need to call SSL_CTX_load_verify_locations(ret->ctx, file, NULL); somewhere around 843 once I figured out how to best set the CA cert

**Comment by grobian** [comment]
SSL_set_verify(x, SSL_VERIFY_PEER, NULL) and SSL_get_verify_result(x)
