### ISSUE TITLE
Question about carbon_ch hashing and instance name

### ISSUE THREAD

**Issue by mmedal** [grobian/carbon-c-relay#317]
Hi Folks,

I wasn't able to find a discussion forum/gitter/slack for asking questions about carbon-c-relay, so I hope you don't mind me asking a question here :). Basically, I'm starting to cutover our aging graphite infra to use all the fantastic replacements you've defined here and I have a question about how the "instance" name comes into play for the hashing. Given a situation where upstreamRelayNode sends metrics to cacheNodeA and cacheNodeB, and I want to replace the relay instances on each host with carbon-c-relay, how do I retain the same metrics distribution? In other words, if I have the following as the configuration on upstreamRelayNode, do I still need to append the `=a` to the hosts to keep the same distribution if both cacheNodeA and cacheNodeB are also using carbon-c-relay?

    cluster graphite
    carbon_ch
        cacheNodeA:2013=a
        cacheNodeB:2013=a
    ;

Does carbon-c-relay even reference itself with letter-based instance names? Without ever diving into the specifics of carbon's hashing technique, I've never quite understood how the instance names are used. Thanks for all the great work!

**Comment by grobian** [comment]
Hi! No problem asking here, there's indeed no channels (I'm aware of).

Instance names are never communicated/verified on the wire, different instances on the same host just use different ports.  However, the carbon_ch hash takes the instance name into account, therefore, if you drop it, the hash distribution changes.
So, long story short, if you don't want the metrics to change distribution, you'll have to keep referring to the instance in your configuration.

**Comment by grobian** [comment]
assuming answered

**Comment by mmedal** [comment]
Yes, you have answered my question. Thanks very much for the response grobian!
