### ISSUE TITLE
Reload route config (handle aggregations)

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [grobian/carbon-c-relay#32]
I think it's good idea to have sort of "fast restart" ability - e.x. when you add new aggregates, there should be a way to perform "fast" reload of the rules.

**Comment by grobian** [comment]
first shot just pushed, but don't try to use this just yet, I needed a syncpoint :)

**Comment by jriguera** [comment]
Nice, this feature is perfect of confd + docker

**Comment by grobian** [comment]
so, I think what needs to be done here, is (apart from some testing) to handle aggregations.

**Comment by grobian** [comment]
I think I've finally tackled this!
