### ISSUE TITLE
Add support for transport gzip over ssl

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#323]
Currently, the relay config for listen and cluster only allows specifying one or the other, not both combined.

**Comment by grobian** [comment]
I knew this would be coming :)  But SSL uses gzip underneat, so it would make little (actually no) sense to apply both.

**Comment by iain-buclaw-sociomantic** [comment]
Haha.  Well when looking at tcpdump between two relays, the gzip packets were significantly smaller that the ssl (which in turn were significantly smaller than plain-text).

If SSL gzips, I wonder if its the difference between gzip+encrypt vs. encrypt+gzip.  The latter may not compress as well as the former I guess.

**Comment by iain-buclaw-sociomantic** [comment]
Actually, I partially retract from my previous statement.

I'm just monitoring sending data between two carbon-c-relays using production load (67K metrics per second), and these are the network bandwidth figures I'm seeing.

Transport | Bandwidth
------------ | -------------
plain-text | 4.1MB/s
ssl | 5.6MB/s
gzip | 325KB/s

I find it surprising that ssl adds that much overhead over plain-text, but I think it's pretty clear that this presents an argument for gzip+ssl.

**Comment by grobian** [comment]
https://stackoverflow.com/questions/2767211/can-you-use-gzip-over-ssl-and-connection-keep-alive-headers

maybe is interesting read here

**Comment by grobian** [comment]
FWIW I'm still puzzled, I would agree that gzip + ssl would make "sense", from your tests it shows clearly this isn't what's done now.

**Comment by grobian** [comment]
I gave this thing a spin, on "internet free moments" during my vacation, decided to push to ensure the work wouldn't get lost, but did minimal testing on this one.
