### ISSUE TITLE
cache filling up every 20 mins

### ISSUE THREAD

**Issue by pratikp09** [grobian/carbon-c-relay#324]
I am running a setup of 2 carbon relay nodes which forward to graphite. I happen to notice recently the cache is filling up super fast every 15 mins. Restarting the nodes help clean it but i am unable to find the root cause as to why this is filling up so fast. Any input will be appreciated.

**Comment by Civil** [comment]
I'd start with checking that your destination nodes can handle the load. Check the CPU and Net on the storage nodes. Have a look if there are any obvious errors there (like metric drops, connection failures, etc)

How many points per second you are doing?

**Comment by azhiltsov** [comment]
carbon-c-relay produces the metrics about itself health.
Health metrics usually starts with carbon.relay.
Look for metricsReceived, metricsSent, metricsDropped there.
Also destinations.$host:$port.metricsDropped could provide you some sort of visibility.
