### ISSUE TITLE
What is the procedure for changing rep factor from 1 to 2?

### ISSUE THREAD

**Issue by mwtzzz** [grobian/carbon-c-relay#325]
I'm a running a cluster with a graphite/whisper backend that has 13 hosts. The relay layer is currently set up for fvn1a_ch with a replication factor of 1. 

What would be the procedure to change this to rep factor 2? What impact will it have on the back end - will I need to add hosts? Will I need to use buckytools to rebalance the cluster after making the change?

**Comment by deniszh** [comment]
@mwtzzz 
>What would be the procedure to change this to rep factor 2? 

Just increase replication factor for corresponding cluster in relay's config and restart relay.

>What impact will it have on the back end - will I need to add hosts? 

Metrics will be reshuffled between hosts, so, hosts start to get approximately twice more metrics - so, more space (if you not using sparse whisper files) and load.

>Will I need to use buckytools to rebalance the cluster after making the change?

Unfortunately, buckytools not supporting replication factor > 1.
But If you using Graphite-web 0.9.16 or newer it will merge data from an old and new file, so, theoretically you can run it without rebalance, but again - it will cost you some extra disk space. You can also rebalance fnv1a cluster using latest [carbonate](https://github.com/graphite-project/carbonate)

**Comment by mwtzzz** [comment]
@deniszh Thanks for the info!

**Comment by grobian** [comment]
I might misunderstand, but if you change replication from 1 to 2, no metrics need to be moved, you just double the storage needs for your cluster, as each metric is now stored on 2 hosts instead of 1.  The position of the existing metrics is unchanged.

**Comment by deniszh** [comment]
Oh, @grobian probably right, my advice only valid if you want to change a number of hosts, together with increasing RF. Sorry, didn't realize that from start.

**Comment by mwtzzz** [comment]
ok thanks for the updated info.
another couple of questions:

- If i'm running a cluster with rep 2, and one of the hosts dies, will its replacement get a copy of all the historical data or just the new metrics that start coming in?

- how does the front end web UI know which of the replicated hosts to use for displaying data? (this kind of relates to the first question)

**Comment by deniszh** [comment]
> If i'm running a cluster with rep 2, and one of the hosts dies, will its replacement get a copy of all the historical data or just the new metrics that start coming in?

Just new. That's why having separate cluster with RF=1 is better - then you can copy data from another cluster with buckytools.

> how does the front end web UI know which of the replicated hosts to use for displaying data? 
It doesn't. It will ask all servers.

**Comment by mwtzzz** [comment]
ok, this means inconsistent results will be displayed - sometimes the new host will be queried and it will be missing the historical data. In this case, I assume carbonate can be used to rebalance the cluster thereby adding the historical data to the new host and making everything consistent?

**Comment by grobian** [comment]
Yes, and for exactly this reason, carbonzipper was created, so you always get the best view possible.

**Comment by deniszh** [comment]
>ok, this means inconsistent results will be displayed - sometimes the new host will be queried and it will be missing the historical data

Graphite 0.9.16 or newer will merge data together and fill the gaps. Or you can use carbonzipper, indeed.

**Comment by mwtzzz** [comment]
Will carbonate rebalance a rep 2 fnv1a_ch cluster and copy historical data to new hosts that don't have it?

**Comment by deniszh** [comment]
It should. I didn't try that, though.

**Comment by mwtzzz** [comment]
I'll try to test it. If you have a chance to test it too that would be helpful.
