### ISSUE TITLE
Question: Installation instructions for v3.3

### ISSUE THREAD

**Issue by JosephFY** [grobian/carbon-c-relay#328]
Hello
Is there a documentation for installation for version 3.3 ? I looked online and couldn't find any. 
I a upgrading from version 2,6 installed via yum before.

My box running Redhat 7.4
Thank you

**Comment by grobian** [comment]
You mean installation from source, when yum doesn't have an updated package yet?  You will need a compiler and development packages installed in order to be able to run ./configure and make.

**Comment by JosephFY** [comment]
@grobian Yea from source. I know there is no yum package anymore.
would you be list list a high level instructions steps of installations, and a list of requirement if there is any.

I am wondering why there isn't any rpm package in place, it would be a really good PR or at least an automated installation script. I may work on an installation script after I get the instructions. 

Appreciate the help on this.

**Comment by grobian** [comment]
Ok, the instructions should be pretty straight-forward, something like https://docs-old.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/Packagers_Guide/sect-Packagers_Guide-Creating_a_Basic_Spec_File.html

The idea is that you unpack the sources, run ./configure (it will tell you if it needs something, then you can add requirements from there) followed by make.  Finally you run make install to get everything installed, but this will most likely require root access, and you better do this from an RPM or something that keeps track of the installed files.

**Comment by JosephFY** [comment]
So as a start I tried to install the this package via rpm https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/c/carbon-c-relay-3.3-1.fc29.src.rpm

rpm only does extract these into a folder called `rpmbuild` into my home directory with 'SOURCE' and 'SPECS' in it. I am not trying to do any modification to the code as of now, I just need to install the daemon. Is the correct way other than to manually put the files under their correspondent locations (/etc, /etc/init.d .....) for each carbon-c-relay file or there is a better way to do so ?

don't have the much of experience of linux rpm installation. any help is really appreciated.

**Comment by grobian** [comment]
EPEL seems to have 3.2 available right now, I guess you could grab an rpm off of fedora too, that saves you the hassle of building etc.

**Comment by JosephFY** [comment]
I dont think so, it still showing this version only !
`[root@localhost tmp]# sudo yum --disablerepo="*" --enablerepo="epel" list available | grep 'carbon'`
carbon-c-relay.x86_64                       2.6-1.el7                       epel

**Comment by JosephFY** [comment]
@grobian 
Is there anyway we can get the mot recent version into EPEL ? it will really help people like me who are more interested in using and exploring the product. It is really a hassle to build as you said specially with all he requirements for rpmbuild.

**Comment by JosephFY** [comment]
So I was looking under the ordinary packages location where yum is pointed 
https://archive.fedoraproject.org/pub/epel/7/x86_64/Packages/c/

I should look under the **testing** packages location under
https://archive.fedoraproject.org/pub/epel/testing/7/x86_64/Packages/c/

I got it installed now.

So my last question before closing this thread  is that should I consider the rpm under the testing an official one ready for prod ?

**Comment by grobian** [comment]
As far as I understand, 3.3 has been created (you posted its link earlier), and now is in the progress of getting promoted up.  This takes a while, as normal distro stabilisation procedures take place.

**Comment by piotr1212** [comment]
and to use testing repo add "--enablerepo='epel-testing'" to your yum commands
