### ISSUE TITLE
Why there can be gaps in aggregate values?

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [grobian/carbon-c-relay#33]
Hi,

I'm trying to use carbon-c-relay and perform some aggregations. One of the rules is:
```
aggregate
        ^([^-]+)-[^.]+\.cacti_nginx\.cacti_nginx_sockets\.nginx_(requests|handled|accepts)
    every 30 seconds
    expire after 35 seconds
    compute sum write to
        aggregates.\1.nginx.sockets.\2
    compute sum write to
        aggregates.all.nginx.sockets.\2
    ;
```

Though there are some strange gaps (looks like 1 or 2 points are missing):
![strange_aggregates](https://cloud.githubusercontent.com/assets/8349709/5567827/94aecb3e-8f4c-11e4-9dcf-15804c84f15a.png)

I can't understand why there can be no data for aggregate but data for the points itself. Especially because data is obtained by collectd and they have actual time.

With format=json it looks like that:
```[20622.722064, 1419838410], [null, 1419838440], [21996.078082, 1419838470]```

```[18649.835853, 1419838410], [18739.188967999995, 1419838440], [19948.72801599999, 1419838470]```

**Comment by vladimir-smirnov-sociomantic** [comment]
For this particular example - less then 1k. There are another aggregates (with same problem, though it's less frequent) - they have approx. 50k events to be aggregated.

**Comment by vladimir-smirnov-sociomantic** [comment]
I've tested with increased expire (45s) - same problem - from time to time (2-3 times a day, always different time, sometimes different even for different metrics in one aggregate section) I've got a one-point gap in the graph.

**Comment by vladimir-smirnov-sociomantic** [comment]
I don't know why, but I can't reproduce the problem now. I've changed "server queue size" to 1M (it was 500k). Maybe that helped somehow.

**Comment by grobian** [comment]
If you look at the metrics for the aggregator/relay, how does it show queue size and dropped metrics? If increasing queue size helps, it feels like the aggregator has issues writing downstream.

**Comment by vladimir-smirnov-sociomantic** [comment]
I was running carbon-c-relay in debug mode, so I don't have those stats in graphite. Though I'm almost certain that downstream can handle this load.

**Comment by vladimir-smirnov-sociomantic** [comment]
Nope, seems to be just a coincidence.

Same problem still happens, but mostly during workday.

**Comment by vladimir-smirnov-sociomantic** [comment]
I've tried to increase number of workers (I was using 2 workers before) - now at least queue became smaller (200-300 events in queue), maybe it'll also help with the gaps.

**Comment by vladimir-smirnov-sociomantic** [comment]
And still sometimes it drops aggregation points, without any explanation in the error log (or stderr).

**Comment by grobian** [comment]
What is the CPU usage of the aggregator?  Your story seems to suggest you're cpu-bound, and the internal destination (carbon.relay.<host>.destinations.internal.dropped) isn't zero (and queued is very high).

**Comment by vladimir-smirnov-sociomantic** [comment]
LA is less than 5 during the day (on 8 cores server, in fact 4 cores + HT). For that particular cases - it was  a bit less than 3. So CPU usage (at least in terms of 30s intervals) was absolutely ok.

I'm graphing all the drops (max of all destinations, and sumaries) - and Max for internal is 0, though for aggregates it's getting higher in time (now it's 6 points, carbon-c-relay is running for 12h)

**Comment by vladimir-smirnov-sociomantic** [comment]
I've also tried to increase "server send batch" to 10k - and for me it seems that gaps happens less often now. Though it's still not clear for me how the carbon-c-relay works (I'm too lazy to find it myself, in fact), so I'm not sure that it really helped.

**Comment by vladimir-smirnov-sociomantic** [comment]
After setting batch to 10k - I've got no drops for 24h now.

**Comment by vladimir-smirnov-sociomantic** [comment]
And nope, I was wrong. Happend again.

Also strange thing about other metrics:
Whn it's happend, Queue was approx. 700 (avg is around 1.5k), LA on the server was 3, CPU stats - Idle around 670%, user - 70, system and softirq is also normal. For RAM usage - also nothing strange there.

**Comment by vladimir-smirnov-sociomantic** [comment]
And I've cheked again - the only "drops" there are "Aggregator drops"

**Comment by grobian** [comment]
aggregator drops, which mean any of the *.dropped metric isn't zero?

**Comment by vladimir-smirnov-sociomantic** [comment]
relay.aggregatos.metricDropped not zero, all other *dropped and *Dropped are zero. Though today it happend again, but ```sumSeries(carbon.relays.*.metricsDropped, carbon.relays.eu-60.*.metricsDropped, carbon.relays.*.*.dropped))``` was zero

**Comment by grobian** [comment]
aggregators.metricsDropped is increased when metrics enter the relay that are either too old (too late) or in the future.  If you see this metric non-zero, you may want to run in debug mode, as the relay will spit out a message if it sees metrics with a future timestamp.

**Comment by vladimir-smirnov-sociomantic** [comment]
It still doesn't explain why I've got gaps :) As I said, there are gaps (no values) from time to time. CPU Load, Disk Load - etc - is quite ok.

**Comment by grobian** [comment]
I don't understand the gaps, I've never seen this before, and we use it moderately :(

**Comment by vladimir-smirnov-sociomantic** [comment]
Yeah, I also can't understand why they are there. There is nothing wrong with the system at all and it's only aggregates what's affected.

**Comment by vladimir-smirnov-sociomantic** [comment]
Though problem still there... Is master stable enough to use in production (for some time, to see if that still happens with master, and maybe get some new stats from it)?

**Comment by grobian** [comment]
if you don't use aggregates and/or you don't try to reload the config, it should be ok.

**Comment by vladimir-smirnov-sociomantic** [comment]
Ok, I'll wait until aggregates will work.

**Comment by vladimir-smirnov-sociomantic** [comment]
Another strange thing about that. I've performed 4 restarts in short period of time and got 4 different messages in stderr:
shutting down internal:2003: waiting for 3069 metrics
shutting down internal:2003: waiting for 3069 metrics
shutting down 127.0.0.1:2105: waiting for 98 metrics
shutting down 127.0.0.1:2115: waiting for 100 metrics

It seems like there is some memory-related bug in carbon-c-relay that corrupts the memory. Or a race condition, that sets server's name in a wrong way.

**Comment by grobian** [comment]
why? it just reports on what servers it is still waiting before it can shut down.

**Comment by vladimir-smirnov-sociomantic** [comment]
M... Ok, maybe I've misunderstood that.

**Comment by vladimir-smirnov-sociomantic** [comment]
Btw, it's bad idea to write error messages (about dropped metrics) only in DEBUG. It's better to introduce "VERBOSE" level that'll print most of the messages, but still will send relay's stats to graphite.

https://github.com/grobian/carbon-c-relay/blob/master/aggregator.c#L225 also this "dropped++" - just a silent drop, maybe that's the cause in my case.

**Comment by grobian** [comment]
it should only write about dropped metrics in submission mode

it's unlikely rhat dropped++ is your case, for as I seem to remember, you said your data is never behind (it is on the spot), and you never saw droppedMetrics go up.

**Comment by vladimir-smirnov-sociomantic** [comment]
I'll try to reproduce that in some more clean testing environment. Though I won't be able to check in current environment anymore (cause I'm changing a company and they'll deal with all that stuff ;) )

**Comment by grobian** [comment]
not happy about this, but I'm inclined to close this ticket since we can't investigate any further

**Comment by grobian** [comment]
I've discovered a bug in the expiration logic, which I just fixed.  I'm not sure if it could cause this bug, but I'd imagine it would do expiry weird in certain scenarios (because there's randomness involved in almost every part of the relay)

**Comment by Civil** [comment]
Anyway, I think we can close that bug, cause I can't access that environment anymore. So I can't check if that fixed a bug. With some high expiration values, like 120-180s it was more or less ok.
