### ISSUE TITLE
Internal statistics can't be sent internal:2003: Bad address

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#335]
Disregards of configuration used I observe the next line in a log
carbon-c-relay[60082]: [2018-06-19 18:39:24] failed to write() to internal:2003: Bad address
and there is no internal statistics being send

one config:
```
statistics
 submit every 60 seconds
 prefix with carbon.relays.hostname
;
```
another config:
```
cluster submission-relay
    forward
        127.0.0.1:3002
    ;
statistics 
  submit every 60 seconds
  prefix with carbon.relays.hostname
  send to submission-relay
  stop 
  ;
```
Build from 03c378e95d159b6fd1ce0f25d9a4baf73638267c

**Comment by grobian** [comment]
2cf65bcbb10a1479f3e1d6df3bdeed6fab8299e0 is the culprit
