### ISSUE TITLE
Process killed OOM

### ISSUE THREAD

**Issue by lfundaro** [grobian/carbon-c-relay#337]
Hi ! 

We're getting an OOM error every 15 min on our relays. Some specs about our environment:

- carbon-c-relay version: `v3.3`
- OS: `ubuntu:14.04` (on docker)
- memory: `4096 MB`
- call: `/usr/local/src/carbon-c-relay/relay -d -f /usr/local/src/carbon-c-relay/conf/${CONFIG_FILE} -p ${PORT} -q ${QUEUE}`
- queue parameter (-q): `8000000`

relay config:

```
cluster my_atoms
  jump_fnv1a_ch replication 1
        atom-carbon-mirrora-v1-0.atom-carbon-mirrora-v1:2013
        atom-carbon-mirrora-v1-1.atom-carbon-mirrora-v1:2013
        atom-carbon-mirrora-v1-2.atom-carbon-mirrora-v1:2013
        atom-carbon-mirrora-v1-3.atom-carbon-mirrora-v1:2013
        atom-carbon-mirrora-v1-4.atom-carbon-mirrora-v1:2013
        atom-carbon-mirrora-v1-5.atom-carbon-mirrora-v1:2013
  ;

aggregate
        ^stats\.ingress\.([a-z-]+)\.gke-[a-z-]+-[0-9]-pool-[0-9]-[a-z0-9]{8}-[a-z0-9]{4}\.([^.]+)\.(res_[0-9]xx|req)
    every 60 seconds
    expire after 120 seconds
    compute sum write to
        stats.ingress.\1.gke-nodes-aggregated.\2.\3
    send to my_atoms
    stop
    ;
aggregate
        ^stats\.ingress\.([a-z-]+)\.gke-[a-z-]+-[0-9]-pool-[0-9]-[a-z0-9]{8}-[a-z0-9]{4}\.([^.]+)\.res_ms
    every 60 seconds
    expire after 120 seconds
    compute average write to
        stats.ingress.\1.gke-nodes-aggregated.\2.res_ms
    send to my_atoms
    stop
    ;

match ^booking-api\.(.*)booking-api-[a-z0-9]{8,10}-[a-z0-9]{4,5}\.bpc-aggregator\.[a-z0-9-]{36}\.(.*)
  send to blackhole
  stop
  ;

match *
  send to my_atoms
  stop
  ;
```

output from dmesg:

```
[1013774.605043] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[1013774.614003] [15424]     0 15424      257        1       4       2        0          -998 pause
[1013774.622929] [15558]     0 15558    13040     4215      30       3        0           933 supervisord
[1013774.632373] [ 9963]     0  9963   178420    12351      68      28        0           933 statsd /opt/sta
[1013774.642163] [26258]     0 26258  1384565  1101042    2203       8        0           933 relay
[1013774.651077] Memory cgroup out of memory: Kill process 26258 (relay) score 1923 or sacrifice child
[1013774.660400] Killed process 26258 (relay) total-vm:5538260kB, anon-rss:4401816kB, file-rss:2352kB
```

nothing unusual on the output debug log:

```
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.metricsSent 33773827 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.metricsQueued 8281996 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.metricStalls 0 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.metricsDropped 0 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.server_wallTime_us 2447545754 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.connections 114 1529758728
[2018-06-23 12:58:48] carbon.relays.molecule-relay-mirrora-v1-79c8f46b7c-s8bd8.disconnects 84 1529758728
```

from time to time I see some connection timeouts with the upstreams. 

We have been using carbon-c-relay version v3.3 since almost it's release and only a couple of weeks ago we started seeing a huge lost of metrics because of process crashes (sigkilled). 

I suspect we might be having a data-driven problem, e.g.: some malformed/corrupted metrics being sent to the relay creating memory leaks which eventually leads to OOM. But unfortunately I haven't been able to pinpoint the data problem yet. What's interesting is that we have in downstream a lot of carbon-c-relays with no rules and they don't crash. My hypothesis is that, if we are sending malformed metrics this relay crashes because it needs to parse them and do blackholing/aggregations possibly leading to memory leaks. I will try to run this relay without rules at all and observe its behavior. 

In the meantime, any ideas/input you may have about this. Should I provide more information ? 

Thanks in advance 😄

**Comment by lfundaro** [comment]
I disabled the rules and still get an OOM. 😞

**Comment by piotr1212** [comment]
Queue size is 8000000 per destination with 6 destinations means that 48000000 metrics can be queued. The size per metric is unknown, it depends on the metrics path, let's assume 50 bytes. Then you'll need already:
48000000×50÷(1024×1024) = 2288 MB of memory for just storing the metrics during bursts. If you have longer metric paths this will be more. Aren't you just a bit low on memory with 4 GB? Maybe there are metrics being sent with very long paths (eg with tags)? What if you lower the queue size, it should start dropping metrics but preventing the oom killer.

**Comment by lfundaro** [comment]
yes indeed, thanks for the valuable insight @piotr1212 . I bumped the queue to 2Mi, and after 10min started seeing massive amounts of metrics dropped and memory grew up to 3GB but stayed quite stable there. We do use tags and they are quite long ! Good catch there. I just bumped the memory and will monitor closely. I will wait a bit before closing the issue. Thank you !

**Comment by grobian** [comment]
Indeed, piotr1212 is right.  The relay doesn't crash, it gets killed.  It just needs more resources, you can limit the queuesize as most important metric.  Also, note that aggregations take space for each and every unique output metric (because it has to create buckets to count them), so the more variation in your input causing new output metrics, the more memory you need.

**Comment by lfundaro** [comment]
>Also, note that aggregations take space for each and every unique output metric (because it has to create buckets to count them), so the more variation in your input causing new output metrics, the more memory you need.

Yes indeeed, I was doing the calculations @piotr1212 did and the memory consumption didn't match quite exactly, I figured there's must be something else taking memory but didn't know exactly what. 

Good news is that after bumping memory up the process has been stable (no crash) for more than 15h now. I would consider this issue as resolved. 

Thank you very much for all your support guys !
