### ISSUE TITLE
Consistent-hashing problem

### ISSUE THREAD

**Issue by AlexAkulov** [grobian/carbon-c-relay#34]
Hello!

I have a problem witch consistent-hashing.
My cluster configuration:
node1 - haproxy and 3 carbon-relay in consistent-hashing, replication factor 2
node2, node3, node4 - carbon-relay and 4 carbon-cache on each.

When i try to use graphite-c-relay on node1 instead of 3 carbon-relays, i faced with the following problem: the way that graphite-c-relay sorts metrics differs from the way that the original graphite does it.

The order of nodes and replication factor in the config carbon-c-relay is the same as it was in carbon.conf. I`m ready to give some extra information.

carbon-c-relay.conf
```
cluster oldcluster
  carbon_ch replication 2
    mynode2:2013 proto tcp
    mynode3:2013 proto tcp
    mynode4:2013 proto tcp
  ;

match *
    send to oldcluster
    stop
    ;
```

carbon.conf
```
RELAY_METHOD = consistent-hashing
REPLICATION_FACTOR = 2
DESTINATIONS = mynode2:2014:1, mynode3:2014:2, mynode4:2014:3

[relay:1]
LINE_RECEIVER_PORT = 2103
PICKLE_RECEIVER_PORT = 2104

[relay:2]
LINE_RECEIVER_PORT = 2203
PICKLE_RECEIVER_PORT = 2204

[relay:3]
LINE_RECEIVER_PORT = 2303
PICKLE_RECEIVER_PORT = 2304
```

**Comment by pkittenis** [comment]
We had faced this same issue of migrating from carbon-relay to carbon-c-relay and finding that the hash destinations do not match - our solution was to modify [carbonate](https://github.com/jssjr/carbonate) to use carbon-c-relays' hashing algorithm and re-sync our cluster with it.

Carbonate code can be found [here](https://github.com/thomsonreuters/carbonate), in particular the release with carbon-c-relays' hashing algorithm is [0.2.23](https://github.com/thomsonreuters/carbonate/archive/0.2.23.tar.gz)

**Comment by filippog** [comment]
FWIW I'm going to tackle this problem by using two carbon-c-relay each serving a different function: a local relay on a non-standard port that fans out to local carbon-cache and serves as the only entry point for metrics into the machine. on top there's another carbon-c-relay listening on 2003/tcp which consistent-hashes to the local relays. Thus, each machine is a different (and a single) ip/port pair.
migrating from a setup that's using the instance numbers should be doable with stock carbonate too

HTH,
filippo

**Comment by grobian** [comment]
Ok, nice to hear.  I haven't got much time lately, and one of the other patches is progressing slowly, but I'll keep implementing this feature on the backlog.

**Comment by AlexAkulov** [comment]
I tried to change the code of carbon-c-relay. In consistent-hash.c I added instead None instance number in the function:
```snprintf (buf, sizeof (buf), "('% s', None):% d", server_ip (s), i);```
to debug the following line added
```fprintf (stdout, "('% s', '% d'):% d", server_ip (s), server_instance (s), i);```
Оutput after the run corresponds to my configuration (here: http://pastebin.com/Z1Rz2fca)
But all the same metrics are arranged not so much so it makes the original carbon
I noob in c and english. Sorry.

**Comment by grobian** [comment]
Nope, the right information to do this is missing, it needs to be parsed from the config, and stored/passed onto the hash construction.

**Comment by grobian** [comment]
I'm working on this.

**Comment by AlexAkulov** [comment]
This is very good news!

**Comment by grobian** [comment]
Testing appreciated
