### ISSUE TITLE
rewrite corrupts metric names

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#343]
relay works in submission mode and build out of 145f3f0
```
cluster upstream-relay
    any_of
      ip1
      ip2
      ip3
    ;
match *
    validate ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s[0-9.]+$ else drop
    send to upstream-relay
    ;
rewrite ^sys\.([A-Za-z0-9_-]+)\.mysql\.(.*)
    into mysql.monitoring.corporate.jiradb.no_cluster.host.live.clone_source.\1.ten_secondly.\2
    ;
match ^mysql\.monitoring\.
    validate ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s[0-9.]+$ else drop
    send to upstream-relay
    ;
```
periodically  metrics got corrupted in random places
instead of
mysql.monitoring.corporate.jiradb.no_cluster.host.live.clone_source.jiradb-1.ten_secondly.Com_release_savepoint
we are getting comething like
mysql.monitoring.corpopate.kizadb.no_cluster.host.live.clone_source.jiradb-1.ten_secondly.Com_release_savepoint

or like mysql.Monit_r_ng.

I can't reliably reproduce this,  but it does not affect original metric and corruption spotted only in plain text part of rewrite. I did not spot any corruptions in selectors like \1 or \2
Issue is reproducible on 2.6 release as well.

**Comment by azhiltsov** [comment]
The same issue was spotted on metrics which was not affected by set of rewrites (rewrites exist in the config, but none of them match affected metrics).
Issue mostly affects high-rate metrics (point every 10 second)

**Comment by grobian** [comment]
I know this is weird to ask, but are you sure the inbound metrics are uncorrupted?

**Comment by azhiltsov** [comment]
Good that you asked. 
We conducted throughout investigation and have noticed that even the issue is looking similar to what we saw many times before in the reality is something different. All affected metrics are having 'corporate' in their name but we did not spot any affected metrics coming from other environments. That lead us to the network issue. The metric corruption was looking as multi byte-flip. 
Lets say corporate.jiradb -> corpopate.kizadb
```
>>> bin(ord('p'))
'0b1110000'
>>> bin(ord('r'))
'0b1110010'
>>> bin(ord('k'))
'0b1101011'
>>> bin(ord('j'))
'0b1101010'
```
Since graphite line protocol does not have any error detection except TCP/IP checksumm/CRC which was not enough to guarantee validity. Issue was caused by broken switch-to-switch link and I am sorry for the noise here.

SSL+compression should prevent this from happening. 
One more question before we close this issue. If such issue will happen while ssl+compression is enabled would carbon-c-relay resend the discarded packets (remember that from TCP/IP point they were fine)?

**Comment by grobian** [comment]
Ok, phew, I'm happy this wasn't corruption in the engine ;)  Honestly, I'm impressed by your sk1llz to troubleshoot this one.

Now to the point of dealing with this.  If SSL impl detects the corrupted packages and re-sends them, it should be fine.  carbon-c-relay does not do re-transmission on its own, apart from failed writes, which it retries again.  They are, however, on the send() interface level, which is hidden away behind buffers etc. when one uses SSL or compression codecs.

**Comment by azhiltsov** [comment]
Thank you.
