### ISSUE TITLE
Reloading config  with queued metrics prevents relay metrics from being reported to graphite

### ISSUE THREAD

**Issue by rsheldon** [grobian/carbon-c-relay#348]
We use carbon-c-relay to send metrics to a 3rd party graphite provider. Sometimes we see the relay start queueing a lot of metrics, and we reload the config (with a kill -HUP) in order that it will stop taking new metrics (we have other relays in the pool), reconnect to the 3rd party and flush the queued metrics.

While this is happening we don't get any of the relay metrics sent out, so we can't see (in graphite) how many metrics are queued, sent etc. 

I could imagine that this is because it's possibly using the same pipe to send metrics as is sending the large queue of metrics, but it would be very useful be to be able to see these metrics as the queue is drained (eg perhaps using an separate connection to graphite)?

We're using carbon-c-relay 3.1.

**Comment by grobian** [comment]
This sounds like a bug, log messages migh give relevant info here.  Regarding using a separate channel for statistics, it would be easier perhaps to get them inserted at the front of the queue.  Still, if writing metrics somehow gets stuck, then this won't do much.  The relay is not supposed to block, so I would like to figure out why it does.

**Comment by grobian** [comment]
need more info here
