### ISSUE TITLE
timestamp of output of aggregator always lag behind

### ISSUE THREAD

**Issue by liyichao** [grobian/carbon-c-relay#35]
my config:

    interval 10
    expire 10
    method sum

every point represents 10s. Howerver, the output of aggregator is always 10s laging behind that computed via graphite's sumSeries function, which is anoiying.

**Comment by grobian** [comment]
Is it always 10s behind?  The aggregator takes the start of the bucket, but could also take the end of the bucket, or the middle of it.  Not sure what makes most sense.

**Comment by liyichao** [comment]
Yes, always.

**Comment by grobian** [comment]
Do you by chance use the original carbon-aggregator.py so you can tell me what that one did for your environment?

**Comment by liyichao** [comment]
No, I never use carbon-aggregator.py.

Let me describe what I thought about what the aggregator does. 

1. Get current time,`t`. Set a timer callback, which will be called at `t + interval`.
2. During the interval, aggregate according to the rules.
3. At `t + interval`，send aggregated metrics, all with timestamp `t`.

Alternatively, the aggregator may look at timestamp of metrics. It complicates things but keeps the original timestamp. I take a glance at the aggregator.c and it seems to work this way.

Maybe I should read `aggregator.c` and then I know why it lags.

**Comment by grobian** [comment]
what it does is it sends with timestamp t + interval (code is actually b->start + s->interval), I'm wondering if I should remove the "+ s->interval".  I think that is what you're expecting.

**Comment by deniszh** [comment]
Sorry for putting my 5cents, but IMO it's quite philosophical question - is it needs to be t, t + interval or t + 0,5 interval, or t+(random number [0..1] with normal distribution)*interval. Anyway, if it will be changed - it will break current behaviour for other users....

**Comment by grobian** [comment]
reason for using t + interval, is that it will make available results from the past, not pretend they are from the future

**Comment by liyichao** [comment]
@grobian: Think about this, all my points arrive at nearly the same time, namely, they all arrive at `b->start`. Then, if you emit record with timestamp `b->start + s->interval`. All aggregated data lags `s->interval`. 

In graphite, datapoints's timestamp is aligned to interval. For example, if interval is 10s, then datapoints will have timestamp like `1422411110`, `1422411120`. all datapoints with timestamp between `1422411110` to `1422411120` are saved with timestamp `1422411110`. This may provide an option to implement the aggregation.

**Comment by grobian** [comment]
so, if I would implement some feature that allows to specify if you want the time at start or end of the bucket, this would work for you, right?

**Comment by grobian** [comment]
or maybe even the middle :)

**Comment by tjamesturner** [comment]
while this is really just a labeling issue (are buckets labeled with their start or end date), i think the current behavior is inconsistent with both graphite and cyanite which label buckets using their start date. 

realistically, i think "fixing" this issue would simply require changing the aggregator_expire method in aggregator.c to remove the "+ s->interval" from each call of snprintf. though i can see the value in making the behavior configurable to allow a smooth transition for current carbon-c-relay users, i would suggest that the default should be consistent with graphite and cyanite (bucket start labelling).

**Comment by aaronm54** [comment]
@grobian Yes, I would like to vote for an option to switch to bucket start times.  Mainly to be consistent with other products like James pointed out.  Currently if my relay is configured to aggregate a metric and also send the raw metric on to something like cyanite, Cyanite will put the raw metric in one bucket and the aggregation of the metric will go into the following bucket.

**Comment by grobian** [comment]
Ok, I didn't know carbon took the start of the bucket.  Let's go for a config flag.

**Comment by grobian** [comment]
I added the optional   [timestamp at (start | middle | end) of bucket]  clause to the aggregator syntax.

**Comment by grobian** [comment]
Can you verify if this allows you to do what you need please?

**Comment by liyichao** [comment]
Yes.
