### ISSUE TITLE
fnva_ch and missing "=x" in cluster definition

### ISSUE THREAD

**Issue by ra-dft** [grobian/carbon-c-relay#355]
Is there a default fallback behaviour if the "=<x>" portion of a cluster definition is missing?
IE:
  fnv1a_ch replication 2
    172.26.2.26:2004 proto tcp
    172.26.2.22:2004 proto tcp
    172.26.2.27:2004 proto tcp

**Comment by grobian** [comment]
yes, then ip and port are used as hashkey

**Comment by ra-dft** [comment]
So that being said, if we had added the tag "=x" on the end, IP changes would not have impact on the distribution of whisper files in our cluster?

**Comment by grobian** [comment]
Correct, I thought I had an example about that, apparently not.  For fnv1a_ch, `=` acts as a full key override, thus allowing you to disconnect from IP/port addresses.

**Comment by ra-dft** [comment]
I believe this was what I read as well, but that was some time ago and just needed to make sure I understood the algorithm in my own words.
Thank you.
