### ISSUE TITLE
Carbon cache rejecting certain relayed metrics

### ISSUE THREAD

**Issue by zenmetsu** [grobian/carbon-c-relay#356]
This may be invalid, however I ran into an issue after switching to carbon-c-relay where certain metrics are being ignored by the carbon-cache cluster.
These rejected metrics appear to be percentages and times reported in 'ms'

stats.hostnameredacted.memory.used_memory_peak_perc 99.07% 1549753441
stats.hostnameredacted.cassandra.system_auth.read_latency 2.0396666666666667 ms 1549753438

I'm guessing that the extra space before the milliseconds and the % are causing the problem.  I suspect that these values should be unitless, but I did not run into an issue with the previous carbon-relay that I was using.  

Is there something I can try doing to resolve this issue?

**Comment by grobian** [comment]
Indeed, the metrics are wrongly formulated.  I wonder what carbon-relay did with these.  Were the metrics ever visible?

Anyway, I don't think there's much c-relay can do here at the moment, except dropping the metrics using the validate construct.

**Comment by zenmetsu** [comment]
Thanks. I will have to rewrite my checks to sanitize this.  i was hoping i could use the rewrite rules to fix, but it seems that this only affects the metric name and not the value.  Is that correct, or did I do something incorrectly?

I'll go ahead and close this since the issue appears to rest elsewhere.

**Comment by grobian** [comment]
Indeed, carbon-c-relay cannot rewrite values at the moment.  Since it can validate, it is probably possible to also perform rewrites on the values, but this would require some effort.  Closing for now, feel free to re-open if you feel this is necessary.
