### ISSUE TITLE
-S option still in advertised options at command line

### ISSUE THREAD

**Issue by digimago** [grobian/carbon-c-relay#358]
Since the introduction of configurable statistics in the configuration file the -S option does not get parsed anymore and the relay fails to start should this option be submitted on the command line.
The -S option has subsequently been removed from the README.md but still appears in the options list for the executable when the executable is run without options. So the executable advertises an option that will actually prevent it from starting.

https://github.com/grobian/carbon-c-relay/blob/62db68d57702f53b2761e19ef6f2ee3c97ae4715/relay.c#L402

**Comment by grobian** [comment]
dunno what went wrong, `-S` was indeed removed in 3.2

**Comment by digimago** [comment]
would you like me to file a pull request or will you fix it yourself?

**Comment by grobian** [comment]
I'm pushing in a second after I confirmed I didn't break any tests
