### ISSUE TITLE
Question on stall mechanim

### ISSUE THREAD

**Issue by alespour** [grobian/carbon-c-relay#360]
I am sorry I was unable to find out details on stalling mechanism. The doc says "when a queue fills up, the relay uses a mechanism called stalling to signal the client (writing to the relay) of this event". How does it signal the client - it sends a message over the connection the client uses to write metrics to the relay? I have a client that pushes a lot of metrics and I get a lot of them dropped. I'd be happy to pause the client when it gets stall notification from the relay. Thank you.

**Comment by grobian** [comment]
The docu is somewhat misleading here.  There is no actual message sent, the only thing that's done, is that the relay stops processing data from the client for a brief period (250-1000ms).  This should manifest itself on the writing end as a blocked write.  After this block, the metrics are dropped.  You can increase maxstalls (-L) and have a look at the stalls metric.  There is a possibility that multiple workers quickly end up re-trying to send (increasing the stall count), therefore rendering the stall time kind of useless (as they hit maxstalls).

**Comment by alespour** [comment]
Thank you. "After this block, the metrics are dropped." - metrics that already in a queue are dropped? Or what metrics are dropped?

**Comment by grobian** [comment]
The queue has a certain size, when the queue is full, it first tries to reject additions to the queue, this is what is called a stall.  If the stall exceeds some conditions (time, retries) the item at the front of the queue is dropped, and the new item is added.  Thus, drops are done only when strictly necessary, the queue is never flushed as result of input pressure.

**Comment by grobian** [comment]
Based on the above, you can now see why increasing the queuesize might help (create more space to fill), or why increasing batch-size might help (if batch sending improves sending speed, then the queue is drained faster).

**Comment by alespour** [comment]
I guess increased queue size could hep with burst, but if I have continuous flood of metrics that a set of carbon-cache instances are not able to process faster than they are received by the relay, I will have metrics drops, right?
There is really no way to configure the relay to just stop reading incoming data until queues are drained and thus have clients blocked in write()?

**Comment by grobian** [comment]
Correct, at the moment the relay is really hard-wired to never block a writer for too long.
