### ISSUE TITLE
Question --  hash key fnv1a_ch

### ISSUE THREAD

**Issue by patrickclee0207** [grobian/carbon-c-relay#365]
is there a way to find out what the hash key comes out to be for something like this..
cluster go_carbon
  fnv1a_ch replication 2
    11.111.111.11
    22.222.222.22
    33.333.333.33

so since the port and hashkey wasn't provided before. wondering if i could somehow change my config to put the hashkey in there without changing how things are hashed currently.

**Comment by grobian** [comment]
have you tried running your config with `-t`?

e.g.:
```
% carbon-c-relay -t -f myconfig
...
cluster go_carbon
    fnv1a_ch replication 2
        11.111.111.11:2003
        22.222.222.22:2003
        33.333.333.33:2003
    ;


match *
    send to go_carbon
    ;

foo.bar
match
    * -> foo.bar
    fnv1a_ch(go_carbon)
        11.111.111.11:2003
        22.222.222.22:2003
```

**Comment by grobian** [comment]
if you want to change IP and keep the same key (I think that's what you're asking) then it's probably best to change the keys to the old IPs, e.g.:
```
cluster go_carbon
    fnv1a_ch replication 2
        11.111.111.12:2003=11.111.111.11
        22.222.222.23:2003=22.222.222.22
        33.333.333.33:2003
    ;

match *
    send to go_carbon
    ;

foo.bar
match
    * -> foo.bar
    fnv1a_ch(go_carbon)
        11.111.111.12:2003
        22.222.222.23:2003
```

**Comment by grobian** [comment]
assuming question has been answered
