### ISSUE TITLE
Installing after configure --program-prefix=something install ill-named man page

### ISSUE THREAD

**Issue by Nelstaar** [grobian/carbon-c-relay#372]
Hi,
I want to install binary with name carbon-c-relay so I configure with 
`configure --program-prefix='carbon-c-'`
But `make install` install _usr/local/bin/carbon-c-relay_ which is correct but also _usr/local/share/man/man1/carbon-c-carbon-c-relay.1_

regards.

**Comment by grobian** [comment]
make sense, thanks

**Comment by Nelstaar** [comment]
FYI I fixed with this patch [program-prefix.patch.txt](https://github.com/grobian/carbon-c-relay/files/3451503/program-prefix.patch.txt)

And re-running 
```
aclocal && autoconf && automake
./configure --program-prefix='carbon-c-'
make man
make
```
regards.
