### ISSUE TITLE
Unable to start carbon-c-relay service with SSL transport enabled

### ISSUE THREAD

**Issue by favrecr** [grobian/carbon-c-relay#373]
Hello folks,

We are trying to setup carbon-c-relay with this configuration file:
```
cluster local
  forward
    127.0.0.1:2003
      proto tcp
      type linemode transport ssl
  ;
```
However when restarting the service we get this error:
/etc/carbon-c-relay.conf:9:30: feature ssl not compiled in

Our version is 
carbon-c-relay v3.3 (2018-07-31)

Any pointers would be appreciated.

**Comment by grobian** [comment]
The message is pretty much clear, I think: `feature ssl not compiled in`.  You'll need to run `./configure --with-ssl` and if that cannot find openssl/libressl it will die with an error.

**Comment by favrecr** [comment]
Fixed by compiling it correctly
