### ISSUE TITLE
Why not C++?

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [grobian/carbon-c-relay#39]
From a quick reading, it seems for me, that migrating to C++ will make code more natural, like "dispatcher.c" or queue looks like OOP in C. If migrate code to C++ (using only small subset of it, e.g. classes, maybe some new atomic primitives), it'll make code more readable without any performance penalties.

**Comment by grobian** [comment]
C++ is slow and a compiler nightmare.  There is no point in migrating from where I'm standing.

**Comment by vladimir-smirnov-sociomantic** [comment]
Ok. I've just saw that queue and dispatcher looks very similar to a classes from C++ and that's why I've asked. My point is still that if you'll use only classes, you won't have noticeable (if you'll have any) performance penalty but you'll get better readability. Though I'll try to make some tests to get a proof about the performance.

**Comment by grobian** [comment]
I think C++ is unreadable and messy.  Also, this project is really small, so no need for complex methods.  However if you have plans to extend the software, you can always fork and go your own way.  The code is given to the community for people to benefit from it in one way or another.
