### ISSUE TITLE
Autotools scripts out of sync

### ISSUE THREAD

**Issue by Nelstaar** [grobian/carbon-c-relay#391]
When build from source I get the following errors:
`Makefile:501: recipe for target 'aclocal.m4' failed`
I workaround with
```
mkdir m4
autoreconf --force --install
```
and it worked.
So I made a pull request where generated file are remove and where _autogen.sh_ build them locally.
[pull request #390](https://github.com/grobian/carbon-c-relay/pull/390)

**Comment by grobian** [comment]
git doesn't store timestamps, which is likely the problem this happens.  You can use --disable-maintainer-mode, like travis does, to ignore this.  There is a reason to include all generated files, that is to not require all build tools and their exact versions to obtain the tested/desired behaviour.

**Comment by Nelstaar** [comment]
Indeed I checked without touching any file and it build.
