### ISSUE TITLE
Some possible errors reported by static analyzer (clang)

### ISSUE THREAD

**Issue by Civil** [grobian/carbon-c-relay#40]
I've ran clang's scan-build (using my branch see the PR for simple-logging from my working account with fixes for clang):
```CC="clang" scan-build -o analyze make -j4```

Then I've opened report (it's an html with all code flow described there) and saw some errors that I think worth reporting here:
```

Bug Group	Bug Type ▾	File	Function/Method	Line	Path Length	
Dead store	Dead assignment	router.c	router_optimise	1231	1	View Report
Dead store	Dead assignment	collector.c	collector_runner	187	1	View Report
Logic error	Dereference of null pointer	consistent-hash.c	ch_get_nodes	238	11	View Report
Logic error	Dereference of null pointer	consistent-hash.c	ch_addnode	179	12	View Report
Logic error	Dereference of null pointer	router.c	router_route_intern	1538	14	View Report
Memory Error	Memory leak	relay.c	main	302	36	View Report
Memory Error	Memory leak	router.c	router_readconfig	747	54	View Report
Logic error	Result of operation is garbage or undefined	aggregator.c	aggregator_putmetric	223	15	View Report
Logic error	Result of operation is garbage or undefined	aggregator.c	aggregator_putmetric	242	19	View Report
```

Memory leaks are not that bad - it's a corner cases for binding and parsing file - not all malloced variables are freed, but program is terminated (in router_readconfig i- you allocate w, but if encounter 'unexpected end of file' you don't free it, in relay.c -you allocate workers, but you won't free it if you'll fail to bind to socket).

About two null-pointer dereferences in consistent-hash:
1. ch_get_nodes: If w is NULL and replcnt is 0, then you'll get null pointer dereference on string ```ret[i].dest = w->server;```. I don't know if it really can happen not as a result of poorly crafted config, but still.
2.  ch_addnode: same thing as before, if ```ring->entries != NULL``, but either w is NULL or ```ring->hash_replicas``` is less than 0, you'll get null pointer derefrence at line 179 (in my fork), string is ```last->next = w```, cause last will be NULL and you are checking only if w is not null. Again, I think ring->hash_replicas should never be 0, but there maybe conditions where its possible. 

Maybe all are false-positives, but it's better if you'll have a look at the output of clang's analyzer.

At least it's right about "dead assignments" on https://github.com/grobian/carbon-c-relay/blob/master/router.c#L1231 - you set rwalk to 'bwalk->firstroute' in "then" statement, and emediately after rewrites it to 'bwalk->lastroute' on line 1235. And same thing about https://github.com/grobian/carbon-c-relay/blob/master/collector.c#L187 - it's just useless, cause it will never be read.

**Comment by grobian** [comment]
The compiler complains about NULL when ring->entries is.  replcnt has nothing to do with it (if 0, it will never execute the loop).  I've added an assert to help the compiler.
