### ISSUE TITLE
Aggregation for count of matching metric series

### ISSUE THREAD

**Issue by matthew-hollick** [grobian/carbon-c-relay#404]
Hi,
Is there a way to create a metric for the count of unique metric series seen in a bucket period?

ie
if I have 100 servers each sending servers.<server_name>.uptime I want to create the metric servers.count with an expected value of 100.

**Comment by grobian** [comment]
I think `count` is doing that for you

**Comment by matthew-hollick** [comment]
Thank you,
Will check it out
