### ISSUE TITLE
dual-ssl and large-ssl tests fail on ubuntu 16.04

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#415]
Tests all pass on v3.6 and v3.7, but these two fail on v3.7.1

That makes bisecting easy (there's only been one code change between the two releases https://github.com/grobian/carbon-c-relay/commit/a50ae144bdbab7212351501fff757c513750f45b)

Looks like there's even CI for ubuntu 16.04, and it's also failing with the same problem.
https://travis-ci.org/github/grobian/carbon-c-relay/jobs/705083939

Reproducible in a container:
```
docker run -it --rm ubuntu:xenial bash

apt-get update && apt-get install -y \
  autoconf build-essential libtool git libonig-dev libssl-dev zlib1g-dev \
  pkg-config liblz4-tool help2man;
git clone https://github.com/grobian/carbon-c-relay;
pushd carbon-c-relay;
autoreconf;
./configure;
make -j8;
make test -j8;
```

**Comment by iain-buclaw-sociomantic** [comment]
The tests do not fail on ubuntu 18.04 (Bionic), so the change triggered something specific to Xenial.  This can be checked by using the same reproducer as above, but starting a container with the `ubuntu:bionic` image instead.

**Comment by grobian** [comment]
Ok, I thought this was a travis issue, since it didn't occur on other platforms.

**Comment by iain-buclaw-sociomantic** [comment]
> Ok, I thought this was a travis issue, since it didn't occur on other platforms.

I think you need to have more faith in your CI. :-)

Would it be useful to expand the testing currently done?  I see that travis now supports 18.04 as well now, along with other architectures (arm64, ppc64le, s390x).
