### ISSUE TITLE
Deduplication of inbound metrics

### ISSUE THREAD

**Issue by obfuscurity** [grobian/carbon-c-relay#417]
Does carbon-c-relay include any features that would support normalization/deduplication of multiple inbound metrics streams? We are looking for a relay that could accept multiple inbound feeds, but then only fanout a single normalized stream (to address potential metric gaps in any one of the upstream emitters).

**Comment by grobian** [comment]
currently not, this would require buffering (like aggregations), but it is an interesting use-case.
