### ISSUE TITLE
parameter -m N is not working for some metrics

### ISSUE THREAD

**Issue by xor-eax-ebx** [grobian/carbon-c-relay#425]
sometimes -m N is not working, for very very long metric names

how to reproduce:
- config value: -m 500
- metric length > ~8KB (i.e. invalid metrics from statsd glued together due to UDP packet size limit)

carbon-c-relay does not delete such invalid metrics, but forwards them

probably end of buffer (without newline characters) is omitted here: 
https://github.com/grobian/carbon-c-relay/blob/master/dispatcher.c#L914-L922

**Comment by grobian** [comment]
Is this the full metric, or a part of it that gets forwarded?  I can imagine somehow that the end of a metric is seen, with its values.

**Comment by xor-eax-ebx** [comment]
full metric with value & timestamp

**Comment by grobian** [comment]
ok, that should be easy to test

**Comment by grobian** [comment]
I tried this:
```
printf "x%01000d 1 2\n" 1 > longmetric.tst
nc localhost 2003 < longmetric.tst 
```
using a conf like this one ```
cluster out
    file ip
        /dev/stdout
    ;   
match *
    send to out
    ;
```

and it prints the metric by default, but it drops it when using `-m500` here.

I increased the size to 10K but it still does not show the metric getting through.  I repeated the 10K 15 times to get a large(r) block and still I could not reproduce this behaviour.

If you have a reproducer, please share.
