### ISSUE TITLE
Internal metrics reported by carbon-c-relay seems to be wrong

### ISSUE THREAD

**Issue by ervikrant06** [grobian/carbon-c-relay#427]
Plotting internal metrics of carbon-c-relay and go-carbon.. Pictures are showing stacked output. carbon-c-relay it showing total number of received metrics to be 1.5B but the total number of metrics reported by go-carbon is approx 5-6M I believe go-carbon reporting correct state. 

Carbon-c-relay stat 

![image](https://user-images.githubusercontent.com/6498699/103437830-38dd7980-4c52-11eb-99f2-18ec82d1b2b2.png)
`
go-carbon stat

![image](https://user-images.githubusercontent.com/6498699/103437868-a093c480-4c52-11eb-9c74-55b4ffa96a81.png)

Some info about setup:

Whole setup is running in K8s 
- Three POD of carbon-c-relay running.  Each of the backend of carbon-c-relay is a K8s service. Each K8s service has 3 go-carbon PODs running on same node that means 9 go-carbon PODs spread across 3 nodes. 

~~~
cluster graphite
        fnv1a_ch
                cache-testsvc-1:2003
                cache-testsvc-2:2003
                cache-testsvc-3:2003
    ;
listen
        type linemode
                2003 proto tcp
   ;
match
    *
    send to graphite
  ;
~~~

**Comment by grobian** [comment]
you need to use nonNegativeDerivative with c-relay's stats

**Comment by ervikrant06** [comment]
Thanks. It worked.
