### ISSUE TITLE
support for 0 expire in aggregator

### ISSUE THREAD

**Issue by liyichao** [grobian/carbon-c-relay#43]
Currently we can not use 0 in expire, thus the output from aggregator lags behind that computed by graphite functions (sum, avg..), which is annoying.

**Comment by grobian** [comment]
An aggregation is performed over a time window.  Only when that window is over, you can expire it.

**Comment by liyichao** [comment]
I wonder why there are two parameters, namely interval and expire, when only one is needed.

When you talk about `time window`, you mean interval. My question is, when interval is over, why we still need to wait for `expire` before we send the metrics out?

**Comment by grobian** [comment]
That's because some events may arrive with a delay.  With expire, you basically set how long events may be delayed before they will be discarded.

**Comment by grobian** [comment]
setting expire == interval would remove any delay possible, as soon as the interval bucket is filled, it is expired

**Comment by liyichao** [comment]
Actually, my config is 

interval 10
expire 10
method sum

see https://github.com/grobian/carbon-c-relay/issues/35.
