### ISSUE TITLE
aggregate: Expire splay should be configurable

### ISSUE THREAD

**Issue by gpiucco** [grobian/carbon-c-relay#435]
If you have high every/expire values, the aggregator will wait too long before producing metrics.

This is because the random splay added is based on the bucket size.

For example, this could take up to 600 seconds before producing metrics:
```
aggregate ^foo\..+\.bar$
  every 300 seconds
  expire after 301 seconds
    compute sum write to foo.bar
  send to main
  stop
  ;
```

In most setups, a few seconds of splay should already be enough to avoid the "thundering herd of expirations" problem.
A simple solution would be to make the value configurable.

**Comment by grobian** [comment]
I can see your point, 600 seems too long with this config indeed

**Comment by grobian** [comment]
how about we just limit the splay to a few seconds instead of anywhere on its interval?
