### ISSUE TITLE
Dockerfile: add bison flex dependency for latest build

### ISSUE THREAD

**Issue by flucrezia** [grobian/carbon-c-relay#449]
Updating the `apk add` line in the Dockerfile as follows:

`RUN \
  apk add --no-cache flex bison git bc build-base curl automake autoconf libtool && \
  ./configure && make
`

the build is again successful. 

Thanks,
Francesco

**Comment by grobian** [comment]
I'm not against something like this but I wonder if this should be necessary, the idea is to have pre-created copies in the git repo to avoid having the need for certain (versions of) buildtools.

**Comment by flucrezia** [comment]
Running the command:
`docker build -t grobian/carbon-c-relay .`
I'm getting the following on my Dell laptop with Ubuntu 20.04. Instead on a virtual machine with also Ubuntu 20.04 it builds smoothly...Strange.

```
...
bison -d conffile.y
make[1]: bison: No such file or directory
make[1]: *** [Makefile:1138: conffile.tab.h] Error 127
make[1]: Leaving directory '/opt/carbon-c-relay-build'
make: *** [Makefile:469: all] Error 2
The command '/bin/sh -c apk add --no-cache git bc build-base curl automake autoconf libtool &&   ./configure && make 
returned a non-zero code: 2```

**Comment by grobian** [comment]
I managed to do the docker build thing successfully with the changes I just pushed, please let me know if this is also fixing the problem for you

**Comment by flucrezia** [comment]
Yes it fixed the build on my laptop, thanks!
