### ISSUE TITLE
Do not prefix stats

### ISSUE THREAD

**Issue by ssko1** [grobian/carbon-c-relay#451]
Is there a way to disable prefixing with the statistics construct?

When I created my own `statistics` construct, I expected it to override the default configuration provided by carbon-c-relay.

```
# my relay.conf
statistics
    submit every 10 seconds
    send to forwarder
    stop
    ;
```

But I end up with the configuration on boot

```
# printed configuration on startup
statistics
    submit every 10 seconds
    prefix with carbon.relays.myhostname
    send to forwarder
    stop
    ;
```

**Comment by grobian** [comment]
Hey, not sure if this works, but have you tried `prefix with ""`?

**Comment by ssko1** [comment]
I did try! Quotes result in an error
```
[2022-10-12 18:55:29] relay.conf:13:17: empty string
[2022-10-12 18:55:29]     prefix with ""
```

**Comment by ssko1** [comment]
Is there any insight as to why `.` would work? A simple test shows the following internal stats
```
.dispatcher1.metricsReceived 0 1665602450
.dispatcher1.metricsBlackholed 0 1665602450
.dispatcher1.metricsDiscarded 0 1665602450
.dispatcher1.wallTime_us 7 1665602450
```

I'm leaning a bit more into the rewrite option, but haven't tested it out yet

**Comment by grobian** [comment]
I had hoped that the metrics would be sanitised, hence the `.`.  I think with current code, you can't do it other than with a rewrite rule.  If that is too limited, I'll have to add some syntax to allow you to have no prefix.

**Comment by grobian** [comment]
Nope, this should do it just fine.

**Comment by ssko1** [comment]
Thanks for your help! I appreciate the feedback and quick response.
