### ISSUE TITLE
Segfault on CentOS

### ISSUE THREAD

**Issue by stevebanik** [grobian/carbon-c-relay#46]
Under high load, carbon-c-relay sometimes dies and the kernel ring buffer reports:

relay[12386] general protection ip:3ee520798e sp:7fc14c4bde00 error:0 in libpthread-2.12.so[3ee5200000+17000]
relay[29214]: segfault at b983c6a8 ip 0000000000409027 sp 00007fa3b983bcb0 error 4 in relay[400000+e000]

on CentOS release 6.3 (Final) 2.6.32-279.5.2.el6.x86_64.  I'd be happy to provide more information as needed.

**Comment by grobian** [comment]
Hmmm, a backtrace would certainly help here, if possible.

What is high load for you?  How does your config look like?

**Comment by stevebanik** [comment]
The relay process occasionally spiked to ~400%CPU.  Config is as follows:

cluster graphite3
        fnv1a_ch
        127.0.0.1:2103 
        127.0.0.1:2203 
        127.0.0.1:2303 
        127.0.0.1:2403 
        127.0.0.1:2503 
        127.0.0.1:2603 
        127.0.0.1:2703 
        127.0.0.1:2803 
        127.0.0.1:2903 
        127.0.0.1:3003 
        127.0.0.1:3103 
        127.0.0.1:3203 
        127.0.0.1:3303 
        127.0.0.1:3403 
        127.0.0.1:3503 
        127.0.0.1:3603 ;

cluster graphite2
        fnv1a_ch
        192.168.200.34:2103 
        192.168.200.34:2203 
        192.168.200.34:2303 
        192.168.200.34:2403 
        192.168.200.34:2503 
        192.168.200.34:2603 
        192.168.200.34:2703 
        192.168.200.34:2803 
        192.168.200.34:2903 
        192.168.200.34:3003 
        192.168.200.34:3103 
        192.168.200.34:3203 
        192.168.200.34:3303 
        192.168.200.34:3403 
        192.168.200.34:3503 
        192.168.200.34:3603 ;

match *
        send to graphite3 ;
match *
        send to graphite2 ;

How can I get a backtrace for you?  Also, I'm not sure if I can currently duplicate the problem because we eliminated a lot of inbound metrics, so load has backed off quite a bit since then and the process has not segfaulted since.

**Comment by grobian** [comment]
for a backtrace, compile with:
make CFLAGS="-g -pipe"
Then run manually in gdb:
gdb --args ./relay -f yourconf
when it crashes type
thread apply all bt

**Comment by grobian** [comment]
Can you tell me what version you use(d)?  If this is about a git version (e.g. not a release) it may not be a surprise at all.  Yet the backtrace would still be useful.

**Comment by stevebanik** [comment]
carbon-c-relay v0.36 (46d3a9)

I haven't been able to get it to segfault since I made some changes to the machine (improved disk throughput via RAID5, eliminated some unnecessary carbon-cache settings, etc.)

**Comment by grobian** [comment]
I have no idea on how to fix this.  The only thing I have left to ask you is you mention 400% cpu usage, on what system was that?  How many CPUs did it have?  Was there plenty of memory available?

**Comment by stevebanik** [comment]
It's a single machine with 24 cores and 96GB RAM.  It hasn't segfaulted since 1/27.  I'm not able to provide any additional useful information on it, so I'll go ahead and close this issue.
