### ISSUE TITLE
rewrite metric names to lowercase

### ISSUE THREAD

**Issue by pschuermann** [grobian/carbon-c-relay#48]
Is it possible to use the rewrite rule to convert all metric names to lowercase?

**Comment by grobian** [comment]
Not at this time.  Would have to implement a syntax hack to perform that change, e.g. something like \_1

**Comment by pschuermann** [comment]
that would be beneficial. We got some metric collectors where we just can't influence the namespace. It results in an ugly mix of uppercase lowercase metrics which are harder to target with wildcards.

**Comment by grobian** [comment]
```
rewrite ^a\.([^.]+)\.
    into newa.\1.
    ;
rewrite ^b\.([^.]+)\.
    into newa.\_1.
    ;
rewrite ^c\.([^.]+)\.
    into newa.\^1.
    ;

a.BlA.foo
rewrite
    ^a\.([^.]+)\. (regex) -> a.BlA.foo
    into(newa.\1.) -> newa.BlA.foo
v.BlA.foo
nothing matched v.BlA.foo
b.BlA.foo
rewrite
    ^b\.([^.]+)\. (regex) -> b.BlA.foo
    into(newa.\_1.) -> newa.bla.foo
c.BlA.foo
rewrite
    ^c\.([^.]+)\. (regex) -> c.BlA.foo
    into(newa.\^1.) -> newa.BLA.foo
```

**Comment by grobian** [comment]
would this be sufficient for you?

**Comment by pschuermann** [comment]
thanks
