### ISSUE TITLE
RHEL Initscript is not LSB compliant

### ISSUE THREAD

**Issue by marco-hoyer** [grobian/carbon-c-relay#49]
On a RHEL based system, a service relay start fails with exit code 1, if the service is already running. I would prefer the init script to behave like described in the LSB: http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html.

Pull request follows.

**Comment by grobian** [comment]
done, thanks
