### ISSUE TITLE
High cpu consumption on carbon-c-relay worker threads

### ISSUE THREAD

**Issue by sombut** [grobian/carbon-c-relay#51]
Hello,

I've found the high cpu usage on the worker threads of the carbon-c-relay. The symptom and impact are mostly the same as the issue reported in this https://github.com/grobian/carbon-c-relay/issues/8 but only the trigger is different. Somehow there were some data that contains only "." sent from our client to our carbon-c-relay and cause this issue.

Step to reproduce is below. Could you help me fix this please?

echo -n "." | nc localhost 2003

**Comment by grobian** [comment]
thanks for reporting this

**Comment by sombut** [comment]
This is just to confirm the issue is fixed. Thank you.
