### ISSUE TITLE
more and more metrics being sent out due to aggregation?

### ISSUE THREAD

**Issue by Dieterbe** [grobian/carbon-c-relay#56]
Hi,
my setup:
* carbon-relay-ng, which sends all metrics it receives to multiple graphite servers (A,B andC), as well as carbon-c-relay
* carbon-c-relay is used just for aggregation. it does a few aggregations, and is configured to send the output of its aggregations also to A, B and C. (it shouldn't send anything else to A/B/C beside its aggregation results, i never verified this but it should be obvious from the config)

here's the config:

```
cluster all
    forward
        graphiteA:2003
        graphiteB:2003
        graphiteC:2003
    ;

aggregate
        ^stats\.dc1pweb[0-9]+\.request_by_country\.([^.]*)
    every 60 seconds
    expire after 60 seconds
    compute sum write to
        stats._sum_dc1pweb.request_by_country.\1
    ;

aggregate
        ^stats\.dc1[^.]+\.warehouselogger\.([^.]*)
    every 60 seconds
    expire after 60 seconds
    compute sum write to
        stats._sum_dc1.warehouselogger.\1
    ;

match _sum_dc1pweb.request_by_country
    send to all
    ;

match _sum_dc1.warehouselogger
    send to all
    ;

```

now the thing is, i didn't want to maintain the A/B/C list in carbon-c-relay as well, because that's what carbon-relay-ng is for, and this list changes too often.
so i modified the config, to instead of forward to A/B/C, forward to carbon-relay-ng:2003, feeding the output of carbon-c-relay back into carbon-relay-ng, which can then feed the aggregations into everywhere it needs to go.
so that means that stuff also feeds back into carbon-c-relay.
I didn't expect this to be an issue, because the regexes are carefully written to only match the input metrics, and not its own aggregation outputs.  However, it was. this is amount of metrics coming into carbon-relay-ng (it flattened back out because carbon-relay-ng hit 100% cpu and couldn't process anym roe)
![metrics](https://cloud.githubusercontent.com/assets/20774/6882568/9fac7ca8-d55f-11e4-9ad4-dab1064f4cb0.png)

i did some network sniffing on the relay machine and saw way too many metrics with `sum_dc1pweb` in them.  

did i misconfigure the relay? or is there any reason why this behavior would make sense? might it be a bug in the relay?

**Comment by grobian** [comment]
From what I understand from your story is that you simply created a loop, which the graph supports.  carbon-relay-ng sends metric A to the aggregator, which turns it into B. Then the aggregator (carbon-c-relay) sends B to carbon-relay-ng, which apparently sends B also to the aggregator (again).  The aggregator (just being a relay) sends B back to carbon-relay-ng which in turn sends it to the aggregator ... well, more and more of that.
If possible, you should filter what's being sent to carbon-c-relay, that is, only that what is matched to be aggregated, then you'll quash this loop.

**Comment by grobian** [comment]
(I assume you don't want to replace carbon-relay-ng, but obviously you could do everything with just carbon-c-relay, and avoid the whole possibility of this metric loop.)

**Comment by Dieterbe** [comment]
I think I get it.
so just to say it in my own words (let me know if i got it right):
carbon-c-relay doesn't relay (send into carbon-relay-ng) any metrics, except for the traffic matching either of the two `match` keywords) (otherwise traffic would have doubled each interval). my intention was for the `match` keywords to only match the output of the aggregators, but of course the aggregated metrics come back into the normal input of carbon-c-relay and are forwarded back because of that (in addition to aggregator output).

I'm a bit surprised though. If you don't mind i find this interesting and want to go a bit deeper:
It seems I have 369 series matching the first regex, and 179 for the second, i.e. 548 in total. (though they might not all be active at the same time)
from the graph we can see amount of metrics increased at about 2.5k in 20 minutes, so 
`2500/(20*60)` is about 2 per second. carbon-relay-ng is configured to flush every second. pretty sure a round trip between carbon-relay-ng takes on avg about 0.5 seconds up to a second.
does carbon-c-relay immediately relay what it gets, or does it also use buffering? 
I expected the roundtrip to be much quicker and the volume of metrics to increase much more rapidly, 
i also expected the increase to be quadratic over time (i.e. number of metrics doubling every interval)

Anyway..
You're right that I want to keep using carbon-relay-ng.  Is there a way to configure carbon-c-relay to only relay the output of the aggregations to a given endpoint/cluster?
or perhaps to never relay metrics with a timestamp that is a certain amount of time out of date?  Or to block certain metrics on input (but still relay them if metrics with the same name come out of the aggregator)?
It would be annoying and error prone to have to maintain a filter in carbon-relay-ng and keep it in sync with the aggregator config.

thanks!
Dieter

**Comment by grobian** [comment]
> carbon-c-relay doesn't relay (send into carbon-relay-ng) any metrics, except for the traffic matching either of the two match keywords)

yes, this is correct
In other words: a config with no match rules in them will never send anything out.

Since aggregations aren't a forwarding target themselves (there are some reasons for that, mostly simplicity internally), but match-rules do, the relay doesn't have enough knowledge (state) to tell what the origin of a metric is.  I fail to understand why the loop-behaviour of carbon-relay-ng is desired here, and why carbon-c-relay should work around it.  Conceptually, it feels wrong to send metrics to the aggregator that are the same as the metrics it would produce.  Currently, there is no way to match based on the origin of metrics.

carbon-c-relay doesn't use buffering, only queues to deal with blocking nature of external factors (servers). A roundtrip with carbon-c-relay should be <<0.5s.  I have no way to see what your metric means, or what exactly is going on.  I do agree that I'd expect quadratic behaviour, could it be that carbon-relay-ng does duplicate elimination somehow?  It's interesting to see how both relays interact with each other.

**Comment by Dieterbe** [comment]
> I fail to understand why the loop-behaviour of carbon-relay-ng is desired here

I don't aim to create a loop per se.  I just have a centralized bus (in this case carbon-relay-ng, could be something else like kafka) that is responsible for sending all metrics to all storage servers.  i currently have 3 storage servers that maintain each their own copy of everything.

this configuration (which storage servers are active) changes over time, and is only something the central pipeline should be concerned about and the config should only be maintained in one place, not in two (in my opinion) hence feeding aggregator output back into the central bus.
similarly, the central bus should (IMHO) not be concerned about what the metrics are the aggregator cares about, which it needs as input for its rules, how the output metrics look like, etc.  Especially since this configuration often changes. Hence my desire to just pipe everything to the aggregator instead of having to make the bus aware of aggregator configuration.

carbon-relay-ng doesn't eliminate duplicates. (the graph shows number of metrics received per second)

**Comment by grobian** [comment]
Hmmm, I see.  In that case you could run two relays, one to filter the input, the other to perform the aggregation.  It is a complex setup as well, but at least keeps the config isolated to one box.

Can we can an idea about which metrics are being sent back and forth?  A tcpdump for a 10 minutes perhaps?

**Comment by Dieterbe** [comment]
meh, i just decided to spend my day today implementing aggregation in -ng. that gets the job done too :p thanks anyway though.

**Comment by grobian** [comment]
That sounds like the best solution for this problem, indeed!
