### ISSUE TITLE
Could be possible a online  reload  of the configuration periodically ?

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#58]
Could be interesting for a critical production environment if carbon-c-relay could reload configuration files itself periodically without restarting the process.

Could be possible in a mid term?

**Comment by grobian** [comment]
I've implemented the reload config while running.  Doing inotify or something would not be that hard, but I wonder if just signalling the daemon to reload its config isn't enough.
I'm working on making the aggregations play nice with a config reload.

**Comment by filippog** [comment]
thanks for config reload @grobian ! is it good to go if aggregations aren't in use?

**Comment by grobian** [comment]
Yes, that should be, I've tested it with that.  The reload causes a small hickup, but shouldn't lose connections or metrics.

**Comment by toni-moreno** [comment]
hi @grobian , Thank you very much, is a very good new!

So If I understood . The reload is completely automatic? the daemon itself detect configuration changes? and reloads it by itself?

**Comment by grobian** [comment]
No, you have to tell the daemon to reload by sending it SIGHUP.  It will re-open logfiles, and re-load its config.  I can look into other ways if this is not sufficient.

**Comment by grobian** [comment]
I won't implement automatic reload, it's easy enough to SIGHUP the process.
