### ISSUE TITLE
Aggregation rules must appear before routing rules?

### ISSUE THREAD

**Issue by EvanKuhn** [grobian/carbon-c-relay#59]
Hi,

I was recently setting up carbon-c-relay and had trouble getting aggregations to work.  It seems that the aggregation configs must appear before the 'match' sections.

Eg. this did not work:

```
cluster caches
    fnv1a_ch
        127.0.0.1:2401 proto udp
        127.0.0.1:2402 proto udp
        127.0.0.1:2403 proto udp
        127.0.0.1:2404 proto udp
    ;

match *
    send to remotes
    stop
    ;

# Metric format: metrics.<dc>.<type>.host.<host>.<metric>
aggregate
        ^metrics\.([^.]+)\.([^.]+)\.host\.([^.]+)\.(.+)$
    every 10 seconds
    expire after 10 seconds
    compute sum write to
        metrics.\1.\2.all.sum.\4
    compute average write to
        metrics.\1.\2.all.avg.\4
    ;
```

But this did:

```
cluster caches
    fnv1a_ch
        127.0.0.1:2401 proto udp
        127.0.0.1:2402 proto udp
        127.0.0.1:2403 proto udp
        127.0.0.1:2404 proto udp
    ;

# Metric format: metrics.<dc>.<type>.host.<host>.<metric>
aggregate
        ^metrics\.([^.]+)\.([^.]+)\.host\.([^.]+)\.(.+)$
    every 10 seconds
    expire after 10 seconds
    compute sum write to
        metrics.\1.\2.all.sum.\4
    compute average write to
        metrics.\1.\2.all.avg.\4
    ;

match *
    send to remotes
    stop
    ;
```

This was running with version 0.39.  

Is this behavior intentional, or a bug?  The example configs in the README follow the non-working format, so at least we should update the README to avoid confusion.

Note that the above config is slightly modified from what I actually ran.  Apologies, but I haven't had time yet to put together a verified set of configs and script to reproduce the problem, but the above should work.  If it doesn't, I can get back to you with those (or better, a Vagrantfile).

Finally, thank you for your work on carbon-c-relay.  I find it to be a real improvement over the carbon-relay and aggregator: easier configuration, more flexible routing, and much more efficient.

Thanks again
-Evan

**Comment by grobian** [comment]
It doesn't work because you use "stop" on the match-rule.  You simply instruct it to stop processing after the match.  That is not what you want in this case, so simply removing the "stop" will make it work as you expect.
