### ISSUE TITLE
make number of workers default to number of available cpus

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#63]
Can you please elaborate on the following options:

```
 Options:
-w  use <workers> worker threads, defaults to 16
-b  server send batch size, defaults to 2500
-q  server queue size, defaults to 25000
-d  debug mode: currently writes statistics to log
-s  submission mode: write info about errors to log
-t  config test mode: prints rule matches from input on stdin
```

How do -w -b -q affect performance? -w seems to do nothing for me. -q seems to just lower the metrics  sent to carbon-cache.

**Comment by grobian** [comment]
`-w` allows you to multi-thread more or less, if you don't see huge amounts of cpu being taken, you can leave it alone.  On larger machines, you may want to increase the value to e.g. the number of available cpu cores.
`-b` specifies how many metrics are sent to a server at once at most, some receivers really choke when they get a large batch of metrics at once, and would need decreasing this value.  The larger the batch, the more efficient the sending gets.
`-q` the number of metrics that can be enqueued for sending to the server.  The bigger this value, the longer the relay can hold up metrics when the server can't handle, or is down, but also the more memory the relay will consume.

**Comment by druchoo** [comment]
```-w``` would you consider making an auto setting that uses # of cores?
```-t``` Can this be used to test rewrite rules?

**Comment by grobian** [comment]
`-w`: yeah, there's just no uniform way to do it, needs some platform specific work, which I was trying to avoid
`-t`: exactly

**Comment by druchoo** [comment]
```-w``` no worries, ```-w $(grep -c processor /proc/cpuinfo)``` works well enough :D
```-t``` how exactly? I have about 20 rules and would like the ability to see which rule(s) a metric hits

**Comment by grobian** [comment]
nproc should do the job as well

when run with `-t` just type the metrics in the console, for instance:
```
bla.foo.bar 
aggregation
    ^(bla.*)$ (regex) -> bla.foo.bar
    sum(\1_sum) -> bla.foo.bar_sum 
foo.bar
nothing matched foo.bar
```

**Comment by druchoo** [comment]
Well thanks for getting back to me so quickly. Not sure what I was doing wrong but got it working. thanks again.
