### ISSUE TITLE
stops listening on udp

### ISSUE THREAD

**Issue by piotr1212** [grobian/carbon-c-relay#64]
I've noticed that carbon-c-relay stops listening on the udp socket after some time (about a day). This is on rhel 6.6 with carbon-c-relay 0.39.

**Comment by grobian** [comment]
do you happen to send a lot of data (large packets) over udp to the relay?

**Comment by grobian** [comment]
would you mind giving the above commit a try to see if it fixes your issue?

**Comment by piotr1212** [comment]
Thank you for your fast response!! I will try this asap. I actually don't know what triggers it, suspect some vulnerability scanner... This also happened on servers which don't have any traffic on them (but are open to internal network).

**Comment by piotr1212** [comment]
This is running fine for 10 days now, closing, thanks

**Comment by grobian** [comment]
(this is in v0.40)
