### ISSUE TITLE
Questions on hashes

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#65]
How are carbon_ch/fnv1a_ch hashes calculated?
On start of carbon-c-relay? 
Where is this information stored?

Basically I want to know if i use carbon_ch/fnv1a_ch hashing, is hash recalculated every time carbon-c-relay is restarted? And how do I rebalance if that's the case. I'm thinking a rule base approach may be better.

All questions above are in regards to sharding and not for distributing among local carbon-caches.

-Thanks

**Comment by deniszh** [comment]
IIRC carcbon_ch hashing is compatible with original graphite's hashing, so, you can use [carbonate](https://github.com/jssjr/carbonate) for rebalancing. It's written in python, so, can be changed for fnv1a_ch hashing too theoretically...
But maybe @grobian has some other tooling for that.

**Comment by deniszh** [comment]
PS: all hashing is in https://github.com/grobian/carbon-c-relay/blob/a4a6fa98d4b2db325e9aaafac900a444d6186b61/consistent-hash.c, lines [49-62](https://github.com/grobian/carbon-c-relay/blob/a4a6fa98d4b2db325e9aaafac900a444d6186b61/consistent-hash.c#L49-L62) for carbon_ch and lines [64-78](https://github.com/grobian/carbon-c-relay/blob/a4a6fa98d4b2db325e9aaafac900a444d6186b61/consistent-hash.c#L64-L78) for fnv1a_ch

**Comment by deniszh** [comment]
PSS: Some people uses rules for sharding, some are using hashing + rebalancing. Rebalancing is pain, but coping with ton of rules is not less pain. Unfortunately.

**Comment by druchoo** [comment]
@deniszh thanks for the insight. So actual hash only changes if adding or removing nodes, correct? Restarting any processes would have no affect.

**Comment by deniszh** [comment]
Yes, if you didn't change IP/instances (for carbon_ch) or IP/ports (for fnv1a_ch) hash ring will be stable.

**Comment by druchoo** [comment]
@deniszh Thanks for answering my questions. We'll be using rule based routing. At this time it suits us best. Closing this out now.
