### ISSUE TITLE
Crashes with Segmentation fault.

### ISSUE THREAD

**Issue by aaronm54** [grobian/carbon-c-relay#66]
I updated with the latest code this morning and now I am getting a segmentation fault immediately when the program starts.

Core was generated by `./relay -f relay.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000003f748842b9 in __memset_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64 keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.10.3-33.el6.x86_64 libcom_err-1.41.12-18.el6_5.1.x86_64 libselinux-2.0.94-5.3.el6_4.1.x86_64 openssl-1.0.1e-30.el6_6.8.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000003f748842b9 in __memset_sse2 () from /lib64/libc.so.6
#1  0x000000000040c2a6 in aggregator_add_compute (s=<value optimized out>, metric=0x1c5ad3b "agg.\\1.\\2.\\3.summary.requests",
    type=<value optimized out>) at aggregator.c:111
#2  0x0000000000407ceb in router_readconfig (clret=0x610540, rret=0x610548, path=<value optimized out>, queuesize=25000, batchsize=2500) at router.c:951
#3  0x0000000000402705 in main (argc=3, argv=0x7fff5bf665f8) at relay.c:367

**Comment by grobian** [comment]
err, oops, that's embarassing

**Comment by grobian** [comment]
This should help a lot, please reopen if it doesn't fix it for you.

**Comment by aaronm54** [comment]
That did the trick.  Thanks for the quick response.
