### ISSUE TITLE
Doc about  server send batch size ?

### ISSUE THREAD

**Issue by liyichao** [grobian/carbon-c-relay#69]
I set it `-b 10000` but when I tcpdump on a `cluster`, I see a lot packets with size < 3000, where there is < 20 datapoints in it. Should not it be 10000 datapoints in a packet ?

I concern about this because influxdb's batch write is related to size of batches sent to it. See https://github.com/influxdb/influxdb/issues/2554 .

**Comment by deniszh** [comment]
Off-topic: I'm wondering why you using carbon-c-relay for pointing to
InfluxDB? For aggregation only?

6:19, ср, 13.05.2015, Li Yichao <notifications@github.com>:

**Comment by liyichao** [comment]
@deniszh 

We use it for 

1. We are trying influxdb 0.9, so we point some metrics to influxdb 0.9, others to influxdb 0.8
2. We have an realtime alterting system which needs realtime metric, so all metrics sent to influxdb also sent to the alerting system.
3. Rewrite. Influxdb 0.9 needs metric names of specific structure, we use carbon-c-relay to make metric names influxdb 0.9 friendly.
4. Batching.

**Comment by grobian** [comment]
Batching in carbon-c-relay is just an upper limit.  carbon-c-relay has an objective to route/deliver metrics as fast as possible.

**Comment by grobian** [comment]
I believe carbon-relay-ng has batch delivery built-in.
