### ISSUE TITLE
md5 standalone implementation?

### ISSUE THREAD

**Issue by filippog** [grobian/carbon-c-relay#70]
hi,
AFAICT openssl is brought in only for MD5(), would a standalone openssl-compatible md5 implementation something willing to be considered?

**Comment by grobian** [comment]
Yes, it is, as long as it doesn't poison the licence scheme.  Another reason I chose to use OpenSSL's one is that it is heavily optimised with ASM and such, which is nice, for the MD5 sum used in carbon_ch is really heavy.
I can also see autotooling in the future as something thay may be necessary, to control whether carbon_ch should be available, if we should use internal MD5, or openssl, or ... implementation.  When we have configure, we can also remove the openmp dependency which is now used only for getting the number of cpu cores.  (upside: almost any compiler has OpenMP these days.)

**Comment by Civil** [comment]
Just a quick note - clang < 3.7 don't have OpenMP support.

**Comment by grobian** [comment]
yes, therefore:
```        tc-has-openmp || sed -i -e '/-fopenmp/s/^/#/' Makefile```

**Comment by filippog** [comment]
I haven't seen any asm-md5 public implementation and the closest licence-wise is probably http://openwall.info/wiki/people/solar/software/public-domain-source-code/md5, good point wrt speed, that alone probably isn't worth chasing other implementations

re: autotools, how would that cater for runtime # cores detection?

**Comment by grobian** [comment]
That looks pretty good, and easy replacement in the current code too (due to OpenSSL compatibility).

autotools: cpu core detection requires some OS-specific probing

**Comment by filippog** [comment]
btw looks like clang got openmp support too: http://blog.llvm.org/2015/05/openmp-support_22.html

**Comment by Civil** [comment]
Only in 3.7, which is planed to be released in august.

**Comment by filippog** [comment]
looks good, thanks @grobian !
