### ISSUE TITLE
dropped metrics

### ISSUE THREAD

**Issue by scbunn** [grobian/carbon-c-relay#73]
We are current running two tiers of relays.  Out systems are sending UDP to the first tier of relays and then those relays send TCP to the send tier of relays that shard the data across 12 caches.  On a few of our first tier relays we are seeing "dropped" metrics.  I'm trying to determine what exactly a dropped metric is so I can troubleshoot it.  Is this a metric that the was dropped from system to relay or from relay to 2nd tier relay?

These relays are on VMs with 2GB of memory.  I don't see any resource crunch on the VM.

**Comment by grobian** [comment]
dropped metrics are those that the relay had to drop because its buffers were full

so in your case from the 1st to the 2nd tier

It may be worth trying to increase the queuesize to give the relay a bit more space to hold metrics in (e.g. when you have bursts)

**Comment by scbunn** [comment]
@grobian Fantastic.  Increasing the queue size (as well as increasing the batch size) has eliminated our dropped metrics.
