### ISSUE TITLE
">" being replaced with "_"

### ISSUE THREAD

**Issue by chjohnst** [grobian/carbon-c-relay#74]
One of my app teams here is sending metrics with a "->" in it, which works fine on graphites carbon implementation and several other ingestors, but when I use the carbon-c-relay its replacing the ">" with a "_".  Not sure if I can say this is a bug or just a code change required to support it.  Getting my app team to change their code is unlikely at this point.

from: metric.1->2 
to: metric.1-_2

**Comment by grobian** [comment]
this is a feature ;)

> on a filesystem probably works, but is a pain.  If you want, you can allow the char in your copy of carbon-c-relay, I guess here:
https://github.com/grobian/carbon-c-relay/blob/master/dispatcher.c#L380

**Comment by grobian** [comment]
The sensical thing to do is make it an option to specify which chars you want to "allow".  But I'm not sure if it's really worth the hassle.  I do understand your case, however.

**Comment by chjohnst** [comment]
I am currently doing something similar to above to allow the char ">" but would be nice if if that was supported by default :-)

**Comment by grobian** [comment]
Fedora/EPEL seems to add a patch to allow `#` similar like you want `>`.  I'm going to turn it into a config option to make everyone happy.

**Comment by chjohnst** [comment]
Thanks!
