### ISSUE TITLE
Any way to write more compact match syntax?

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#77]
I will use carbon-c-relay as a a way to distribute metrics across several graphite backends. In order to do this I will create a config. file with more than 1000 match rules ( these rules could change in time and I will create a script to recreate them 

this is current syntax ,  is fine but not really  scripting friendly.

```
match "^serversA\."
    send to backend_A
    stop
    ;

match "^serversB\,"
    send to backends_B
    stop
    ;
```

I would like  something like that, that I could easily recreate , scan and filter with external scripts.

```
match  "^serversA\." send to backend_A stop ;
match  "^serversB\." send to backend_B stop ;
```

**Comment by grobian** [comment]
I don't understand very well.  Both rules you wrote are equivalent and accepted by the parser.

**Comment by toni-moreno** [comment]
OK!  I didn't see this syntax in the documentation  before !

thank you very much!!
