### ISSUE TITLE
revisiting consistent-hashing & cache-names from #34

### ISSUE THREAD

**Issue by elijah** [grobian/carbon-c-relay#79]
Testing the feature that came from issue #34 - I get errors.

I'm running 0.40, and this seems not to work -- I get errors like so:

{code}
root@ init.d]# /usr/sbin/carbon-c-relay -f /etc/carbon/carbon-c-relay-default.conf -p 2015 -i 0.0.0.0
[2015-07-10 21:27:07] starting carbon-c-relay v0.40 (2015-06-26), pid=9736
configuration:
relay hostname = my-test-host
listen port = 2015
listen interface = 0.0.0.0
workers = 5
send batch size = 2500
server queue size = 25000
statistics submission interval = 60s
routes configuration = /etc/carbon/carbon-c-relay-default.conf

[2015-07-10 21:27:07] expected port, or unexpected data at '2004=a' for cluster local
[2015-07-10 21:27:07] failed to read configuration '/etc/carbon/carbon-c-relay-default.conf'{code}

My host references are in the format that i understand is to be expected here - e.g.:

"xx.xx.xx.xx:2004=a"

**Comment by grobian** [comment]
confirmed, this broke somewhere

**Comment by grobian** [comment]
ehm, no this didn't break.

what doesn't work is:
`cluster x forward 127.0.0.1:2004=a`

what /does/ work is:
`cluster x carbon_ch 127.0.0.1:2004=a`

the instance is only valid with carbon_ch clusters.  What cluster type is local in your case?

**Comment by elijah** [comment]
It looks like you're right -- my cluster that *should* be set to carbon_ch for compat with existing relays is set to forward.  :)  I'll fix that and try again.  [I rewrote an erb template out of someone else's chef cookbook to implement this, and I missed this bit.]

**Comment by elijah** [comment]
Confirmed, my config was bad.  :)
