### ISSUE TITLE
Writing directly to the file system no longer works?

### ISSUE THREAD

**Issue by costimuraru** [grobian/carbon-c-relay#81]
My `relay.conf` contains this:
```
cluster local_file
    file
        /tmp/carbon_c_relay.data
    ;
```

When trying to start the daemon (`./relay -f contrib/relay.conf`) this is the error I receive:
```
starting carbon-c-relay v0.40 (common.v2.1.0-148-ge0b5d0-dirty), pid=4885
configuration:
    relay hostname = platform
    listen port = 2003
    workers = 1
    send batch size = 2500
    server queue size = 25000
    statistics submission interval = 60s
    routes configuration = contrib/relay.conf

[2015-07-17 19:27:47] unknown cluster type 'file' for cluster local_file
[2015-07-17 19:27:47] failed to read configuration 'contrib/relay.conf'
```

**Comment by grobian** [comment]
the versiontag suggests local changes and modifications, are you sure they aren't causing this problem?

**Comment by costimuraru** [comment]
I've just downloaded the source code from https://github.com/grobian/carbon-c-relay/releases/tag/v0.40 and compiled it. No changes made.
Is there somewhere I could download the binary files from directly or perhaps a rpm / docker image?

**Comment by grobian** [comment]
0.40 doesn't have the feature yet, I'm about to do a release with the feature soon.

**Comment by costimuraru** [comment]
Got it. I also noticed that carbon-c-relay is in EPEL. Awesome!

**Comment by grobian** [comment]
It is? AWESOME!

**Comment by grobian** [comment]
Closing this, am going to release v0.41 soon
