### ISSUE TITLE
Configuration file: aggregate section must be above match section (contrary to what the Readme and relay.conf say)

### ISSUE THREAD

**Issue by costimuraru** [grobian/carbon-c-relay#82]
Looking over the readme we can see that aggregate section is the last in configuration file. After trying this I was unable to see the aggregated metrics in whisper. 2 hours later I decided to put the `aggregate` section above the `match` section and success: I could see the aggregated metrics being sent. I don't know if the order described in the readme used to work in the past (I'm using version 0.40), but if it's not working anymore, let's update the wiki.

```
# comments are allowed in any place and start with a hash (#)

cluster <name>
    <forward | any_of [useall] | failover | <carbon_ch | fnv1a_ch> [replication <count>]>
        <host[:port] [proto <udp | tcp>]> ...
    ;
cluster <name>
    file
        </path/to/file> ...
    ;
match <* | <expression>>
    send to <cluster | blackhole>
    [stop]
    ;
rewrite <expression>
    into <replacement>
    ;
aggregate
        <expression> ...
    every <interval> seconds
    expire after <expiration> seconds
    [timestamp at <start | middle | end> of bucket]
    compute <sum | count | max | min | average> write to
        <metric>
    [compute ...]
    ;
```

What worked was:
```
aggregate
        <expression> ...
    every <interval> seconds
    expire after <expiration> seconds
    [timestamp at <start | middle | end> of bucket]
    compute <sum | count | max | min | average> write to
        <metric>
    [compute ...]
    ;

match <* | <expression>>
    send to <cluster | blackhole>
    [stop]
    ;
```

**Comment by grobian** [comment]
My suspicion is that you used a stop rule, in which case this is a feature, not a bug :).  Can you share your anonymised config?

**Comment by costimuraru** [comment]
Yes, indeed there was a stop rule. 
Moreover I cam across this in the read me: "Also, since aggregations appear as matches without stop keyword, their positioning matters in the same way ordering of match statements."
I like this as a feature, but do you think we could make it more clear that a `stop` clause before an aggregation will make the process ignore the latter?

Thanks for your help!

```
cluster local_carbon
  carbon_ch
    127.0.0.1:2013=a
  ;
match *
  send to local_carbon
  stop
  ;
aggregate
        ^sys\.dc[0-9].(somehost-[0-9]+)\.([^.]+)\.mysql\.replication_delay
    every 10 seconds
    expire after 35 seconds
    compute sum write to
        mysql.host.\1.replication_delay
    compute sum write to
        mysql.host.all.replication_delay
    compute sum write to
        mysql.cluster.\2.replication_delay
    compute sum write to
        mysql.cluster.all.replication_delay
    ;
```

**Comment by grobian** [comment]
The idea of the "stop" keyword is to indicate that processing stops.  If you have any suggestions on how to make it obvious to everyone that the config you just printed never aggregates anything, I'm all ears!

Thinking of it, I'm wondering if I can make the optimiser smart enough to e.g. warn about this situation.
warning: aggregate ^sys.... will never be matched due to preceding match *.

**Comment by grobian** [comment]
```
% ./relay -t -f issue82.conf  
[2015-07-22 13:57:27] starting carbon-c-relay v0.40 (af8264-dirty), pid=20566
configuration:
    relay hostname = Priscilla
    listen port = 2003
    workers = 5
    send batch size = 2500
    server queue size = 25000
    statistics submission interval = 60s
    routes configuration = issue82.conf

[2015-07-22 13:57:27] warning: aggregate ^sys\.dc[0-9].(somehost-[0-9]+)\.([^.]+)\.mysql\.replication_delay will never be matched due to preceeding match * ... stop
parsed configuration follows:
cluster local_carbon
    carbon_ch replication 1
        127.0.0.1:2013=a
    ;
```
...

**Comment by costimuraru** [comment]
That's awesome!  Thanks @grobian
