### ISSUE TITLE
libgomp dependency in centos 6

### ISSUE THREAD

**Issue by nicktgr15** [grobian/carbon-c-relay#88]
Hi,

I'm getting the following error when starting the carbon-c-relay service in centos 6. I'm using the spec file provided with version 0.43 to build the rpm. 

```
/usr/bin/cc_relay: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
```

If I ```yum install libgomp``` then carbon-c-relay works fine. Should libgomp be in the Requires list in the spec? We were using version 0.33 before and libgomp wasn't a dependency so it must have been introduced afterwards. 

Regards,
Nick

**Comment by grobian** [comment]
Yeah, that feels like a missing dep.  Honestly, I feel we should stick to the spec-file that's in EPEL/Fedora now. @piotr1212 can I have green light on this one to remove the rpm bits from this repo?  I did some searching for the debian bits, and it seems they are upstream too, but wasn't too sure.

**Comment by nicktgr15** [comment]
Yes, we just discovered the EPEL carbon-c-relay and we are going to use that one instead. Thank you for your quick response.

**Comment by piotr1212** [comment]
I think I have the Requires missing in the EPEL spec too, will check it in a bit/push new packages.

@grobian  I'm not using the spec in this repo, not sure if others prefer this one..? I don't mind deleting it from this repo.

**Comment by grobian** [comment]
I'll remove the spec stuff from carbon-c-relay.git.  Thanks!

**Comment by piotr1212** [comment]
FYI: libgomp is automatically included as Requires through the autorequires script which runs by rpmbuild during building. 

This feature is explicitly disabled in the spec in contrib:
AutoReqProv: no

**Comment by filippog** [comment]
@grobian FWIW 0.40 got uploaded to Debian a month ago, https://packages.qa.debian.org/c/carbon-c-relay.html with a different `debian/` directory if you want to drop that as well

**Comment by grobian** [comment]
yes, I do, thanks!
