### ISSUE TITLE
router.c:266: Resource leak: cnf

### ISSUE THREAD

**Issue by dcb314** [grobian/carbon-c-relay#92]
if ((cnf = fopen(path, "r")) == NULL || stat(path, &st) == -1)
        return 0;

Maybe better code

    if ((cnf = fopen(path, "r")) == NULL)
        return 0;
    if (stat(path, &st) == -1) {
        fclose(cnf);
        return 0;
    }

**Comment by grobian** [comment]
Nice one, applied.
