### ISSUE TITLE
Infinity loop in aggregation

### ISSUE THREAD

**Issue by szibis** [grobian/carbon-c-relay#94]
I have manage to create loop by simple mistake and this infinity loop create 3mln metrics in 2 minutes bringing freespace in cluster to knees.

I use latest version: carbon-c-relay v0.43 (5c523b)

#### Configuration:

```
 aggregate
         ^diamond\.([^.]+)\.([^.]+)\.([^.]+)\.([^.]+)\.[^.]+\.processcpu\.([^.]+)
     every 30 seconds
     expire after 35 seconds
     compute average write to
        diamond.\1.\2.\3.\4.all.processcpu.\5.average
    compute average write to
        diamond.\1.\2.\3.all.all.processcpu.\5.average
     compute max write to
        diamond.\1.\2.\3.\4.all.processcpu.\5.max
     compute max write to
        diamond.\1.\2.\3.all.all.processcpu.\5.max
     ;

match ^diamond.*.all.*
    send to local-relays
    stop
    ;
```

This generates infinity loop of multiple metrics as in example of created path: 
```
/opt/graphite/storage/whisper/diamond/production/us-east-1/testservice/all/all/processcpu/nginx/max/max/max/average/max/max/max/max/max/max/max/max/max/max/max/max/max/max/max/max/average/average/max/average/average/max/max/max/max/max/average.wsp
```
Is there any chance to secure this maybe just like in web servers that detects infinity loop in redirects and cut off when gets defined level of depth.

We would like to add aggregation to hands of many people and possibility of cluster kill is huge.

**Comment by grobian** [comment]
congrats!

The only way out of here is to be able to specify an output cluster on aggregations like match rules.

I wanted to implement this for a while, for I shot myself in the foot with this as well.

The reason I did it this way, is because the output can be routed to different clusters this way.  But reality check says we use different servers/instances for the aggregation and let the routing be done elsewhere.  So I guess it may be a nice feature to allow output to be set, to avoid these nice loops.

By the way, did the relay crash?

**Comment by szibis** [comment]
Hi, Thanks for quick response.

Yes it was to open match rule in send to but still yes this feature would be very nice. It is very simple to hit this issue.

As i have different node's for aggregation i can use here only aggregation configuration, but still writing to same graphite cluster.

Carbon-c-relay as aggregator node survive whole thing, adding some graphs, maybe this will be helpfull.

![aggregation_1](https://cloud.githubusercontent.com/assets/329831/9270298/ed6268da-4270-11e5-8990-a43ee9c3b9e6.jpg)

![aggregation_2](https://cloud.githubusercontent.com/assets/329831/9270302/f219b1b2-4270-11e5-9c66-7543eeb423d1.jpg)

**Comment by szibis** [comment]
Sorry it was 8 minutes in total, but still high generation rate.

![metrics_vs_creates](https://cloud.githubusercontent.com/assets/329831/9299871/9e126ce2-44c0-11e5-9a8d-92fcb2cc2fa0.jpg)

Carbon-c-relay on top and on store servers. Store servers with SSD drives and summary of 100 carbon-cache daemons do the job :smile:

**Comment by dforste** [comment]
What is the best way to deal with aggregation? Do you have an example somewhere? 
It seems you advocate: 
Relay => Aggregator (Send only metrics you want aggregated here)
Aggregator ? Send everything and aggregate to storage? 

Is there a good way to aggregate a metric without sending the points you aggregated? I have tried the following with mixed results: 
```
###############################################################################
#
#  Define Aggregations we want to use and drop non aggregated metrics. 
#
###############################################################################
aggregate
    ^app\.([^.]+)\.dc\.([^.]+)\.env\.([^.]+)\.site\.([^.]+)\.pages\.([^.]+)\.count
	every 60 seconds
	expire after 35 seconds
	compute sum write to 
	  aggregated_app.\1.dc.\2.env.\3.site.\4.pages.\5.count
	;
match ^app\.([^.]+)\.dc\.([^.]+)\.env\.([^.]+)\.site\.([^.]+)\.pages\.([^.]+)\.count
  send to blackhole
  stop
  ;

###############################################################################
#
#  Rewrite aggregated metrics back to their original selves. 
#
###############################################################################
rewrite aggregated_([^.]+)\.(.+)
  into \1.\2
  ;

###############################################################################
#
#  Send all metrics home. 
#
###############################################################################
match *
  send to local
  stop
  ;

```
With the above with multiple items sometimes they go threw but sometimes they just drop. If I want to aggregate a metric for a time period do I need 3 relays? 
Relay => Aggregator 
(Send metrics I want to the Aggregator.)
Aggregator => Post Aggregation Relay 
(Aggregate metrics to a new name and send them to the post aggregator.)
Post Aggregator => Storage 
(Rewrite the aggregated metric back to the original and then send to storage.)

**Comment by grobian** [comment]
Assuming that local is another store/relay (and not self), this config should more or less be the only way to do it right now. I'll have to see for myself if this doesn't pass through the metrics.

**Comment by dforste** [comment]
This configuration on the aggregator worked for one point and then failed. 
carbon-c-relay v0.44 (38fac7)
```
configuration:
    relay hostname = carbon-c-relay-aggregator-1
    listen port = 2003
    workers = 8
    send batch size = 2500
    server queue size = 25000
    statistics submission interval = 60s
    routes configuration = /conf/carbon-c-relay.conf

parsed configuration follows:
cluster aggregator-post
    failover
        aggregatorpost:2003
        failover:2003
    ;

rewrite ^carbon\.(.*)
    into system.carbon.\1
    ;
aggregate
        ^app\.([^.]+)\.dc\.([^.]+)\.env\.([^.]+)\.store\.([^.]+)\.pages\.([^.]+)\.count
    every 60 seconds
    expire after 35 seconds
    timestamp at end of bucket
    compute sum write to
        aggregated_app.\1.dc.\2.env.\3.store.\4.pages.\5.count
    ;
match ^system\.carbon\.(.*)
    send to aggregator-post
    stop
    ;
match ^aggregated_(.*)
    send to aggregator-post
    stop
    ;
match *
    send to blackhole
    stop
    ;
```

Any idea why aggregated metrics never make it to aggregator-post? The carbon ones do.

**Comment by grobian** [comment]
I think this is because of a bug fixed earlier but not in any release, you specified an expire < the bucket interval.  Current git master says:

[2015-10-13 21:53:34] expire (35) must be greater than interval (60)
[2015-10-13 21:53:34] failed to read configuration 'issue94.conf'

**Comment by dforste** [comment]
Created a docfix pr. https://github.com/grobian/carbon-c-relay/pull/111

**Comment by grobian** [comment]
I've tested this with 95 and 35, and it seems to work for me with those values.

**Comment by grobian** [comment]
I've prepared the way in the current git code to add "send to <cluster>" support to the aggregate rules.  This will hopefully make it much simpler (and maybe intuitive) to deal with aggregation rules.

**Comment by dforste** [comment]
YAY! Thank you so much. Is there a stable release in which to do this with?

**Comment by grobian** [comment]
currently testing this:
```
cluster graphite
    forward
        127.0.0.1:2004
    ;

aggregate ^sys\.somemetric
    every 60 seconds
    expire after 75 seconds
    timestamp at end of bucket
    compute sum write to
        sys.somemetric
    send to graphite
    ;
match *
    send to graphite
    ;
```
also with stop in the aggregate, it seems to work well

**Comment by dforste** [comment]
Segmentation fault (core dumped) 

I built off git checkout https://github.com/grobian/carbon-c-relay/commit/e81fb724cfff3b8fe254e7f08d3c9c846a402533
What debug steps do you want me to take?

**Comment by grobian** [comment]
any chance you could get me a stacktrace, or give me your config?

**Comment by dforste** [comment]
There didn't seem to be any stacktrace to stdout. Here is the config:
```
###############################################################################
#
#  Define clusters that we will manage.
#
###############################################################################
cluster local
  forward
    gocarbon
  ;


###############################################################################
#
#  Define any rewrite rules you might want.
#
###############################################################################
# carbon-c-relay metrics should go under system.
rewrite ^carbon\.(.*)
  into system.carbon.\1
  ;

###############################################################################
#
#  Define Aggregations we want to use.
#
###############################################################################

#access-logs page counts
aggregate
    ^app\.([^.]+)\.dc\.([^.]+)\.env\.([^.]+)\.store\.([^.]+)\.pages\.([^.]+)\.count
        every 60 seconds
        expire after 90 seconds
        compute sum write to
          aggregated_app.\1.dc.\2.env.\3.store.\4.pages.\5.count
        send to local
        ;


###############################################################################
#
#  Send carbon metrics home. If you want another metric to be sent do it here.
#
###############################################################################
match ^system\.carbon\.(.*)
  send to local
  stop
  ;
```

**Comment by grobian** [comment]
When does this crash for you? Immediately, or after a while, or when traffic hits it?

**Comment by dforste** [comment]
Let me test out. I was throwing traffic at it immediately but let me see if it crashes without it.

**Comment by grobian** [comment]
I got a crash too, but only when compiled with optimisation.  That explains why my testing didn't reveal it.

**Comment by grobian** [comment]
ok, that was not where I expected it to be, but should work better now.

**Comment by grobian** [comment]
This is going to be in a release soon, which should make this all less confusing.
