### ISSUE TITLE
Feature request: whitelisting

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#98]
My use-case: I want to drop all metrics, unless it matches a regex like:

```
^(?:containers|cacti|carbon|cronacle|events|jmeter|omniture|oracle|perftest|puppet|rum|servers|statsd|sitespeed|storage|virt)\.
```

Is it possible to add a "not_match" operator? So I could do something like:
```
not_match ^(?:aap|noot|mies)\.
    send to blackhole stop;
```

Note: I have tried to use the "match", but that does not work:
```
(ERR) invalid expression '^(?!(?:containers|cacti|carbon|cronacle|events|jmeter|omniture|oracle|perftest|puppet|rum|servers|statsd|sitespeed|storage|virt)\.)' for match: Invalid preceding regular expression
```

**Comment by deniszh** [comment]
I'm not author of project, but I suspect that built-in regex parser just didn't know about "negative lookaheads" (but not sure why you use it here) and complains for it.
IMO for sake of simplicity and readability you can rewrite you rules as:
```
match (containers|cacti|carbon|cronacle|events|jmeter) send to cluster stop;
match (omniture|oracle|perftest|puppet|rum) send to cluster stop;
match (servers|statsd|sitespeed|storage|virt) send to cluster stop;
match * send to blackhole stop;
```

**Comment by rtoma** [comment]
Oh nice one! That off course works too.

But this solution has a performance penalty for me, since I am sending to 3 clusters (local caches, remote caches + legacy cluster) these matches have to be executed 3 times. Let's see if the overhead is noticeable.

And ... I guess I was overcomplicating things. A mindset I have been getting used to, to get Graphite working with original parts.

**Comment by deniszh** [comment]
carbon-c-relay is powerful thing.
IIRC it has (had?) performance problems with single-thread aggregator, but normal matches are quite fast.

**Comment by grobian** [comment]
Like deniszh says, whitelisting is implicit by matching.  If you have a performance problem, let me know, and I'll optimise the matches into one.

You don't need the match * send to blackhole in this example by the way, for all metrics that didn't match anything are silently dropped.

**Comment by rtoma** [comment]
I'll implement startswith matching as whitelist. That works for me.

Closing this issue
