### ISSUE TITLE
Collecting carbon-c-relay stats when running >1 relay per host

### ISSUE THREAD

**Issue by nherson** [grobian/carbon-c-relay#99]
I am trying to build a graphite cluster where 2 carbon-c-relay's run on each host.  It looks like both processes will generate statistics and prefix them with `carbon.relays.HOSTNAME....`

It would be useful if an optional flag could be given at runtime that would add a tag to the end of the prefix, in the event of running multiple relays on a single host.

E.g. suppose I have 2 relays. I want to be able to run something like
`carbon-c-relay [ ... other options ... ] -T TAG`
which would make stats about this relay appear in graphite with the prefix `carbon.relays.HOSTNAME-TAG`

**Comment by grobian** [comment]
The -H <hostname> flag was introduced for this purpose, so you can set it to <HOSTNAME>-<TAG> yourself.  Does that solve the issue for you sufficiently?

**Comment by nherson** [comment]
Yeah that is what I was looking for. This will do exactly what I want. Solves my issue.
